pages = [{"l":"index.html#","e":false,"i":"","n":"Grapple","t":"Grapple","d":"","k":"static","x":""},
{"l":"grapple/json.html#","e":false,"i":"","n":"grapple.json","t":"grapple.json","d":"","k":"package","x":""},
{"l":"grapple/json.html#\\-ffffffa9","e":false,"i":"extension (json: JsonValue)","n":"\\","t":"\\(key: String): JsonValue","d":"grapple.json","k":"def","x":""},
{"l":"grapple/json.html#\\-fa7","e":false,"i":"extension (json: JsonValue)","n":"\\","t":"\\(index: Int): JsonValue","d":"grapple.json","k":"def","x":""},
{"l":"grapple/json.html#\\\\-92","e":false,"i":"extension (json: JsonValue)","n":"\\\\","t":"\\\\(key: String): Seq[JsonValue]","d":"grapple.json","k":"def","x":""},
{"l":"grapple/json.html#arrayJsonInput-fffffd42","e":false,"i":"","n":"arrayJsonInput","t":"arrayJsonInput[T](using input: JsonInput[T])(using ctag: ClassTag[T]): JsonInput[Array[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#arrayJsonOutput-fffff871","e":false,"i":"","n":"arrayJsonOutput","t":"arrayJsonOutput[T](using output: JsonOutput[T]): JsonOutput[Array[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#bigDecimalJsonInput-0","e":false,"i":"","n":"bigDecimalJsonInput","t":"bigDecimalJsonInput: JsonInput[BigDecimal]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#bigDecimalJsonOutput-0","e":false,"i":"","n":"bigDecimalJsonOutput","t":"bigDecimalJsonOutput: JsonOutput[BigDecimal]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#bigIntJsonInput-0","e":false,"i":"","n":"bigIntJsonInput","t":"bigIntJsonInput: JsonInput[BigInt]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#bigIntJsonOutput-0","e":false,"i":"","n":"bigIntJsonOutput","t":"bigIntJsonOutput: JsonOutput[BigInt]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#booleanJsonInput-0","e":false,"i":"","n":"booleanJsonInput","t":"booleanJsonInput: JsonInput[Boolean]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#booleanJsonOutput-0","e":false,"i":"","n":"booleanJsonOutput","t":"booleanJsonOutput: JsonOutput[Boolean]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#doubleJsonInput-0","e":false,"i":"","n":"doubleJsonInput","t":"doubleJsonInput: JsonInput[Double]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#doubleJsonOutput-0","e":false,"i":"","n":"doubleJsonOutput","t":"doubleJsonOutput: JsonOutput[Double]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#eitherJsonInput-fffff2c3","e":false,"i":"","n":"eitherJsonInput","t":"eitherJsonInput[A, B](using left: JsonInput[A])(using right: JsonInput[B]): JsonInput[Either[A, B]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#eitherJsonOutput-fffffbfd","e":false,"i":"","n":"eitherJsonOutput","t":"eitherJsonOutput[A, B, C <: (Either)](using left: JsonOutput[A])(using right: JsonOutput[B]): JsonOutput[C[A, B]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#failureJsonOutput-0","e":false,"i":"","n":"failureJsonOutput","t":"failureJsonOutput: JsonOutput[Failure[_]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#floatJsonInput-0","e":false,"i":"","n":"floatJsonInput","t":"floatJsonInput: JsonInput[Float]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#floatJsonOutput-0","e":false,"i":"","n":"floatJsonOutput","t":"floatJsonOutput: JsonOutput[Float]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#intJsonInput-0","e":false,"i":"","n":"intJsonInput","t":"intJsonInput: JsonInput[Int]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#intJsonOutput-0","e":false,"i":"","n":"intJsonOutput","t":"intJsonOutput: JsonOutput[Int]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#iterableJsonInput-fffff2ea","e":false,"i":"","n":"iterableJsonInput","t":"iterableJsonInput[T, C <: (Iterable)](using input: JsonInput[T])(using factory: Factory[T, C[T]]): JsonInput[C[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#iterableJsonOutput-eb2","e":false,"i":"","n":"iterableJsonOutput","t":"iterableJsonOutput[T, C <: (Iterable)](using output: JsonOutput[T]): JsonOutput[C[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonArrayJsonInput-0","e":false,"i":"","n":"jsonArrayJsonInput","t":"jsonArrayJsonInput: JsonInput[JsonArray]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonBooleanJsonInput-0","e":false,"i":"","n":"jsonBooleanJsonInput","t":"jsonBooleanJsonInput: JsonInput[JsonBoolean]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonFieldConversion-bdd","e":false,"i":"","n":"jsonFieldConversion","t":"jsonFieldConversion[T](using output: JsonOutput[T]): Conversion[(String, T), (String, JsonValue)]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonInputConversion-fffff4ea","e":false,"i":"","n":"jsonInputConversion","t":"jsonInputConversion[T](using input: JsonInput[T]): Conversion[JsonValue, T]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonNullJsonInput-0","e":false,"i":"","n":"jsonNullJsonInput","t":"jsonNullJsonInput: JsonInput[JsonNull.type]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonNumberJsonInput-0","e":false,"i":"","n":"jsonNumberJsonInput","t":"jsonNumberJsonInput: JsonInput[JsonNumber]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonObjectJsonInput-0","e":false,"i":"","n":"jsonObjectJsonInput","t":"jsonObjectJsonInput: JsonInput[JsonObject]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonOutputConversion-bdd","e":false,"i":"","n":"jsonOutputConversion","t":"jsonOutputConversion[T](using output: JsonOutput[T]): Conversion[T, JsonValue]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonStringJsonInput-0","e":false,"i":"","n":"jsonStringJsonInput","t":"jsonStringJsonInput: JsonInput[JsonString]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonStructureFacadeConversion-0","e":false,"i":"","n":"jsonStructureFacadeConversion","t":"jsonStructureFacadeConversion: Conversion[JsonValue, JsonStructureFacade]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueJsonInput-0","e":false,"i":"","n":"jsonValueJsonInput","t":"jsonValueJsonInput: JsonInput[JsonValue]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#leftJsonOutput-fffff871","e":false,"i":"","n":"leftJsonOutput","t":"leftJsonOutput[T](using output: JsonOutput[T]): JsonOutput[Left[T, _]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#longJsonInput-0","e":false,"i":"","n":"longJsonInput","t":"longJsonInput: JsonInput[Long]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#longJsonOutput-0","e":false,"i":"","n":"longJsonOutput","t":"longJsonOutput: JsonOutput[Long]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#mapJsonInput-fffff2ea","e":false,"i":"","n":"mapJsonInput","t":"mapJsonInput[T, C <: ([T] =>> Map[String, T])](using input: JsonInput[T])(using factory: Factory[(String, T), C[T]]): JsonInput[C[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#mapJsonOutput-eb2","e":false,"i":"","n":"mapJsonOutput","t":"mapJsonOutput[T, C <: ([T] =>> Map[String, T])](using output: JsonOutput[T]): JsonOutput[C[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#noneJsonOutput-0","e":false,"i":"","n":"noneJsonOutput","t":"noneJsonOutput: JsonOutput[None.type]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#optionJsonInput-fffff5a7","e":false,"i":"","n":"optionJsonInput","t":"optionJsonInput[T](using input: JsonInput[T]): JsonInput[Option[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#optionJsonOutput-eb2","e":false,"i":"","n":"optionJsonOutput","t":"optionJsonOutput[T, C <: (Option)](using output: JsonOutput[T]): JsonOutput[C[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#rightJsonOutput-fffff871","e":false,"i":"","n":"rightJsonOutput","t":"rightJsonOutput[T](using output: JsonOutput[T]): JsonOutput[Right[_, T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#stringJsonInput-0","e":false,"i":"","n":"stringJsonInput","t":"stringJsonInput: JsonInput[String]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#stringJsonOutput-0","e":false,"i":"","n":"stringJsonOutput","t":"stringJsonOutput: JsonOutput[String]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#tryJsonInput-fffff5a7","e":false,"i":"","n":"tryJsonInput","t":"tryJsonInput[T](using input: JsonInput[T]): JsonInput[Try[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#tryJsonOutput-eb2","e":false,"i":"","n":"tryJsonOutput","t":"tryJsonOutput[T, C <: (Try)](using output: JsonOutput[T]): JsonOutput[C[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json/rpc.html#","e":false,"i":"","n":"grapple.json.rpc","t":"grapple.json.rpc","d":"","k":"package","x":""},
{"l":"grapple/json/rpc.html#defaultOnFailure-0","e":false,"i":"","n":"defaultOnFailure","t":"defaultOnFailure: PartialFunction[Throwable, JsonRpcError]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc.html#jsonRpcErrorToJsonValue-0","e":false,"i":"","n":"jsonRpcErrorToJsonValue","t":"jsonRpcErrorToJsonValue: JsonOutput[JsonRpcError]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc.html#jsonRpcIdentifierToJsonValue-0","e":false,"i":"","n":"jsonRpcIdentifierToJsonValue","t":"jsonRpcIdentifierToJsonValue: JsonOutput[JsonRpcIdentifier]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc.html#jsonRpcRequestToJsonValue-0","e":false,"i":"","n":"jsonRpcRequestToJsonValue","t":"jsonRpcRequestToJsonValue: JsonOutput[JsonRpcRequest]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc.html#jsonRpcResponseToJsonValue-0","e":false,"i":"","n":"jsonRpcResponseToJsonValue","t":"jsonRpcResponseToJsonValue: JsonOutput[JsonRpcResponse]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc.html#jsonValueToJsonRpcError-0","e":false,"i":"","n":"jsonValueToJsonRpcError","t":"jsonValueToJsonRpcError: JsonInput[JsonRpcError]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc.html#jsonValueToJsonRpcIdentifier-0","e":false,"i":"","n":"jsonValueToJsonRpcIdentifier","t":"jsonValueToJsonRpcIdentifier: JsonInput[JsonRpcIdentifier]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc.html#jsonValueToJsonRpcRequest-0","e":false,"i":"","n":"jsonValueToJsonRpcRequest","t":"jsonValueToJsonRpcRequest: JsonInput[JsonRpcRequest]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc.html#jsonValueToJsonRpcResponse-0","e":false,"i":"","n":"jsonValueToJsonRpcResponse","t":"jsonValueToJsonRpcResponse: JsonInput[JsonRpcResponse]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc/InternalError.html#","e":false,"i":"","n":"InternalError","t":"InternalError extends JsonRpcError","d":"grapple.json.rpc","k":"class","x":""},
{"l":"grapple/json/rpc/InternalError$.html#","e":false,"i":"","n":"InternalError","t":"InternalError","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/InternalError$.html#apply-cdb","e":false,"i":"","n":"apply","t":"apply(): InternalError","d":"grapple.json.rpc.InternalError","k":"def","x":""},
{"l":"grapple/json/rpc/InternalError$.html#apply-480","e":false,"i":"","n":"apply","t":"apply(data: String): InternalError","d":"grapple.json.rpc.InternalError","k":"def","x":""},
{"l":"grapple/json/rpc/InternalError$.html#apply-ffffff9d","e":false,"i":"","n":"apply","t":"apply(data: JsonValue): InternalError","d":"grapple.json.rpc.InternalError","k":"def","x":""},
{"l":"grapple/json/rpc/InternalError$.html#apply-a58","e":false,"i":"","n":"apply","t":"apply(data: Option[JsonValue]): InternalError","d":"grapple.json.rpc.InternalError","k":"def","x":""},
{"l":"grapple/json/rpc/InternalError$.html#unapply-fffff298","e":false,"i":"","n":"unapply","t":"unapply(error: InternalError): Option[(Int, String, Option[JsonValue])]","d":"grapple.json.rpc.InternalError","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidParams.html#","e":false,"i":"","n":"InvalidParams","t":"InvalidParams extends JsonRpcError","d":"grapple.json.rpc","k":"class","x":""},
{"l":"grapple/json/rpc/InvalidParams$.html#","e":false,"i":"","n":"InvalidParams","t":"InvalidParams","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/InvalidParams$.html#apply-fffff5ed","e":false,"i":"","n":"apply","t":"apply(): InvalidParams","d":"grapple.json.rpc.InvalidParams","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidParams$.html#apply-fffffd92","e":false,"i":"","n":"apply","t":"apply(data: String): InvalidParams","d":"grapple.json.rpc.InvalidParams","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidParams$.html#apply-fffff8af","e":false,"i":"","n":"apply","t":"apply(data: JsonValue): InvalidParams","d":"grapple.json.rpc.InvalidParams","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidParams$.html#apply-fffff36a","e":false,"i":"","n":"apply","t":"apply(data: Option[JsonValue]): InvalidParams","d":"grapple.json.rpc.InvalidParams","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidParams$.html#unapply-aa","e":false,"i":"","n":"unapply","t":"unapply(error: InvalidParams): Option[(Int, String, Option[JsonValue])]","d":"grapple.json.rpc.InvalidParams","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidRequest.html#","e":false,"i":"","n":"InvalidRequest","t":"InvalidRequest extends JsonRpcError","d":"grapple.json.rpc","k":"class","x":""},
{"l":"grapple/json/rpc/InvalidRequest$.html#","e":false,"i":"","n":"InvalidRequest","t":"InvalidRequest","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/InvalidRequest$.html#apply-308","e":false,"i":"","n":"apply","t":"apply(): InvalidRequest","d":"grapple.json.rpc.InvalidRequest","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidRequest$.html#apply-3","e":false,"i":"","n":"apply","t":"apply(data: String): InvalidRequest","d":"grapple.json.rpc.InvalidRequest","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidRequest$.html#apply-886","e":false,"i":"","n":"apply","t":"apply(data: JsonValue): InvalidRequest","d":"grapple.json.rpc.InvalidRequest","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidRequest$.html#apply-52b","e":false,"i":"","n":"apply","t":"apply(data: Option[JsonValue]): InvalidRequest","d":"grapple.json.rpc.InvalidRequest","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidRequest$.html#unapply-fffffd45","e":false,"i":"","n":"unapply","t":"unapply(error: InvalidRequest): Option[(Int, String, Option[JsonValue])]","d":"grapple.json.rpc.InvalidRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#","e":false,"i":"","n":"JsonRpcError","t":"JsonRpcError extends JsonException","d":"grapple.json.rpc","k":"class","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#code-0","e":false,"i":"","n":"code","t":"code: Int","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#data-0","e":false,"i":"","n":"data","t":"data: Option[JsonValue]","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#isInternalError-0","e":false,"i":"","n":"isInternalError","t":"isInternalError: Boolean","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#isInvalidParams-0","e":false,"i":"","n":"isInvalidParams","t":"isInvalidParams: Boolean","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#isInvalidRequest-0","e":false,"i":"","n":"isInvalidRequest","t":"isInvalidRequest: Boolean","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#isMethodNotFound-0","e":false,"i":"","n":"isMethodNotFound","t":"isMethodNotFound: Boolean","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#isParseError-0","e":false,"i":"","n":"isParseError","t":"isParseError: Boolean","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#isServerError-0","e":false,"i":"","n":"isServerError","t":"isServerError: Boolean","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#message-0","e":false,"i":"","n":"message","t":"message: String","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError$.html#","e":false,"i":"","n":"JsonRpcError","t":"JsonRpcError","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/JsonRpcError$.html#apply-68f","e":false,"i":"","n":"apply","t":"apply(code: Int, message: String): JsonRpcError","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError$.html#apply-fffff48d","e":false,"i":"","n":"apply","t":"apply(code: Int, message: String, data: JsonValue): JsonRpcError","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError$.html#apply-fffff772","e":false,"i":"","n":"apply","t":"apply(code: Int, message: String, data: Option[JsonValue]): JsonRpcError","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError$.html#unapply-858","e":false,"i":"","n":"unapply","t":"unapply(error: JsonRpcError): Option[(Int, String, Option[JsonValue])]","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html#","e":false,"i":"","n":"JsonRpcIdentifier","t":"JsonRpcIdentifier","d":"grapple.json.rpc","k":"trait","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html#isNull-0","e":false,"i":"","n":"isNull","t":"isNull: Boolean","d":"grapple.json.rpc.JsonRpcIdentifier","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html#isNumber-0","e":false,"i":"","n":"isNumber","t":"isNumber: Boolean","d":"grapple.json.rpc.JsonRpcIdentifier","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html#isString-0","e":false,"i":"","n":"isString","t":"isString: Boolean","d":"grapple.json.rpc.JsonRpcIdentifier","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html#number-0","e":false,"i":"","n":"number","t":"number: Long","d":"grapple.json.rpc.JsonRpcIdentifier","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html#string-0","e":false,"i":"","n":"string","t":"string: String","d":"grapple.json.rpc.JsonRpcIdentifier","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier$.html#","e":false,"i":"","n":"JsonRpcIdentifier","t":"JsonRpcIdentifier","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier$.html#apply-d1b","e":false,"i":"","n":"apply","t":"apply(id: String): JsonRpcIdentifier","d":"grapple.json.rpc.JsonRpcIdentifier","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier$.html#apply-53a","e":false,"i":"","n":"apply","t":"apply(id: Long): JsonRpcIdentifier","d":"grapple.json.rpc.JsonRpcIdentifier","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier$.html#nullified-0","e":false,"i":"","n":"nullified","t":"nullified: JsonRpcIdentifier","d":"grapple.json.rpc.JsonRpcIdentifier","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcMessage.html#","e":false,"i":"","n":"JsonRpcMessage","t":"JsonRpcMessage","d":"grapple.json.rpc","k":"trait","x":""},
{"l":"grapple/json/rpc/JsonRpcMessage.html#attributes-0","e":false,"i":"","n":"attributes","t":"attributes: Map[String, Any]","d":"grapple.json.rpc.JsonRpcMessage","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcMessage.html#get-229","e":false,"i":"","n":"get","t":"get[T](name: String): T","d":"grapple.json.rpc.JsonRpcMessage","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcMessage.html#getOption-fffff9d3","e":false,"i":"","n":"getOption","t":"getOption[T](name: String): Option[T]","d":"grapple.json.rpc.JsonRpcMessage","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcMessage.html#getOrElse-6cd","e":false,"i":"","n":"getOrElse","t":"getOrElse[T](name: String, default: => T): T","d":"grapple.json.rpc.JsonRpcMessage","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcMessage.html#id-0","e":false,"i":"","n":"id","t":"id: JsonRpcIdentifier","d":"grapple.json.rpc.JsonRpcMessage","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcMessage.html#version-0","e":false,"i":"","n":"version","t":"version: String","d":"grapple.json.rpc.JsonRpcMessage","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest.html#","e":false,"i":"","n":"JsonRpcRequest","t":"JsonRpcRequest extends JsonRpcMessage","d":"grapple.json.rpc","k":"trait","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest.html#isNotification-0","e":false,"i":"","n":"isNotification","t":"isNotification: Boolean","d":"grapple.json.rpc.JsonRpcRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest.html#method-0","e":false,"i":"","n":"method","t":"method: String","d":"grapple.json.rpc.JsonRpcRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest.html#params-0","e":false,"i":"","n":"params","t":"params: Option[JsonValue]","d":"grapple.json.rpc.JsonRpcRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest.html#put-fffff56a","e":false,"i":"","n":"put","t":"put(name: String, value: Any): JsonRpcRequest","d":"grapple.json.rpc.JsonRpcRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest.html#remove-75d","e":false,"i":"","n":"remove","t":"remove(name: String): JsonRpcRequest","d":"grapple.json.rpc.JsonRpcRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest.html#setAttributes-fffff23a","e":false,"i":"","n":"setAttributes","t":"setAttributes(attributes: Map[String, Any]): JsonRpcRequest","d":"grapple.json.rpc.JsonRpcRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest$.html#","e":false,"i":"","n":"JsonRpcRequest","t":"JsonRpcRequest","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest$.html#apply-ffffff7b","e":false,"i":"","n":"apply","t":"apply(version: String, method: String, params: Option[JsonValue]): JsonRpcRequest","d":"grapple.json.rpc.JsonRpcRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest$.html#apply-f05","e":false,"i":"","n":"apply","t":"apply(version: String, id: JsonRpcIdentifier, method: String, params: Option[JsonValue]): JsonRpcRequest","d":"grapple.json.rpc.JsonRpcRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#","e":false,"i":"","n":"JsonRpcRequestBuilder","t":"JsonRpcRequestBuilder","d":"grapple.json.rpc","k":"class","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#attributes-fffff001","e":false,"i":"","n":"attributes","t":"attributes(value: Map[String, Any]): this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#attributes-fffff2f6","e":false,"i":"","n":"attributes","t":"attributes(one: (String, Any), more: (String, Any)*): this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#id-fffff24f","e":false,"i":"","n":"id","t":"id(value: JsonRpcIdentifier): this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#id-fffffd7e","e":false,"i":"","n":"id","t":"id(value: String): this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#id-fffffe1d","e":false,"i":"","n":"id","t":"id(value: Long): this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#idNull-ad9","e":false,"i":"","n":"idNull","t":"idNull(): this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#idUndefined-ad9","e":false,"i":"","n":"idUndefined","t":"idUndefined(): this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#method-fffffd7e","e":false,"i":"","n":"method","t":"method(value: String): this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#params-fffffb56","e":false,"i":"","n":"params","t":"params(value: Option[JsonValue]): this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#params-b9b","e":false,"i":"","n":"params","t":"params(value: JsonValue): this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#toJsonRpcRequest-fffffa62","e":false,"i":"","n":"toJsonRpcRequest","t":"toJsonRpcRequest(): JsonRpcRequest","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#version-fffffd7e","e":false,"i":"","n":"version","t":"version(value: String): this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse.html#","e":false,"i":"","n":"JsonRpcResponse","t":"JsonRpcResponse extends JsonRpcMessage","d":"grapple.json.rpc","k":"trait","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse.html#error-0","e":false,"i":"","n":"error","t":"error: JsonRpcError","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse.html#isError-0","e":false,"i":"","n":"isError","t":"isError: Boolean","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse.html#isResult-0","e":false,"i":"","n":"isResult","t":"isResult: Boolean","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse.html#put-fffffcc6","e":false,"i":"","n":"put","t":"put(name: String, value: Any): JsonRpcResponse","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse.html#remove-fffff933","e":false,"i":"","n":"remove","t":"remove(name: String): JsonRpcResponse","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse.html#result-0","e":false,"i":"","n":"result","t":"result: JsonValue","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse.html#setAttributes-9f6","e":false,"i":"","n":"setAttributes","t":"setAttributes(attributes: Map[String, Any]): JsonRpcResponse","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse$.html#","e":false,"i":"","n":"JsonRpcResponse","t":"JsonRpcResponse","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse$.html#apply-fffffbeb","e":false,"i":"","n":"apply","t":"apply(version: String, id: JsonRpcIdentifier, result: JsonValue): JsonRpcResponse","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse$.html#apply-62e","e":false,"i":"","n":"apply","t":"apply(version: String, id: JsonRpcIdentifier, error: JsonRpcError): JsonRpcResponse","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#","e":false,"i":"","n":"JsonRpcResponseBuilder","t":"JsonRpcResponseBuilder","d":"grapple.json.rpc","k":"class","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#attributes-cc5","e":false,"i":"","n":"attributes","t":"attributes(value: Map[String, Any]): this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#attributes-fffff870","e":false,"i":"","n":"attributes","t":"attributes(one: (String, Any), more: (String, Any)*): this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#error-fffff1f2","e":false,"i":"","n":"error","t":"error(value: JsonRpcError): this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#error-fffff104","e":false,"i":"","n":"error","t":"error(code: Int, message: String, data: Option[JsonValue]): this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#error-85f","e":false,"i":"","n":"error","t":"error(code: Int, message: String, data: JsonValue): this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#id-fffff437","e":false,"i":"","n":"id","t":"id(value: JsonRpcIdentifier): this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#id-ee8","e":false,"i":"","n":"id","t":"id(value: String): this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#id-fffff229","e":false,"i":"","n":"id","t":"id(value: Long): this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#idNull-ced","e":false,"i":"","n":"idNull","t":"idNull(): this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#result-fffff46b","e":false,"i":"","n":"result","t":"result(value: JsonValue): this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#resultOrError-3fa","e":false,"i":"","n":"resultOrError","t":"resultOrError(value: JsonValue | JsonRpcError): this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#toJsonRpcResponse-fffff6ce","e":false,"i":"","n":"toJsonRpcResponse","t":"toJsonRpcResponse(): JsonRpcResponse","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#tryResult-ac","e":false,"i":"","n":"tryResult","t":"tryResult(value: => JsonValue)(using onFailure: PartialFunction[Throwable, JsonRpcError]): this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#version-ee8","e":false,"i":"","n":"version","t":"version(value: String): this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/MethodNotFound.html#","e":false,"i":"","n":"MethodNotFound","t":"MethodNotFound extends JsonRpcError","d":"grapple.json.rpc","k":"class","x":""},
{"l":"grapple/json/rpc/MethodNotFound$.html#","e":false,"i":"","n":"MethodNotFound","t":"MethodNotFound","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/MethodNotFound$.html#apply-fffffae0","e":false,"i":"","n":"apply","t":"apply(): MethodNotFound","d":"grapple.json.rpc.MethodNotFound","k":"def","x":""},
{"l":"grapple/json/rpc/MethodNotFound$.html#apply-fffff7db","e":false,"i":"","n":"apply","t":"apply(data: String): MethodNotFound","d":"grapple.json.rpc.MethodNotFound","k":"def","x":""},
{"l":"grapple/json/rpc/MethodNotFound$.html#apply-fffff05e","e":false,"i":"","n":"apply","t":"apply(data: JsonValue): MethodNotFound","d":"grapple.json.rpc.MethodNotFound","k":"def","x":""},
{"l":"grapple/json/rpc/MethodNotFound$.html#apply-fffffd03","e":false,"i":"","n":"apply","t":"apply(data: Option[JsonValue]): MethodNotFound","d":"grapple.json.rpc.MethodNotFound","k":"def","x":""},
{"l":"grapple/json/rpc/MethodNotFound$.html#unapply-11d","e":false,"i":"","n":"unapply","t":"unapply(error: MethodNotFound): Option[(Int, String, Option[JsonValue])]","d":"grapple.json.rpc.MethodNotFound","k":"def","x":""},
{"l":"grapple/json/rpc/ParseError.html#","e":false,"i":"","n":"ParseError","t":"ParseError extends JsonRpcError","d":"grapple.json.rpc","k":"class","x":""},
{"l":"grapple/json/rpc/ParseError$.html#","e":false,"i":"","n":"ParseError","t":"ParseError","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/ParseError$.html#apply-585","e":false,"i":"","n":"apply","t":"apply(): ParseError","d":"grapple.json.rpc.ParseError","k":"def","x":""},
{"l":"grapple/json/rpc/ParseError$.html#apply-fffff800","e":false,"i":"","n":"apply","t":"apply(data: String): ParseError","d":"grapple.json.rpc.ParseError","k":"def","x":""},
{"l":"grapple/json/rpc/ParseError$.html#apply-a03","e":false,"i":"","n":"apply","t":"apply(data: JsonValue): ParseError","d":"grapple.json.rpc.ParseError","k":"def","x":""},
{"l":"grapple/json/rpc/ParseError$.html#apply-128","e":false,"i":"","n":"apply","t":"apply(data: Option[JsonValue]): ParseError","d":"grapple.json.rpc.ParseError","k":"def","x":""},
{"l":"grapple/json/rpc/ParseError$.html#unapply-c42","e":false,"i":"","n":"unapply","t":"unapply(error: ParseError): Option[(Int, String, Option[JsonValue])]","d":"grapple.json.rpc.ParseError","k":"def","x":""},
{"l":"grapple/json/Json$.html#","e":false,"i":"","n":"Json","t":"Json","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/Json$.html#arr-b15","e":false,"i":"","n":"arr","t":"arr(values: JsonValue*): JsonArray","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#obj-fffff203","e":false,"i":"","n":"obj","t":"obj(fields: (String, JsonValue)*): JsonObject","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#parse-fe9","e":false,"i":"","n":"parse","t":"parse(input: String): JsonStructure","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#parse-fffffb76","e":false,"i":"","n":"parse","t":"parse(input: Array[Byte]): JsonStructure","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#parse-fffff6d6","e":false,"i":"","n":"parse","t":"parse(input: Array[Byte], offset: Int, length: Int): JsonStructure","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#parse-fffff6e3","e":false,"i":"","n":"parse","t":"parse(input: Reader): JsonStructure","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#parse-fffff492","e":false,"i":"","n":"parse","t":"parse(input: InputStream): JsonStructure","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#parse-55c","e":false,"i":"","n":"parse","t":"parse(input: File): JsonStructure","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#parse-fffff9d5","e":false,"i":"","n":"parse","t":"parse(input: Path): JsonStructure","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#toBytes-fffff774","e":false,"i":"","n":"toBytes","t":"toBytes(value: JsonValue): Array[Byte]","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#toJson-f4e","e":false,"i":"","n":"toJson","t":"toJson[T](value: T)(using output: JsonOutput[T]): JsonValue","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#toPrettyPrint-fffff4a7","e":false,"i":"","n":"toPrettyPrint","t":"toPrettyPrint(value: JsonValue): String","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#toPrettyPrint-fffffd0c","e":false,"i":"","n":"toPrettyPrint","t":"toPrettyPrint(value: JsonValue, indent: String): String","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/JsonAdapter.html#","e":false,"i":"","n":"JsonAdapter","t":"JsonAdapter[T] extends JsonInput[T], JsonOutput[T]","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonArray.html#","e":false,"i":"","n":"JsonArray","t":"JsonArray extends JsonStructure","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonArray.html#++-ad4","e":false,"i":"","n":"++","t":"++(suffix: JsonArray): JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#+:-fffff7ec","e":false,"i":"","n":"+:","t":"+:(value: JsonValue): JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#:+-fffff7ec","e":false,"i":"","n":":+","t":":+(value: JsonValue): JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#apply-a29","e":false,"i":"","n":"apply","t":"apply(index: Int): JsonValue","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getArray-b11","e":false,"i":"","n":"getArray","t":"getArray(index: Int): JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getBigDecimal-788","e":false,"i":"","n":"getBigDecimal","t":"getBigDecimal(index: Int): BigDecimal","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getBigInt-fa6","e":false,"i":"","n":"getBigInt","t":"getBigInt(index: Int): BigInt","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getBoolean-ffffff99","e":false,"i":"","n":"getBoolean","t":"getBoolean(index: Int): Boolean","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getDouble-640","e":false,"i":"","n":"getDouble","t":"getDouble(index: Int): Double","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getFloat-fffffe0d","e":false,"i":"","n":"getFloat","t":"getFloat(index: Int): Float","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getInt-fffffbe0","e":false,"i":"","n":"getInt","t":"getInt(index: Int): Int","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getLong-fffff0ab","e":false,"i":"","n":"getLong","t":"getLong(index: Int): Long","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getObject-fffff187","e":false,"i":"","n":"getObject","t":"getObject(index: Int): JsonObject","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getString-78c","e":false,"i":"","n":"getString","t":"getString(index: Int): String","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#isNull-ffffff99","e":false,"i":"","n":"isNull","t":"isNull(index: Int): Boolean","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#read-fffff1c4","e":false,"i":"","n":"read","t":"read[T](index: Int)(using JsonInput[T]): T","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#readOption-eee","e":false,"i":"","n":"readOption","t":"readOption[T](index: Int)(using JsonInput[T]): Option[T]","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#readOrElse-fffff068","e":false,"i":"","n":"readOrElse","t":"readOrElse[T](index: Int, default: => T)(using JsonInput[T]): T","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#removed-b11","e":false,"i":"","n":"removed","t":"removed(index: Int): JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#updated-fffff893","e":false,"i":"","n":"updated","t":"updated(index: Int, value: JsonValue): JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#values-0","e":false,"i":"","n":"values","t":"values: Seq[JsonValue]","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray$.html#","e":false,"i":"","n":"JsonArray","t":"JsonArray","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonArray$.html#apply-fffff32a","e":false,"i":"","n":"apply","t":"apply(): JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray$.html#apply-b15","e":false,"i":"","n":"apply","t":"apply(values: Seq[JsonValue]): JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray$.html#unapply-a67","e":false,"i":"","n":"unapply","t":"unapply(json: JsonArray): Option[Seq[JsonValue]]","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#","e":false,"i":"","n":"JsonArrayBuilder","t":"JsonArrayBuilder","d":"grapple.json","k":"class","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-cc","e":false,"i":"","n":"add","t":"add(value: String): this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-5b1","e":false,"i":"","n":"add","t":"add(value: Boolean): this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-fffff74a","e":false,"i":"","n":"add","t":"add(value: Int): this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-14d","e":false,"i":"","n":"add","t":"add(value: Long): this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-fffffdfd","e":false,"i":"","n":"add","t":"add(value: Float): this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-a18","e":false,"i":"","n":"add","t":"add(value: Double): this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-844","e":false,"i":"","n":"add","t":"add(value: BigInt): this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-ffffff22","e":false,"i":"","n":"add","t":"add(value: BigDecimal): this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-fffffe0f","e":false,"i":"","n":"add","t":"add(value: JsonValue): this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#addNull-111","e":false,"i":"","n":"addNull","t":"addNull(): this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#toJsonArray-fffff32a","e":false,"i":"","n":"toJsonArray","t":"toJsonArray(): JsonArray","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayError.html#","e":false,"i":"","n":"JsonArrayError","t":"JsonArrayError(index: Int, cause: Exception) extends JsonException","d":"grapple.json","k":"class","x":""},
{"l":"grapple/json/JsonBoolean.html#","e":false,"i":"","n":"JsonBoolean","t":"JsonBoolean extends JsonValue","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonBoolean.html#value-0","e":false,"i":"","n":"value","t":"value: Boolean","d":"grapple.json.JsonBoolean","k":"def","x":""},
{"l":"grapple/json/JsonBoolean$.html#","e":false,"i":"","n":"JsonBoolean","t":"JsonBoolean","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonBoolean$.html#apply-fffff419","e":false,"i":"","n":"apply","t":"apply(value: Boolean): JsonBoolean","d":"grapple.json.JsonBoolean","k":"def","x":""},
{"l":"grapple/json/JsonBoolean$.html#unapply-fffff576","e":false,"i":"","n":"unapply","t":"unapply(json: JsonBoolean): Option[Boolean]","d":"grapple.json.JsonBoolean","k":"def","x":""},
{"l":"grapple/json/JsonBoolean$$False$.html#","e":false,"i":"","n":"False","t":"False extends JsonBoolean","d":"grapple.json.JsonBoolean","k":"object","x":""},
{"l":"grapple/json/JsonBoolean$$False$.html#toString-0","e":false,"i":"","n":"toString","t":"toString: String","d":"grapple.json.JsonBoolean.False","k":"val","x":""},
{"l":"grapple/json/JsonBoolean$$False$.html#value-0","e":false,"i":"","n":"value","t":"value: Boolean","d":"grapple.json.JsonBoolean.False","k":"val","x":""},
{"l":"grapple/json/JsonBoolean$$True$.html#","e":false,"i":"","n":"True","t":"True extends JsonBoolean","d":"grapple.json.JsonBoolean","k":"object","x":""},
{"l":"grapple/json/JsonBoolean$$True$.html#toString-0","e":false,"i":"","n":"toString","t":"toString: String","d":"grapple.json.JsonBoolean.True","k":"val","x":""},
{"l":"grapple/json/JsonBoolean$$True$.html#value-0","e":false,"i":"","n":"value","t":"value: Boolean","d":"grapple.json.JsonBoolean.True","k":"val","x":""},
{"l":"grapple/json/JsonException.html#","e":false,"i":"","n":"JsonException","t":"JsonException(message: String, cause: Throwable) extends RuntimeException","d":"grapple.json","k":"class","x":""},
{"l":"grapple/json/JsonException.html#<init>-a0","e":false,"i":"","n":"this","t":"this()","d":"grapple.json.JsonException","k":"def","x":""},
{"l":"grapple/json/JsonException.html#<init>-fffff2c5","e":false,"i":"","n":"this","t":"this(message: String)","d":"grapple.json.JsonException","k":"def","x":""},
{"l":"grapple/json/JsonException.html#<init>-40c","e":false,"i":"","n":"this","t":"this(cause: Throwable)","d":"grapple.json.JsonException","k":"def","x":""},
{"l":"grapple/json/JsonExpectationError.html#","e":false,"i":"","n":"JsonExpectationError","t":"JsonExpectationError(expected: Class[_], actual: Class[_]) extends JsonException","d":"grapple.json","k":"class","x":""},
{"l":"grapple/json/JsonGenerator.html#","e":false,"i":"","n":"JsonGenerator","t":"JsonGenerator extends AutoCloseable","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonGenerator.html#close-94c","e":false,"i":"","n":"close","t":"close(): Unit","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#flush-94c","e":false,"i":"","n":"flush","t":"flush(): Unit","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-56e","e":false,"i":"","n":"write","t":"write(key: String, value: String): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-c7f","e":false,"i":"","n":"write","t":"write(key: String, value: Boolean): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-ffffff06","e":false,"i":"","n":"write","t":"write(key: String, value: Int): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffffc4d","e":false,"i":"","n":"write","t":"write(key: String, value: Long): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffffa73","e":false,"i":"","n":"write","t":"write(key: String, value: Float): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffffa22","e":false,"i":"","n":"write","t":"write(key: String, value: Double): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffff54c","e":false,"i":"","n":"write","t":"write(key: String, value: BigInt): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffff5ae","e":false,"i":"","n":"write","t":"write(key: String, value: BigDecimal): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffff74b","e":false,"i":"","n":"write","t":"write(key: String, value: JsonValue): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-d49","e":false,"i":"","n":"write","t":"write(value: String): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffffa84","e":false,"i":"","n":"write","t":"write(value: Boolean): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-78b","e":false,"i":"","n":"write","t":"write(value: Int): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-468","e":false,"i":"","n":"write","t":"write(value: Long): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffff5b8","e":false,"i":"","n":"write","t":"write(value: Float): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-77d","e":false,"i":"","n":"write","t":"write(value: Double): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-8d1","e":false,"i":"","n":"write","t":"write(value: BigInt): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffffeb3","e":false,"i":"","n":"write","t":"write(value: BigDecimal): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-ee6","e":false,"i":"","n":"write","t":"write(value: JsonValue): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#writeEnd-b24","e":false,"i":"","n":"writeEnd","t":"writeEnd(): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#writeNull-d49","e":false,"i":"","n":"writeNull","t":"writeNull(key: String): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#writeNull-b24","e":false,"i":"","n":"writeNull","t":"writeNull(): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#writeStartArray-b24","e":false,"i":"","n":"writeStartArray","t":"writeStartArray(): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#writeStartArray-d49","e":false,"i":"","n":"writeStartArray","t":"writeStartArray(key: String): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#writeStartObject-b24","e":false,"i":"","n":"writeStartObject","t":"writeStartObject(): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#writeStartObject-d49","e":false,"i":"","n":"writeStartObject","t":"writeStartObject(key: String): this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator$.html#","e":false,"i":"","n":"JsonGenerator","t":"JsonGenerator","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonGenerator$.html#apply-fffff818","e":false,"i":"","n":"apply","t":"apply(output: Writer, indent: String): JsonGenerator","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator$.html#apply-3f3","e":false,"i":"","n":"apply","t":"apply(output: Writer): JsonGenerator","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator$.html#apply-506","e":false,"i":"","n":"apply","t":"apply(output: OutputStream, indent: String): JsonGenerator","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator$.html#apply-fffffce1","e":false,"i":"","n":"apply","t":"apply(output: OutputStream): JsonGenerator","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator$.html#apply-fffff4e1","e":false,"i":"","n":"apply","t":"apply(output: File, indent: String): JsonGenerator","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator$.html#apply-2bc","e":false,"i":"","n":"apply","t":"apply(output: File): JsonGenerator","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator$.html#apply-75a","e":false,"i":"","n":"apply","t":"apply(output: Path, indent: String): JsonGenerator","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator$.html#apply-fffff735","e":false,"i":"","n":"apply","t":"apply(output: Path): JsonGenerator","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGeneratorError.html#","e":false,"i":"","n":"JsonGeneratorError","t":"JsonGeneratorError(message: String) extends JsonException","d":"grapple.json","k":"class","x":""},
{"l":"grapple/json/JsonInput.html#","e":false,"i":"","n":"JsonInput","t":"JsonInput[T]","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonInput.html#read-fffff7d5","e":false,"i":"","n":"read","t":"read(value: JsonValue): T","d":"grapple.json.JsonInput","k":"def","x":""},
{"l":"grapple/json/JsonNull$.html#","e":false,"i":"","n":"JsonNull","t":"JsonNull extends JsonValue","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonNull$.html#toString-0","e":false,"i":"","n":"toString","t":"toString: String","d":"grapple.json.JsonNull","k":"val","x":""},
{"l":"grapple/json/JsonNumber.html#","e":false,"i":"","n":"JsonNumber","t":"JsonNumber extends JsonValue","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonNumber.html#toBigDecimal-0","e":false,"i":"","n":"toBigDecimal","t":"toBigDecimal: BigDecimal","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber.html#toBigInt-0","e":false,"i":"","n":"toBigInt","t":"toBigInt: BigInt","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber.html#toDouble-0","e":false,"i":"","n":"toDouble","t":"toDouble: Double","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber.html#toFloat-0","e":false,"i":"","n":"toFloat","t":"toFloat: Float","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber.html#toInt-0","e":false,"i":"","n":"toInt","t":"toInt: Int","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber.html#toLong-0","e":false,"i":"","n":"toLong","t":"toLong: Long","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber$.html#","e":false,"i":"","n":"JsonNumber","t":"JsonNumber","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonNumber$.html#apply-c93","e":false,"i":"","n":"apply","t":"apply(value: String): JsonNumber","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber$.html#apply-fffff991","e":false,"i":"","n":"apply","t":"apply(value: Int): JsonNumber","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber$.html#apply-1d4","e":false,"i":"","n":"apply","t":"apply(value: Long): JsonNumber","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber$.html#apply-edf","e":false,"i":"","n":"apply","t":"apply(value: Double): JsonNumber","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber$.html#apply-e0b","e":false,"i":"","n":"apply","t":"apply(value: BigInt): JsonNumber","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber$.html#apply-fffff369","e":false,"i":"","n":"apply","t":"apply(value: BigDecimal): JsonNumber","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber$.html#unapply-fffff6d5","e":false,"i":"","n":"unapply","t":"unapply(json: JsonNumber): Option[BigDecimal]","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#","e":false,"i":"","n":"JsonObject","t":"JsonObject extends JsonStructure","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonObject.html#++-fffff040","e":false,"i":"","n":"++","t":"++(other: JsonObject): JsonObject","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#apply-fffffee7","e":false,"i":"","n":"apply","t":"apply(key: String): JsonValue","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#fields-0","e":false,"i":"","n":"fields","t":"fields: Map[String, JsonValue]","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#get-fffffd22","e":false,"i":"","n":"get","t":"get(key: String): Option[JsonValue]","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getArray-ffffffcf","e":false,"i":"","n":"getArray","t":"getArray(key: String): JsonArray","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getBigDecimal-fffff30a","e":false,"i":"","n":"getBigDecimal","t":"getBigDecimal(key: String): BigDecimal","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getBigInt-fffffc28","e":false,"i":"","n":"getBigInt","t":"getBigInt(key: String): BigInt","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getBoolean-fffffd1b","e":false,"i":"","n":"getBoolean","t":"getBoolean(key: String): Boolean","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getDouble-fffff07e","e":false,"i":"","n":"getDouble","t":"getDouble(key: String): Double","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getFloat-fffff40f","e":false,"i":"","n":"getFloat","t":"getFloat(key: String): Float","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getInt-a62","e":false,"i":"","n":"getInt","t":"getInt(key: String): Int","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getLong-269","e":false,"i":"","n":"getLong","t":"getLong(key: String): Long","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getObject-489","e":false,"i":"","n":"getObject","t":"getObject(key: String): JsonObject","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getOrElse-f8d","e":false,"i":"","n":"getOrElse","t":"getOrElse(key: String, default: => JsonValue): JsonValue","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getString-fffff2ca","e":false,"i":"","n":"getString","t":"getString(key: String): String","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#isNull-fffffd1b","e":false,"i":"","n":"isNull","t":"isNull(key: String): Boolean","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#keys-0","e":false,"i":"","n":"keys","t":"keys: Set[String]","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#read-fffff044","e":false,"i":"","n":"read","t":"read[T](key: String)(using JsonInput[T]): T","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#readOption-fffffd6e","e":false,"i":"","n":"readOption","t":"readOption[T](key: String)(using JsonInput[T]): Option[T]","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#readOrElse-1e8","e":false,"i":"","n":"readOrElse","t":"readOrElse[T](key: String, default: => T)(using JsonInput[T]): T","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#removed-489","e":false,"i":"","n":"removed","t":"removed(key: String): JsonObject","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#updated-fffff9c7","e":false,"i":"","n":"updated","t":"updated(key: String, value: JsonValue): JsonObject","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject$.html#","e":false,"i":"","n":"JsonObject","t":"JsonObject","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonObject$.html#apply-fffffc8e","e":false,"i":"","n":"apply","t":"apply(): JsonObject","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject$.html#apply-fffffc66","e":false,"i":"","n":"apply","t":"apply(fields: Map[String, JsonValue]): JsonObject","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject$.html#apply-fffff203","e":false,"i":"","n":"apply","t":"apply(fields: Seq[(String, JsonValue)]): JsonObject","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: JsonObject","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject$.html#unapply-dcb","e":false,"i":"","n":"unapply","t":"unapply(json: JsonObject): Option[Map[String, JsonValue]]","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#","e":false,"i":"","n":"JsonObjectBuilder","t":"JsonObjectBuilder","d":"grapple.json","k":"class","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-477","e":false,"i":"","n":"add","t":"add(key: String, value: String): this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-b08","e":false,"i":"","n":"add","t":"add(key: String, value: Boolean): this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-20f","e":false,"i":"","n":"add","t":"add(key: String, value: Int): this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-3d6","e":false,"i":"","n":"add","t":"add(key: String, value: Long): this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-fffffefc","e":false,"i":"","n":"add","t":"add(key: String, value: Float): this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-ffffff2b","e":false,"i":"","n":"add","t":"add(key: String, value: Double): this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-fffff555","e":false,"i":"","n":"add","t":"add(key: String, value: BigInt): this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-4b7","e":false,"i":"","n":"add","t":"add(key: String, value: BigDecimal): this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-fd4","e":false,"i":"","n":"add","t":"add(key: String, value: JsonValue): this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#addNull-fffff6d2","e":false,"i":"","n":"addNull","t":"addNull(key: String): this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#toJsonObject-fffffc8e","e":false,"i":"","n":"toJsonObject","t":"toJsonObject(): JsonObject","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectError.html#","e":false,"i":"","n":"JsonObjectError","t":"JsonObjectError(key: String, cause: Exception) extends JsonException","d":"grapple.json","k":"class","x":""},
{"l":"grapple/json/JsonOutput.html#","e":false,"i":"","n":"JsonOutput","t":"JsonOutput[T]","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonOutput.html#write-fffffb95","e":false,"i":"","n":"write","t":"write(value: T): JsonValue","d":"grapple.json.JsonOutput","k":"def","x":""},
{"l":"grapple/json/JsonParser.html#","e":false,"i":"","n":"JsonParser","t":"JsonParser extends Iterator[Event], AutoCloseable","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonParser.html#close-94c","e":false,"i":"","n":"close","t":"close(): Unit","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser.html#getArray-fffff32a","e":false,"i":"","n":"getArray","t":"getArray(): JsonArray","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser.html#getObject-fffffc8e","e":false,"i":"","n":"getObject","t":"getObject(): JsonObject","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser.html#hasNext-0","e":false,"i":"","n":"hasNext","t":"hasNext: Boolean","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser.html#next-702","e":false,"i":"","n":"next","t":"next(): Event","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser$.html#","e":false,"i":"","n":"JsonParser","t":"JsonParser","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonParser$.html#apply-8af","e":false,"i":"","n":"apply","t":"apply(input: Reader): JsonParser","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser$.html#apply-d69","e":false,"i":"","n":"apply","t":"apply(input: String): JsonParser","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser$.html#apply-fffff4fc","e":false,"i":"","n":"apply","t":"apply(input: Array[Byte]): JsonParser","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser$.html#apply-fffff59c","e":false,"i":"","n":"apply","t":"apply(input: Array[Byte], offset: Int, length: Int): JsonParser","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser$.html#apply-160","e":false,"i":"","n":"apply","t":"apply(input: InputStream): JsonParser","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser$.html#apply-4d6","e":false,"i":"","n":"apply","t":"apply(input: File): JsonParser","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser$.html#apply-fffffafd","e":false,"i":"","n":"apply","t":"apply(input: Path): JsonParser","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser$$Event.html#","e":false,"i":"","n":"Event","t":"Event","d":"grapple.json.JsonParser","k":"enum","x":""},
{"l":"grapple/json/JsonParser$$Event$$Key.html#","e":false,"i":"","n":"Key","t":"Key(get: String) extends Event","d":"grapple.json.JsonParser.Event","k":"class","x":""},
{"l":"grapple/json/JsonParser$$Event$$Value.html#","e":false,"i":"","n":"Value","t":"Value(get: JsonValue) extends Event","d":"grapple.json.JsonParser.Event","k":"class","x":""},
{"l":"grapple/json/JsonParser$$Event.html#StartObject-0","e":false,"i":"","n":"StartObject","t":"StartObject extends Event","d":"grapple.json.JsonParser.Event","k":"val","x":""},
{"l":"grapple/json/JsonParser$$Event.html#StartArray-0","e":false,"i":"","n":"StartArray","t":"StartArray extends Event","d":"grapple.json.JsonParser.Event","k":"val","x":""},
{"l":"grapple/json/JsonParser$$Event.html#EndObject-0","e":false,"i":"","n":"EndObject","t":"EndObject extends Event","d":"grapple.json.JsonParser.Event","k":"val","x":""},
{"l":"grapple/json/JsonParser$$Event.html#EndArray-0","e":false,"i":"","n":"EndArray","t":"EndArray extends Event","d":"grapple.json.JsonParser.Event","k":"val","x":""},
{"l":"grapple/json/JsonParser$$Event$$Key.html#","e":false,"i":"","n":"Key","t":"Key(get: String) extends Event","d":"grapple.json.JsonParser.Event","k":"class","x":""},
{"l":"grapple/json/JsonParser$$Event$$Value.html#","e":false,"i":"","n":"Value","t":"Value(get: JsonValue) extends Event","d":"grapple.json.JsonParser.Event","k":"class","x":""},
{"l":"grapple/json/JsonParserError.html#","e":false,"i":"","n":"JsonParserError","t":"JsonParserError(message: String, offset: Long) extends JsonException","d":"grapple.json","k":"class","x":""},
{"l":"grapple/json/JsonReader.html#","e":false,"i":"","n":"JsonReader","t":"JsonReader extends AutoCloseable","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonReader.html#close-94c","e":false,"i":"","n":"close","t":"close(): Unit","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonReader.html#read-dc4","e":false,"i":"","n":"read","t":"read(): JsonStructure","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonReader$.html#","e":false,"i":"","n":"JsonReader","t":"JsonReader","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonReader$.html#apply-553","e":false,"i":"","n":"apply","t":"apply(input: Reader): JsonReader","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonReader$.html#apply-a0d","e":false,"i":"","n":"apply","t":"apply(input: String): JsonReader","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonReader$.html#apply-fffff1a0","e":false,"i":"","n":"apply","t":"apply(input: Array[Byte]): JsonReader","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonReader$.html#apply-fffff240","e":false,"i":"","n":"apply","t":"apply(input: Array[Byte], offset: Int, length: Int): JsonReader","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonReader$.html#apply-e04","e":false,"i":"","n":"apply","t":"apply(input: InputStream): JsonReader","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonReader$.html#apply-17a","e":false,"i":"","n":"apply","t":"apply(input: File): JsonReader","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonReader$.html#apply-fffff7a1","e":false,"i":"","n":"apply","t":"apply(input: Path): JsonReader","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonString.html#","e":false,"i":"","n":"JsonString","t":"JsonString extends JsonValue","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonString.html#value-0","e":false,"i":"","n":"value","t":"value: String","d":"grapple.json.JsonString","k":"def","x":""},
{"l":"grapple/json/JsonString$.html#","e":false,"i":"","n":"JsonString","t":"JsonString","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonString$.html#apply-15b","e":false,"i":"","n":"apply","t":"apply(value: String): JsonString","d":"grapple.json.JsonString","k":"def","x":""},
{"l":"grapple/json/JsonString$.html#unapply-ffffff9d","e":false,"i":"","n":"unapply","t":"unapply(json: JsonString): Option[String]","d":"grapple.json.JsonString","k":"def","x":""},
{"l":"grapple/json/JsonStructure.html#","e":false,"i":"","n":"JsonStructure","t":"JsonStructure extends JsonValue","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonStructure.html#isEmpty-0","e":false,"i":"","n":"isEmpty","t":"isEmpty: Boolean","d":"grapple.json.JsonStructure","k":"def","x":""},
{"l":"grapple/json/JsonStructure.html#nonEmpty-0","e":false,"i":"","n":"nonEmpty","t":"nonEmpty: Boolean","d":"grapple.json.JsonStructure","k":"def","x":""},
{"l":"grapple/json/JsonStructure.html#size-0","e":false,"i":"","n":"size","t":"size: Int","d":"grapple.json.JsonStructure","k":"def","x":""},
{"l":"grapple/json/JsonStructureFacade.html#","e":false,"i":"","n":"JsonStructureFacade","t":"JsonStructureFacade extends JsonObject, JsonArray","d":"grapple.json","k":"class","x":""},
{"l":"grapple/json/JsonStructureFacade.html#++-fffff040","e":false,"i":"","n":"++","t":"++(other: JsonObject): JsonObject","d":"grapple.json.JsonStructureFacade","k":"def","x":""},
{"l":"grapple/json/JsonStructureFacade.html#++-ad4","e":false,"i":"","n":"++","t":"++(suffix: JsonArray): JsonArray","d":"grapple.json.JsonStructureFacade","k":"def","x":""},
{"l":"grapple/json/JsonStructureFacade.html#+:-fffff7ec","e":false,"i":"","n":"+:","t":"+:(value: JsonValue): JsonArray","d":"grapple.json.JsonStructureFacade","k":"def","x":""},
{"l":"grapple/json/JsonStructureFacade.html#:+-fffff7ec","e":false,"i":"","n":":+","t":":+(value: JsonValue): JsonArray","d":"grapple.json.JsonStructureFacade","k":"def","x":""},
{"l":"grapple/json/JsonStructureFacade.html#apply-fffffee7","e":false,"i":"","n":"apply","t":"apply(key: String): JsonValue","d":"grapple.json.JsonStructureFacade","k":"def","x":""},
{"l":"grapple/json/JsonStructureFacade.html#apply-a29","e":false,"i":"","n":"apply","t":"apply(index: Int): JsonValue","d":"grapple.json.JsonStructureFacade","k":"def","x":""},
{"l":"grapple/json/JsonStructureFacade.html#fields-0","e":false,"i":"","n":"fields","t":"fields: Map[String, JsonValue]","d":"grapple.json.JsonStructureFacade","k":"def","x":""},
{"l":"grapple/json/JsonStructureFacade.html#get-fffffd22","e":false,"i":"","n":"get","t":"get(key: String): Option[JsonValue]","d":"grapple.json.JsonStructureFacade","k":"def","x":""},
{"l":"grapple/json/JsonStructureFacade.html#keys-0","e":false,"i":"","n":"keys","t":"keys: Set[String]","d":"grapple.json.JsonStructureFacade","k":"def","x":""},
{"l":"grapple/json/JsonStructureFacade.html#removed-489","e":false,"i":"","n":"removed","t":"removed(key: String): JsonObject","d":"grapple.json.JsonStructureFacade","k":"def","x":""},
{"l":"grapple/json/JsonStructureFacade.html#removed-b11","e":false,"i":"","n":"removed","t":"removed(index: Int): JsonArray","d":"grapple.json.JsonStructureFacade","k":"def","x":""},
{"l":"grapple/json/JsonStructureFacade.html#size-0","e":false,"i":"","n":"size","t":"size: Int","d":"grapple.json.JsonStructureFacade","k":"def","x":""},
{"l":"grapple/json/JsonStructureFacade.html#toString-0","e":false,"i":"","n":"toString","t":"toString: String","d":"grapple.json.JsonStructureFacade","k":"val","x":""},
{"l":"grapple/json/JsonStructureFacade.html#unwrap-0","e":false,"i":"","n":"unwrap","t":"unwrap: JsonStructure","d":"grapple.json.JsonStructureFacade","k":"def","x":""},
{"l":"grapple/json/JsonStructureFacade.html#updated-fffff9c7","e":false,"i":"","n":"updated","t":"updated(key: String, value: JsonValue): JsonObject","d":"grapple.json.JsonStructureFacade","k":"def","x":""},
{"l":"grapple/json/JsonStructureFacade.html#updated-fffff893","e":false,"i":"","n":"updated","t":"updated(index: Int, value: JsonValue): JsonArray","d":"grapple.json.JsonStructureFacade","k":"def","x":""},
{"l":"grapple/json/JsonStructureFacade.html#values-0","e":false,"i":"","n":"values","t":"values: Seq[JsonValue]","d":"grapple.json.JsonStructureFacade","k":"def","x":""},
{"l":"grapple/json/JsonValue.html#","e":false,"i":"","n":"JsonValue","t":"JsonValue","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonValue.html#as-f9f","e":false,"i":"","n":"as","t":"as[T](using input: JsonInput[T]): T","d":"grapple.json.JsonValue","k":"def","x":""},
{"l":"grapple/json/JsonWriter.html#","e":false,"i":"","n":"JsonWriter","t":"JsonWriter extends AutoCloseable","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonWriter.html#close-94c","e":false,"i":"","n":"close","t":"close(): Unit","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter.html#write-37e","e":false,"i":"","n":"write","t":"write(value: JsonStructure): this.type","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter$.html#","e":false,"i":"","n":"JsonWriter","t":"JsonWriter","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonWriter$.html#apply-fffff54e","e":false,"i":"","n":"apply","t":"apply(output: Writer, indent: String): JsonWriter","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter$.html#apply-f53","e":false,"i":"","n":"apply","t":"apply(output: Writer): JsonWriter","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter$.html#apply-ffffff20","e":false,"i":"","n":"apply","t":"apply(output: OutputStream, indent: String): JsonWriter","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter$.html#apply-d25","e":false,"i":"","n":"apply","t":"apply(output: OutputStream): JsonWriter","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter$.html#apply-fffff525","e":false,"i":"","n":"apply","t":"apply(output: File, indent: String): JsonWriter","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter$.html#apply-d2a","e":false,"i":"","n":"apply","t":"apply(output: File): JsonWriter","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter$.html#apply-fffffd4c","e":false,"i":"","n":"apply","t":"apply(output: Path, indent: String): JsonWriter","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter$.html#apply-fffff351","e":false,"i":"","n":"apply","t":"apply(output: Path): JsonWriter","d":"grapple.json.JsonWriter","k":"def","x":""}];