pages = [{"l":"index.html","n":"Grapple","t":"Grapple","d":"","k":"static"},
{"l":"grapple/json.html","n":"grapple.json","t":"package grapple.json","d":"grapple/json","k":"package"},
{"l":"grapple/json.html","n":"\\","t":"def \\(name: String): JsonValue","d":"grapple/json","k":"def"},
{"l":"grapple/json.html","n":"\\","t":"def \\(index: Int): JsonValue","d":"grapple/json","k":"def"},
{"l":"grapple/json.html","n":"\\\\","t":"def \\\\(name: String): Seq[JsonValue]","d":"grapple/json","k":"def"},
{"l":"grapple/json/arrayToJsonArray.html","n":"arrayToJsonArray","t":"given arrayToJsonArray[T](using val converter: JsonOutput[T]): JsonOutput[Array[T]]","d":"grapple/json","k":"given"},
{"l":"grapple/json/arrayToJsonArray.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json","k":"val"},
{"l":"grapple/json/arrayToJsonArray.html","n":"write","t":"def write(value: Array[T]): JsonArray","d":"grapple/json","k":"def"},
{"l":"grapple/json/bigDecimalToJsonNumber$.html","n":"bigDecimalToJsonNumber","t":"given bigDecimalToJsonNumber: JsonOutput[BigDecimal]","d":"grapple/json","k":"given"},
{"l":"grapple/json/bigDecimalToJsonNumber$.html","n":"write","t":"def write(value: BigDecimal): JsonNumber","d":"grapple/json","k":"def"},
{"l":"grapple/json/bigIntToJsonNumber$.html","n":"bigIntToJsonNumber","t":"given bigIntToJsonNumber: JsonOutput[BigInt]","d":"grapple/json","k":"given"},
{"l":"grapple/json/bigIntToJsonNumber$.html","n":"write","t":"def write(value: BigInt): JsonNumber","d":"grapple/json","k":"def"},
{"l":"grapple/json/booleanToJsonBoolean$.html","n":"booleanToJsonBoolean","t":"given booleanToJsonBoolean: JsonOutput[Boolean]","d":"grapple/json","k":"given"},
{"l":"grapple/json/booleanToJsonBoolean$.html","n":"write","t":"def write(value: Boolean): JsonBoolean","d":"grapple/json","k":"def"},
{"l":"grapple/json/byteToJsonNumber$.html","n":"byteToJsonNumber","t":"given byteToJsonNumber: JsonOutput[Byte]","d":"grapple/json","k":"given"},
{"l":"grapple/json/byteToJsonNumber$.html","n":"write","t":"def write(value: Byte): JsonNumber","d":"grapple/json","k":"def"},
{"l":"grapple/json/doubleToJsonNumber$.html","n":"doubleToJsonNumber","t":"given doubleToJsonNumber: JsonOutput[Double]","d":"grapple/json","k":"given"},
{"l":"grapple/json/doubleToJsonNumber$.html","n":"write","t":"def write(value: Double): JsonNumber","d":"grapple/json","k":"def"},
{"l":"grapple/json/eitherToJsonValue.html","n":"eitherToJsonValue","t":"given eitherToJsonValue[A, B, M <: (Either)](using val left: JsonOutput[A])(using val right: JsonOutput[B]): JsonOutput[M[A, B]]","d":"grapple/json","k":"given"},
{"l":"grapple/json/eitherToJsonValue.html","n":"left","t":"val left: JsonOutput[A]","d":"grapple/json","k":"val"},
{"l":"grapple/json/eitherToJsonValue.html","n":"right","t":"val right: JsonOutput[B]","d":"grapple/json","k":"val"},
{"l":"grapple/json/eitherToJsonValue.html","n":"write","t":"def write(value: M[A, B]): JsonValue","d":"grapple/json","k":"def"},
{"l":"grapple/json/failureToJsonNull$.html","n":"failureToJsonNull","t":"given failureToJsonNull: JsonOutput[Failure[_]]","d":"grapple/json","k":"given"},
{"l":"grapple/json/failureToJsonNull$.html","n":"write","t":"def write(value: Failure[_]): JsonNull","d":"grapple/json","k":"def"},
{"l":"grapple/json/floatToJsonNumber$.html","n":"floatToJsonNumber","t":"given floatToJsonNumber: JsonOutput[Float]","d":"grapple/json","k":"given"},
{"l":"grapple/json/floatToJsonNumber$.html","n":"write","t":"def write(value: Float): JsonNumber","d":"grapple/json","k":"def"},
{"l":"grapple/json/intToJsonNumber$.html","n":"intToJsonNumber","t":"given intToJsonNumber: JsonOutput[Int]","d":"grapple/json","k":"given"},
{"l":"grapple/json/intToJsonNumber$.html","n":"write","t":"def write(value: Int): JsonNumber","d":"grapple/json","k":"def"},
{"l":"grapple/json/iterableToJsonArray.html","n":"iterableToJsonArray","t":"given iterableToJsonArray[T, M <: (Iterable)](using val converter: JsonOutput[T]): JsonOutput[M[T]]","d":"grapple/json","k":"given"},
{"l":"grapple/json/iterableToJsonArray.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json","k":"val"},
{"l":"grapple/json/iterableToJsonArray.html","n":"write","t":"def write(value: M[T]): JsonArray","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonInputConversion.html","n":"jsonInputConversion","t":"given jsonInputConversion[T](using val converter: JsonInput[T]): Conversion[JsonValue, T]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonInputConversion.html","n":"apply","t":"def apply(value: JsonValue): T","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonInputConversion.html","n":"converter","t":"val converter: JsonInput[T]","d":"grapple/json","k":"val"},
{"l":"grapple/json/jsonOutputConversion.html","n":"jsonOutputConversion","t":"given jsonOutputConversion[T](using val converter: JsonOutput[T]): Conversion[T, JsonValue]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonOutputConversion.html","n":"apply","t":"def apply(value: T): JsonValue","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonOutputConversion.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json","k":"val"},
{"l":"grapple/json/jsonValueToBigDecimal$.html","n":"jsonValueToBigDecimal","t":"given jsonValueToBigDecimal: JsonInput[BigDecimal]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToBigDecimal$.html","n":"read","t":"def read(value: JsonValue): BigDecimal","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToBigInt$.html","n":"jsonValueToBigInt","t":"given jsonValueToBigInt: JsonInput[BigInt]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToBigInt$.html","n":"read","t":"def read(value: JsonValue): BigInt","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToBoolean$.html","n":"jsonValueToBoolean","t":"given jsonValueToBoolean: JsonInput[Boolean]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToBoolean$.html","n":"read","t":"def read(value: JsonValue): Boolean","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToByte$.html","n":"jsonValueToByte","t":"given jsonValueToByte: JsonInput[Byte]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToByte$.html","n":"read","t":"def read(value: JsonValue): Byte","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToCollection.html","n":"jsonValueToCollection","t":"given jsonValueToCollection[T, M[T]](using val converter: JsonInput[T])(using val factory: Factory[T, M[T]]): JsonInput[M[T]]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToCollection.html","n":"converter","t":"val converter: JsonInput[T]","d":"grapple/json","k":"val"},
{"l":"grapple/json/jsonValueToCollection.html","n":"factory","t":"val factory: Factory[T, M[T]]","d":"grapple/json","k":"val"},
{"l":"grapple/json/jsonValueToCollection.html","n":"read","t":"def read(value: JsonValue): M[T]","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToDouble$.html","n":"jsonValueToDouble","t":"given jsonValueToDouble: JsonInput[Double]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToDouble$.html","n":"read","t":"def read(value: JsonValue): Double","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToEither.html","n":"jsonValueToEither","t":"given jsonValueToEither[A, B](using val left: JsonInput[A])(using val right: JsonInput[B]): JsonInput[Either[A, B]]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToEither.html","n":"left","t":"val left: JsonInput[A]","d":"grapple/json","k":"val"},
{"l":"grapple/json/jsonValueToEither.html","n":"read","t":"def read(value: JsonValue): Either[A, B]","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToEither.html","n":"right","t":"val right: JsonInput[B]","d":"grapple/json","k":"val"},
{"l":"grapple/json/jsonValueToFloat$.html","n":"jsonValueToFloat","t":"given jsonValueToFloat: JsonInput[Float]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToFloat$.html","n":"read","t":"def read(value: JsonValue): Float","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToInt$.html","n":"jsonValueToInt","t":"given jsonValueToInt: JsonInput[Int]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToInt$.html","n":"read","t":"def read(value: JsonValue): Int","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToJsonArray$.html","n":"jsonValueToJsonArray","t":"given jsonValueToJsonArray: JsonInput[JsonArray]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToJsonArray$.html","n":"read","t":"def read(value: JsonValue): JsonArray","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToJsonBoolean$.html","n":"jsonValueToJsonBoolean","t":"given jsonValueToJsonBoolean: JsonInput[JsonBoolean]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToJsonBoolean$.html","n":"read","t":"def read(value: JsonValue): JsonBoolean","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToJsonNull$.html","n":"jsonValueToJsonNull","t":"given jsonValueToJsonNull: JsonInput[JsonNull]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToJsonNull$.html","n":"read","t":"def read(value: JsonValue): JsonNull","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToJsonNumber$.html","n":"jsonValueToJsonNumber","t":"given jsonValueToJsonNumber: JsonInput[JsonNumber]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToJsonNumber$.html","n":"read","t":"def read(value: JsonValue): JsonNumber","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToJsonObject$.html","n":"jsonValueToJsonObject","t":"given jsonValueToJsonObject: JsonInput[JsonObject]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToJsonObject$.html","n":"read","t":"def read(value: JsonValue): JsonObject","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToJsonString$.html","n":"jsonValueToJsonString","t":"given jsonValueToJsonString: JsonInput[JsonString]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToJsonString$.html","n":"read","t":"def read(value: JsonValue): JsonString","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToJsonValue$.html","n":"jsonValueToJsonValue","t":"given jsonValueToJsonValue: JsonInput[JsonValue]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToJsonValue$.html","n":"read","t":"def read(value: JsonValue): JsonValue","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToLong$.html","n":"jsonValueToLong","t":"given jsonValueToLong: JsonInput[Long]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToLong$.html","n":"read","t":"def read(value: JsonValue): Long","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToOption.html","n":"jsonValueToOption","t":"given jsonValueToOption[T](using val converter: JsonInput[T]): JsonInput[Option[T]]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToOption.html","n":"converter","t":"val converter: JsonInput[T]","d":"grapple/json","k":"val"},
{"l":"grapple/json/jsonValueToOption.html","n":"read","t":"def read(value: JsonValue): Option[T]","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToShort$.html","n":"jsonValueToShort","t":"given jsonValueToShort: JsonInput[Short]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToShort$.html","n":"read","t":"def read(value: JsonValue): Short","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToString$.html","n":"jsonValueToString","t":"given jsonValueToString: JsonInput[String]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToString$.html","n":"read","t":"def read(value: JsonValue): String","d":"grapple/json","k":"def"},
{"l":"grapple/json/jsonValueToTry.html","n":"jsonValueToTry","t":"given jsonValueToTry[T](using val converter: JsonInput[T]): JsonInput[Try[T]]","d":"grapple/json","k":"given"},
{"l":"grapple/json/jsonValueToTry.html","n":"converter","t":"val converter: JsonInput[T]","d":"grapple/json","k":"val"},
{"l":"grapple/json/jsonValueToTry.html","n":"read","t":"def read(value: JsonValue): Try[T]","d":"grapple/json","k":"def"},
{"l":"grapple/json/leftToJsonValue.html","n":"leftToJsonValue","t":"given leftToJsonValue[T](using val converter: JsonOutput[T]): JsonOutput[Left[T, _]]","d":"grapple/json","k":"given"},
{"l":"grapple/json/leftToJsonValue.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json","k":"val"},
{"l":"grapple/json/leftToJsonValue.html","n":"write","t":"def write(value: Left[T, _]): JsonValue","d":"grapple/json","k":"def"},
{"l":"grapple/json/longToJsonNumber$.html","n":"longToJsonNumber","t":"given longToJsonNumber: JsonOutput[Long]","d":"grapple/json","k":"given"},
{"l":"grapple/json/longToJsonNumber$.html","n":"write","t":"def write(value: Long): JsonNumber","d":"grapple/json","k":"def"},
{"l":"grapple/json/mapToJsonObject.html","n":"mapToJsonObject","t":"given mapToJsonObject[T, M <: ([T] =>> Map[String, T])](using val converter: JsonOutput[T]): JsonOutput[M[T]]","d":"grapple/json","k":"given"},
{"l":"grapple/json/mapToJsonObject.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json","k":"val"},
{"l":"grapple/json/mapToJsonObject.html","n":"write","t":"def write(value: M[T]): JsonObject","d":"grapple/json","k":"def"},
{"l":"grapple/json/noneToJsonNull$.html","n":"noneToJsonNull","t":"given noneToJsonNull: JsonOutput[None]","d":"grapple/json","k":"given"},
{"l":"grapple/json/noneToJsonNull$.html","n":"write","t":"def write(value: None): JsonNull","d":"grapple/json","k":"def"},
{"l":"grapple/json/optionToJsonValue.html","n":"optionToJsonValue","t":"given optionToJsonValue[T, M <: (Option)](using val converter: JsonOutput[T]): JsonOutput[M[T]]","d":"grapple/json","k":"given"},
{"l":"grapple/json/optionToJsonValue.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json","k":"val"},
{"l":"grapple/json/optionToJsonValue.html","n":"write","t":"def write(value: M[T]): JsonValue","d":"grapple/json","k":"def"},
{"l":"grapple/json/rightToJsonValue.html","n":"rightToJsonValue","t":"given rightToJsonValue[T](using val converter: JsonOutput[T]): JsonOutput[Right[_, T]]","d":"grapple/json","k":"given"},
{"l":"grapple/json/rightToJsonValue.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json","k":"val"},
{"l":"grapple/json/rightToJsonValue.html","n":"write","t":"def write(value: Right[_, T]): JsonValue","d":"grapple/json","k":"def"},
{"l":"grapple/json/shortToJsonNumber$.html","n":"shortToJsonNumber","t":"given shortToJsonNumber: JsonOutput[Short]","d":"grapple/json","k":"given"},
{"l":"grapple/json/shortToJsonNumber$.html","n":"write","t":"def write(value: Short): JsonNumber","d":"grapple/json","k":"def"},
{"l":"grapple/json/stringToJsonString$.html","n":"stringToJsonString","t":"given stringToJsonString: JsonOutput[String]","d":"grapple/json","k":"given"},
{"l":"grapple/json/stringToJsonString$.html","n":"write","t":"def write(value: String): JsonString","d":"grapple/json","k":"def"},
{"l":"grapple/json/toJsonArrayConversion.html","n":"toJsonArrayConversion","t":"given toJsonArrayConversion(using val converter: JsonInput[JsonArray]): Conversion[JsonValue, JsonArray]","d":"grapple/json","k":"given"},
{"l":"grapple/json/toJsonArrayConversion.html","n":"apply","t":"def apply(value: JsonValue): JsonArray","d":"grapple/json","k":"def"},
{"l":"grapple/json/toJsonArrayConversion.html","n":"converter","t":"val converter: JsonInput[JsonArray]","d":"grapple/json","k":"val"},
{"l":"grapple/json/toJsonObjectConversion.html","n":"toJsonObjectConversion","t":"given toJsonObjectConversion(using val converter: JsonInput[JsonObject]): Conversion[JsonValue, JsonObject]","d":"grapple/json","k":"given"},
{"l":"grapple/json/toJsonObjectConversion.html","n":"apply","t":"def apply(value: JsonValue): JsonObject","d":"grapple/json","k":"def"},
{"l":"grapple/json/toJsonObjectConversion.html","n":"converter","t":"val converter: JsonInput[JsonObject]","d":"grapple/json","k":"val"},
{"l":"grapple/json/tryToJsonValue.html","n":"tryToJsonValue","t":"given tryToJsonValue[T, M <: (Try)](using val converter: JsonOutput[T]): JsonOutput[M[T]]","d":"grapple/json","k":"given"},
{"l":"grapple/json/tryToJsonValue.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json","k":"val"},
{"l":"grapple/json/tryToJsonValue.html","n":"write","t":"def write(value: M[T]): JsonValue","d":"grapple/json","k":"def"},
{"l":"grapple/json/tupleToJsonField.html","n":"tupleToJsonField","t":"given tupleToJsonField[T](using val converter: JsonOutput[T]): Conversion[(String, T), (String, JsonValue)]","d":"grapple/json","k":"given"},
{"l":"grapple/json/tupleToJsonField.html","n":"apply","t":"def apply(value: (String, T)): (String, JsonValue)","d":"grapple/json","k":"def"},
{"l":"grapple/json/tupleToJsonField.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json","k":"val"},
{"l":"grapple/json/Json$.html","n":"Json","t":"object Json","d":"grapple/json/Json$","k":"object"},
{"l":"grapple/json/Json$.html","n":"arr","t":"def arr(values: JsonValue*): JsonArray","d":"grapple/json/Json$","k":"def"},
{"l":"grapple/json/Json$.html","n":"obj","t":"def obj(fields: (String, JsonValue)*): JsonObject","d":"grapple/json/Json$","k":"def"},
{"l":"grapple/json/Json$.html","n":"parse","t":"def parse(text: String): JsonStructure","d":"grapple/json/Json$","k":"def"},
{"l":"grapple/json/Json$.html","n":"parse","t":"def parse(bytes: Array[Byte]): JsonStructure","d":"grapple/json/Json$","k":"def"},
{"l":"grapple/json/Json$.html","n":"parse","t":"def parse(input: Reader): JsonStructure","d":"grapple/json/Json$","k":"def"},
{"l":"grapple/json/Json$.html","n":"parse","t":"def parse(input: InputStream): JsonStructure","d":"grapple/json/Json$","k":"def"},
{"l":"grapple/json/Json$.html","n":"parse","t":"def parse(input: File): JsonStructure","d":"grapple/json/Json$","k":"def"},
{"l":"grapple/json/Json$.html","n":"parse","t":"def parse(input: Path): JsonStructure","d":"grapple/json/Json$","k":"def"},
{"l":"grapple/json/Json$.html","n":"toBytes","t":"def toBytes(value: JsonValue): Array[Byte]","d":"grapple/json/Json$","k":"def"},
{"l":"grapple/json/Json$.html","n":"toJson","t":"def toJson[T](value: T)(using converter: JsonOutput[T]): JsonValue","d":"grapple/json/Json$","k":"def"},
{"l":"grapple/json/Json$.html","n":"toPrettyPrint","t":"def toPrettyPrint(value: JsonValue): String","d":"grapple/json/Json$","k":"def"},
{"l":"grapple/json/Json$.html","n":"toPrettyPrint","t":"def toPrettyPrint(value: JsonValue, indent: String): String","d":"grapple/json/Json$","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"JsonArray","t":"trait JsonArray extends JsonStructure","d":"grapple/json/JsonArray","k":"trait"},
{"l":"grapple/json/JsonArray.html","n":"++","t":"def ++(suffix: JsonArray): JsonArray","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"+:","t":"def +:(value: JsonValue): JsonArray","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":":+","t":"def :+(value: JsonValue): JsonArray","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"apply","t":"def apply(index: Int): JsonValue","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"getBigDecimal","t":"def getBigDecimal(index: Int): BigDecimal","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"getBigInt","t":"def getBigInt(index: Int): BigInt","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"getBoolean","t":"def getBoolean(index: Int): Boolean","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"getByte","t":"def getByte(index: Int): Byte","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"getDouble","t":"def getDouble(index: Int): Double","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"getFloat","t":"def getFloat(index: Int): Float","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"getInt","t":"def getInt(index: Int): Int","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"getJsonArray","t":"def getJsonArray(index: Int): JsonArray","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"getJsonBoolean","t":"def getJsonBoolean(index: Int): JsonBoolean","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"getJsonNull","t":"def getJsonNull(index: Int): JsonNull","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"getJsonNumber","t":"def getJsonNumber(index: Int): JsonNumber","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"getJsonObject","t":"def getJsonObject(index: Int): JsonObject","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"getJsonString","t":"def getJsonString(index: Int): JsonString","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"getLong","t":"def getLong(index: Int): Long","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"getShort","t":"def getShort(index: Int): Short","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"getString","t":"def getString(index: Int): String","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"head","t":"def head: JsonValue","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"headOption","t":"def headOption: Option[JsonValue]","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"init","t":"def init: JsonArray","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"isNull","t":"def isNull(index: Int): Boolean","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"last","t":"def last: JsonValue","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"lastOption","t":"def lastOption: Option[JsonValue]","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"slice","t":"def slice(from: Int, until: Int): JsonArray","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"tail","t":"def tail: JsonArray","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"updated","t":"def updated(index: Int, value: JsonValue): JsonArray","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray.html","n":"values","t":"def values: Seq[JsonValue]","d":"grapple/json/JsonArray","k":"def"},
{"l":"grapple/json/JsonArray$.html","n":"JsonArray","t":"object JsonArray","d":"grapple/json/JsonArray$","k":"object"},
{"l":"grapple/json/JsonArray$.html","n":"apply","t":"def apply(): JsonArray","d":"grapple/json/JsonArray$","k":"def"},
{"l":"grapple/json/JsonArray$.html","n":"apply","t":"def apply(values: Seq[JsonValue]): JsonArray","d":"grapple/json/JsonArray$","k":"def"},
{"l":"grapple/json/JsonArray$.html","n":"empty","t":"def empty: JsonArray","d":"grapple/json/JsonArray$","k":"def"},
{"l":"grapple/json/JsonArray$.html","n":"unapply","t":"def unapply(json: JsonArray): Option[Seq[JsonValue]]","d":"grapple/json/JsonArray$","k":"def"},
{"l":"grapple/json/JsonArrayBuilder.html","n":"JsonArrayBuilder","t":"class JsonArrayBuilder","d":"grapple/json/JsonArrayBuilder","k":"class"},
{"l":"grapple/json/JsonArrayBuilder.html","n":"add","t":"def add(value: JsonValue): JsonArrayBuilder","d":"grapple/json/JsonArrayBuilder","k":"def"},
{"l":"grapple/json/JsonArrayBuilder.html","n":"add","t":"def add(value: String): JsonArrayBuilder","d":"grapple/json/JsonArrayBuilder","k":"def"},
{"l":"grapple/json/JsonArrayBuilder.html","n":"add","t":"def add(value: Byte): JsonArrayBuilder","d":"grapple/json/JsonArrayBuilder","k":"def"},
{"l":"grapple/json/JsonArrayBuilder.html","n":"add","t":"def add(value: Short): JsonArrayBuilder","d":"grapple/json/JsonArrayBuilder","k":"def"},
{"l":"grapple/json/JsonArrayBuilder.html","n":"add","t":"def add(value: Int): JsonArrayBuilder","d":"grapple/json/JsonArrayBuilder","k":"def"},
{"l":"grapple/json/JsonArrayBuilder.html","n":"add","t":"def add(value: Long): JsonArrayBuilder","d":"grapple/json/JsonArrayBuilder","k":"def"},
{"l":"grapple/json/JsonArrayBuilder.html","n":"add","t":"def add(value: Float): JsonArrayBuilder","d":"grapple/json/JsonArrayBuilder","k":"def"},
{"l":"grapple/json/JsonArrayBuilder.html","n":"add","t":"def add(value: Double): JsonArrayBuilder","d":"grapple/json/JsonArrayBuilder","k":"def"},
{"l":"grapple/json/JsonArrayBuilder.html","n":"add","t":"def add(value: BigInt): JsonArrayBuilder","d":"grapple/json/JsonArrayBuilder","k":"def"},
{"l":"grapple/json/JsonArrayBuilder.html","n":"add","t":"def add(value: BigDecimal): JsonArrayBuilder","d":"grapple/json/JsonArrayBuilder","k":"def"},
{"l":"grapple/json/JsonArrayBuilder.html","n":"add","t":"def add(value: Boolean): JsonArrayBuilder","d":"grapple/json/JsonArrayBuilder","k":"def"},
{"l":"grapple/json/JsonArrayBuilder.html","n":"addNull","t":"def addNull(): JsonArrayBuilder","d":"grapple/json/JsonArrayBuilder","k":"def"},
{"l":"grapple/json/JsonArrayBuilder.html","n":"build","t":"def build(): JsonArray","d":"grapple/json/JsonArrayBuilder","k":"def"},
{"l":"grapple/json/JsonBoolean.html","n":"JsonBoolean","t":"trait JsonBoolean extends JsonValue","d":"grapple/json/JsonBoolean","k":"trait"},
{"l":"grapple/json/JsonBoolean.html","n":"value","t":"def value: Boolean","d":"grapple/json/JsonBoolean","k":"def"},
{"l":"grapple/json/JsonBoolean$.html","n":"JsonBoolean","t":"object JsonBoolean","d":"grapple/json/JsonBoolean$","k":"object"},
{"l":"grapple/json/JsonBoolean$.html","n":"apply","t":"def apply(value: Boolean): JsonBoolean","d":"grapple/json/JsonBoolean$","k":"def"},
{"l":"grapple/json/JsonBoolean$.html","n":"unapply","t":"def unapply(json: JsonBoolean): Option[Boolean]","d":"grapple/json/JsonBoolean$","k":"def"},
{"l":"grapple/json/JsonException.html","n":"JsonException","t":"class JsonException(message: String, cause: Throwable) extends RuntimeException","d":"grapple/json/JsonException","k":"class"},
{"l":"grapple/json/JsonException.html","n":"this","t":"def this()","d":"grapple/json/JsonException","k":"def"},
{"l":"grapple/json/JsonException.html","n":"this","t":"def this(message: String)","d":"grapple/json/JsonException","k":"def"},
{"l":"grapple/json/JsonException.html","n":"this","t":"def this(cause: Throwable)","d":"grapple/json/JsonException","k":"def"},
{"l":"grapple/json/JsonFalse$.html","n":"JsonFalse","t":"object JsonFalse extends JsonBoolean","d":"grapple/json/JsonFalse$","k":"object"},
{"l":"grapple/json/JsonFalse$.html","n":"toString","t":"val toString: String","d":"grapple/json/JsonFalse$","k":"val"},
{"l":"grapple/json/JsonFalse$.html","n":"value","t":"val value: Boolean","d":"grapple/json/JsonFalse$","k":"val"},
{"l":"grapple/json/JsonGenerator.html","n":"JsonGenerator","t":"trait JsonGenerator extends AutoCloseable","d":"grapple/json/JsonGenerator","k":"trait"},
{"l":"grapple/json/JsonGenerator.html","n":"close","t":"def close(): Unit","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"flush","t":"def flush(): Unit","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(name: String, value: JsonValue): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(name: String, value: String): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(name: String, value: Byte): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(name: String, value: Short): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(name: String, value: Int): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(name: String, value: Long): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(name: String, value: Float): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(name: String, value: Double): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(name: String, value: BigInt): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(name: String, value: BigDecimal): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(name: String, value: Boolean): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(value: JsonValue): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(value: String): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(value: Byte): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(value: Short): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(value: Int): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(value: Long): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(value: Float): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(value: Double): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(value: BigInt): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(value: BigDecimal): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"write","t":"def write(value: Boolean): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"writeEnd","t":"def writeEnd(): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"writeNull","t":"def writeNull(name: String): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"writeNull","t":"def writeNull(): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"writeStartArray","t":"def writeStartArray(name: String): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"writeStartArray","t":"def writeStartArray(): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"writeStartObject","t":"def writeStartObject(name: String): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator.html","n":"writeStartObject","t":"def writeStartObject(): JsonGenerator","d":"grapple/json/JsonGenerator","k":"def"},
{"l":"grapple/json/JsonGenerator$.html","n":"JsonGenerator","t":"object JsonGenerator","d":"grapple/json/JsonGenerator$","k":"object"},
{"l":"grapple/json/JsonGenerator$.html","n":"apply","t":"def apply(output: Writer, indent: String): JsonGenerator","d":"grapple/json/JsonGenerator$","k":"def"},
{"l":"grapple/json/JsonGenerator$.html","n":"apply","t":"def apply(output: Writer): JsonGenerator","d":"grapple/json/JsonGenerator$","k":"def"},
{"l":"grapple/json/JsonGenerator$.html","n":"apply","t":"def apply(output: OutputStream, indent: String): JsonGenerator","d":"grapple/json/JsonGenerator$","k":"def"},
{"l":"grapple/json/JsonGenerator$.html","n":"apply","t":"def apply(output: OutputStream): JsonGenerator","d":"grapple/json/JsonGenerator$","k":"def"},
{"l":"grapple/json/JsonGenerator$.html","n":"apply","t":"def apply(output: File, indent: String): JsonGenerator","d":"grapple/json/JsonGenerator$","k":"def"},
{"l":"grapple/json/JsonGenerator$.html","n":"apply","t":"def apply(output: File): JsonGenerator","d":"grapple/json/JsonGenerator$","k":"def"},
{"l":"grapple/json/JsonGenerator$.html","n":"apply","t":"def apply(output: Path, indent: String): JsonGenerator","d":"grapple/json/JsonGenerator$","k":"def"},
{"l":"grapple/json/JsonGenerator$.html","n":"apply","t":"def apply(output: Path): JsonGenerator","d":"grapple/json/JsonGenerator$","k":"def"},
{"l":"grapple/json/JsonGeneratorError.html","n":"JsonGeneratorError","t":"class JsonGeneratorError(message: String) extends JsonException","d":"grapple/json/JsonGeneratorError","k":"class"},
{"l":"grapple/json/JsonInput.html","n":"JsonInput","t":"trait JsonInput[T]","d":"grapple/json/JsonInput","k":"trait"},
{"l":"grapple/json/JsonInput.html","n":"read","t":"def read(value: JsonValue): T","d":"grapple/json/JsonInput","k":"def"},
{"l":"grapple/json/JsonNull.html","n":"JsonNull","t":"trait JsonNull extends JsonValue","d":"grapple/json/JsonNull","k":"trait"},
{"l":"grapple/json/JsonNull$.html","n":"JsonNull","t":"object JsonNull extends JsonNull","d":"grapple/json/JsonNull$","k":"object"},
{"l":"grapple/json/JsonNull$.html","n":"toString","t":"val toString: String","d":"grapple/json/JsonNull$","k":"val"},
{"l":"grapple/json/JsonNumber.html","n":"JsonNumber","t":"trait JsonNumber extends JsonValue","d":"grapple/json/JsonNumber","k":"trait"},
{"l":"grapple/json/JsonNumber.html","n":"bigDecimalValue","t":"def bigDecimalValue: BigDecimal","d":"grapple/json/JsonNumber","k":"def"},
{"l":"grapple/json/JsonNumber.html","n":"bigIntValue","t":"def bigIntValue: BigInt","d":"grapple/json/JsonNumber","k":"def"},
{"l":"grapple/json/JsonNumber.html","n":"byteValue","t":"def byteValue: Byte","d":"grapple/json/JsonNumber","k":"def"},
{"l":"grapple/json/JsonNumber.html","n":"doubleValue","t":"def doubleValue: Double","d":"grapple/json/JsonNumber","k":"def"},
{"l":"grapple/json/JsonNumber.html","n":"floatValue","t":"def floatValue: Float","d":"grapple/json/JsonNumber","k":"def"},
{"l":"grapple/json/JsonNumber.html","n":"intValue","t":"def intValue: Int","d":"grapple/json/JsonNumber","k":"def"},
{"l":"grapple/json/JsonNumber.html","n":"longValue","t":"def longValue: Long","d":"grapple/json/JsonNumber","k":"def"},
{"l":"grapple/json/JsonNumber.html","n":"shortValue","t":"def shortValue: Short","d":"grapple/json/JsonNumber","k":"def"},
{"l":"grapple/json/JsonNumber$.html","n":"JsonNumber","t":"object JsonNumber","d":"grapple/json/JsonNumber$","k":"object"},
{"l":"grapple/json/JsonNumber$.html","n":"apply","t":"def apply(value: String): JsonNumber","d":"grapple/json/JsonNumber$","k":"def"},
{"l":"grapple/json/JsonNumber$.html","n":"apply","t":"def apply(value: Int): JsonNumber","d":"grapple/json/JsonNumber$","k":"def"},
{"l":"grapple/json/JsonNumber$.html","n":"apply","t":"def apply(value: Long): JsonNumber","d":"grapple/json/JsonNumber$","k":"def"},
{"l":"grapple/json/JsonNumber$.html","n":"apply","t":"def apply(value: Double): JsonNumber","d":"grapple/json/JsonNumber$","k":"def"},
{"l":"grapple/json/JsonNumber$.html","n":"apply","t":"def apply(value: BigInt): JsonNumber","d":"grapple/json/JsonNumber$","k":"def"},
{"l":"grapple/json/JsonNumber$.html","n":"apply","t":"def apply(value: BigDecimal): JsonNumber","d":"grapple/json/JsonNumber$","k":"def"},
{"l":"grapple/json/JsonNumber$.html","n":"unapply","t":"def unapply(json: JsonNumber): Option[BigDecimal]","d":"grapple/json/JsonNumber$","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"JsonObject","t":"trait JsonObject extends JsonStructure","d":"grapple/json/JsonObject","k":"trait"},
{"l":"grapple/json/JsonObject.html","n":"+","t":"def +(field: (String, JsonValue)): JsonObject","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"++","t":"def ++(other: JsonObject): JsonObject","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"-","t":"def -(name: String): JsonObject","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"apply","t":"def apply(name: String): JsonValue","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"fields","t":"def fields: Map[String, JsonValue]","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"get","t":"def get(name: String): Option[JsonValue]","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getBigDecimal","t":"def getBigDecimal(name: String): BigDecimal","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getBigInt","t":"def getBigInt(name: String): BigInt","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getBoolean","t":"def getBoolean(name: String): Boolean","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getByte","t":"def getByte(name: String): Byte","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getDouble","t":"def getDouble(name: String): Double","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getFloat","t":"def getFloat(name: String): Float","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getInt","t":"def getInt(name: String): Int","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getJsonArray","t":"def getJsonArray(name: String): JsonArray","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getJsonBoolean","t":"def getJsonBoolean(name: String): JsonBoolean","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getJsonNull","t":"def getJsonNull(name: String): JsonNull","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getJsonNumber","t":"def getJsonNumber(name: String): JsonNumber","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getJsonObject","t":"def getJsonObject(name: String): JsonObject","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getJsonString","t":"def getJsonString(name: String): JsonString","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getLong","t":"def getLong(name: String): Long","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getOrElse","t":"def getOrElse[T](name: String, default: => T)(using JsonInput[T]): T","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getShort","t":"def getShort(name: String): Short","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"getString","t":"def getString(name: String): String","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"isNull","t":"def isNull(name: String): Boolean","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"map","t":"def map[T](name: String)(using JsonInput[T]): Option[T]","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject.html","n":"names","t":"def names: Seq[String]","d":"grapple/json/JsonObject","k":"def"},
{"l":"grapple/json/JsonObject$.html","n":"JsonObject","t":"object JsonObject","d":"grapple/json/JsonObject$","k":"object"},
{"l":"grapple/json/JsonObject$.html","n":"apply","t":"def apply(): JsonObject","d":"grapple/json/JsonObject$","k":"def"},
{"l":"grapple/json/JsonObject$.html","n":"apply","t":"def apply(fields: Map[String, JsonValue]): JsonObject","d":"grapple/json/JsonObject$","k":"def"},
{"l":"grapple/json/JsonObject$.html","n":"apply","t":"def apply(fields: Seq[(String, JsonValue)]): JsonObject","d":"grapple/json/JsonObject$","k":"def"},
{"l":"grapple/json/JsonObject$.html","n":"empty","t":"def empty: JsonObject","d":"grapple/json/JsonObject$","k":"def"},
{"l":"grapple/json/JsonObject$.html","n":"unapply","t":"def unapply(json: JsonObject): Option[Map[String, JsonValue]]","d":"grapple/json/JsonObject$","k":"def"},
{"l":"grapple/json/JsonObjectBuilder.html","n":"JsonObjectBuilder","t":"class JsonObjectBuilder","d":"grapple/json/JsonObjectBuilder","k":"class"},
{"l":"grapple/json/JsonObjectBuilder.html","n":"add","t":"def add(name: String, value: JsonValue): JsonObjectBuilder","d":"grapple/json/JsonObjectBuilder","k":"def"},
{"l":"grapple/json/JsonObjectBuilder.html","n":"add","t":"def add(name: String, value: String): JsonObjectBuilder","d":"grapple/json/JsonObjectBuilder","k":"def"},
{"l":"grapple/json/JsonObjectBuilder.html","n":"add","t":"def add(name: String, value: Byte): JsonObjectBuilder","d":"grapple/json/JsonObjectBuilder","k":"def"},
{"l":"grapple/json/JsonObjectBuilder.html","n":"add","t":"def add(name: String, value: Short): JsonObjectBuilder","d":"grapple/json/JsonObjectBuilder","k":"def"},
{"l":"grapple/json/JsonObjectBuilder.html","n":"add","t":"def add(name: String, value: Int): JsonObjectBuilder","d":"grapple/json/JsonObjectBuilder","k":"def"},
{"l":"grapple/json/JsonObjectBuilder.html","n":"add","t":"def add(name: String, value: Long): JsonObjectBuilder","d":"grapple/json/JsonObjectBuilder","k":"def"},
{"l":"grapple/json/JsonObjectBuilder.html","n":"add","t":"def add(name: String, value: Float): JsonObjectBuilder","d":"grapple/json/JsonObjectBuilder","k":"def"},
{"l":"grapple/json/JsonObjectBuilder.html","n":"add","t":"def add(name: String, value: Double): JsonObjectBuilder","d":"grapple/json/JsonObjectBuilder","k":"def"},
{"l":"grapple/json/JsonObjectBuilder.html","n":"add","t":"def add(name: String, value: BigInt): JsonObjectBuilder","d":"grapple/json/JsonObjectBuilder","k":"def"},
{"l":"grapple/json/JsonObjectBuilder.html","n":"add","t":"def add(name: String, value: BigDecimal): JsonObjectBuilder","d":"grapple/json/JsonObjectBuilder","k":"def"},
{"l":"grapple/json/JsonObjectBuilder.html","n":"add","t":"def add(name: String, value: Boolean): JsonObjectBuilder","d":"grapple/json/JsonObjectBuilder","k":"def"},
{"l":"grapple/json/JsonObjectBuilder.html","n":"addNull","t":"def addNull(name: String): JsonObjectBuilder","d":"grapple/json/JsonObjectBuilder","k":"def"},
{"l":"grapple/json/JsonObjectBuilder.html","n":"build","t":"def build(): JsonObject","d":"grapple/json/JsonObjectBuilder","k":"def"},
{"l":"grapple/json/JsonOutput.html","n":"JsonOutput","t":"trait JsonOutput[T]","d":"grapple/json/JsonOutput","k":"trait"},
{"l":"grapple/json/JsonOutput.html","n":"write","t":"def write(value: T): JsonValue","d":"grapple/json/JsonOutput","k":"def"},
{"l":"grapple/json/JsonParser.html","n":"JsonParser","t":"trait JsonParser extends Iterator[Event] with AutoCloseable","d":"grapple/json/JsonParser","k":"trait"},
{"l":"grapple/json/JsonParser.html","n":"close","t":"def close(): Unit","d":"grapple/json/JsonParser","k":"def"},
{"l":"grapple/json/JsonParser.html","n":"getArray","t":"def getArray(): JsonArray","d":"grapple/json/JsonParser","k":"def"},
{"l":"grapple/json/JsonParser.html","n":"getObject","t":"def getObject(): JsonObject","d":"grapple/json/JsonParser","k":"def"},
{"l":"grapple/json/JsonParser.html","n":"hasNext","t":"def hasNext: Boolean","d":"grapple/json/JsonParser","k":"def"},
{"l":"grapple/json/JsonParser.html","n":"next","t":"def next(): Event","d":"grapple/json/JsonParser","k":"def"},
{"l":"grapple/json/JsonParser$.html","n":"JsonParser","t":"object JsonParser","d":"grapple/json/JsonParser$","k":"object"},
{"l":"grapple/json/JsonParser$.html","n":"apply","t":"def apply(input: Reader): JsonParser","d":"grapple/json/JsonParser$","k":"def"},
{"l":"grapple/json/JsonParser$.html","n":"apply","t":"def apply(text: String): JsonParser","d":"grapple/json/JsonParser$","k":"def"},
{"l":"grapple/json/JsonParser$.html","n":"apply","t":"def apply(bytes: Array[Byte]): JsonParser","d":"grapple/json/JsonParser$","k":"def"},
{"l":"grapple/json/JsonParser$.html","n":"apply","t":"def apply(input: InputStream): JsonParser","d":"grapple/json/JsonParser$","k":"def"},
{"l":"grapple/json/JsonParser$.html","n":"apply","t":"def apply(input: File): JsonParser","d":"grapple/json/JsonParser$","k":"def"},
{"l":"grapple/json/JsonParser$.html","n":"apply","t":"def apply(input: Path): JsonParser","d":"grapple/json/JsonParser$","k":"def"},
{"l":"grapple/json/JsonParser$$Event.html","n":"Event","t":"enum Event","d":"grapple/json/JsonParser$$Event","k":"enum"},
{"l":"grapple/json/JsonParser$$Event$$FieldName.html","n":"FieldName","t":"case FieldName(get: String) extends Event","d":"grapple/json/JsonParser$$Event","k":"case"},
{"l":"grapple/json/JsonParser$$Event$$Value.html","n":"Value","t":"case Value(get: JsonValue) extends Event","d":"grapple/json/JsonParser$$Event","k":"case"},
{"l":"grapple/json/JsonParser$$Event.html","n":"StartObject","t":"case StartObject extends Event","d":"grapple/json/JsonParser$$Event","k":"case"},
{"l":"grapple/json/JsonParser$$Event.html","n":"StartArray","t":"case StartArray extends Event","d":"grapple/json/JsonParser$$Event","k":"case"},
{"l":"grapple/json/JsonParser$$Event.html","n":"EndObject","t":"case EndObject extends Event","d":"grapple/json/JsonParser$$Event","k":"case"},
{"l":"grapple/json/JsonParser$$Event.html","n":"EndArray","t":"case EndArray extends Event","d":"grapple/json/JsonParser$$Event","k":"case"},
{"l":"grapple/json/JsonParser$$Event$$FieldName.html","n":"FieldName","t":"case FieldName(get: String) extends Event","d":"grapple/json/JsonParser$$Event$$FieldName","k":"case"},
{"l":"grapple/json/JsonParser$$Event$$Value.html","n":"Value","t":"case Value(get: JsonValue) extends Event","d":"grapple/json/JsonParser$$Event$$Value","k":"case"},
{"l":"grapple/json/JsonParserError.html","n":"JsonParserError","t":"class JsonParserError(message: String, offset: Long) extends JsonException","d":"grapple/json/JsonParserError","k":"class"},
{"l":"grapple/json/JsonReader.html","n":"JsonReader","t":"trait JsonReader extends AutoCloseable","d":"grapple/json/JsonReader","k":"trait"},
{"l":"grapple/json/JsonReader.html","n":"close","t":"def close(): Unit","d":"grapple/json/JsonReader","k":"def"},
{"l":"grapple/json/JsonReader.html","n":"read","t":"def read(): JsonStructure","d":"grapple/json/JsonReader","k":"def"},
{"l":"grapple/json/JsonReader$.html","n":"JsonReader","t":"object JsonReader","d":"grapple/json/JsonReader$","k":"object"},
{"l":"grapple/json/JsonReader$.html","n":"apply","t":"def apply(text: String): JsonReader","d":"grapple/json/JsonReader$","k":"def"},
{"l":"grapple/json/JsonReader$.html","n":"apply","t":"def apply(bytes: Array[Byte]): JsonReader","d":"grapple/json/JsonReader$","k":"def"},
{"l":"grapple/json/JsonReader$.html","n":"apply","t":"def apply(input: Reader): JsonReader","d":"grapple/json/JsonReader$","k":"def"},
{"l":"grapple/json/JsonReader$.html","n":"apply","t":"def apply(input: InputStream): JsonReader","d":"grapple/json/JsonReader$","k":"def"},
{"l":"grapple/json/JsonReader$.html","n":"apply","t":"def apply(input: File): JsonReader","d":"grapple/json/JsonReader$","k":"def"},
{"l":"grapple/json/JsonReader$.html","n":"apply","t":"def apply(input: Path): JsonReader","d":"grapple/json/JsonReader$","k":"def"},
{"l":"grapple/json/JsonString.html","n":"JsonString","t":"trait JsonString extends JsonValue","d":"grapple/json/JsonString","k":"trait"},
{"l":"grapple/json/JsonString.html","n":"value","t":"def value: String","d":"grapple/json/JsonString","k":"def"},
{"l":"grapple/json/JsonString$.html","n":"JsonString","t":"object JsonString","d":"grapple/json/JsonString$","k":"object"},
{"l":"grapple/json/JsonString$.html","n":"apply","t":"def apply(value: String): JsonString","d":"grapple/json/JsonString$","k":"def"},
{"l":"grapple/json/JsonString$.html","n":"unapply","t":"def unapply(json: JsonString): Option[String]","d":"grapple/json/JsonString$","k":"def"},
{"l":"grapple/json/JsonStructure.html","n":"JsonStructure","t":"trait JsonStructure extends JsonValue","d":"grapple/json/JsonStructure","k":"trait"},
{"l":"grapple/json/JsonStructure.html","n":"isEmpty","t":"def isEmpty: Boolean","d":"grapple/json/JsonStructure","k":"def"},
{"l":"grapple/json/JsonStructure.html","n":"size","t":"def size: Int","d":"grapple/json/JsonStructure","k":"def"},
{"l":"grapple/json/JsonTrue$.html","n":"JsonTrue","t":"object JsonTrue extends JsonBoolean","d":"grapple/json/JsonTrue$","k":"object"},
{"l":"grapple/json/JsonTrue$.html","n":"toString","t":"val toString: String","d":"grapple/json/JsonTrue$","k":"val"},
{"l":"grapple/json/JsonTrue$.html","n":"value","t":"val value: Boolean","d":"grapple/json/JsonTrue$","k":"val"},
{"l":"grapple/json/JsonValue.html","n":"JsonValue","t":"trait JsonValue","d":"grapple/json/JsonValue","k":"trait"},
{"l":"grapple/json/JsonValue.html","n":"as","t":"def as[T](using converter: JsonInput[T]): T","d":"grapple/json/JsonValue","k":"def"},
{"l":"grapple/json/JsonWriter.html","n":"JsonWriter","t":"trait JsonWriter extends AutoCloseable","d":"grapple/json/JsonWriter","k":"trait"},
{"l":"grapple/json/JsonWriter.html","n":"close","t":"def close(): Unit","d":"grapple/json/JsonWriter","k":"def"},
{"l":"grapple/json/JsonWriter.html","n":"write","t":"def write(value: JsonStructure): JsonWriter","d":"grapple/json/JsonWriter","k":"def"},
{"l":"grapple/json/JsonWriter$.html","n":"JsonWriter","t":"object JsonWriter","d":"grapple/json/JsonWriter$","k":"object"},
{"l":"grapple/json/JsonWriter$.html","n":"apply","t":"def apply(output: Writer, indent: String): JsonWriter","d":"grapple/json/JsonWriter$","k":"def"},
{"l":"grapple/json/JsonWriter$.html","n":"apply","t":"def apply(output: Writer): JsonWriter","d":"grapple/json/JsonWriter$","k":"def"},
{"l":"grapple/json/JsonWriter$.html","n":"apply","t":"def apply(output: OutputStream, indent: String): JsonWriter","d":"grapple/json/JsonWriter$","k":"def"},
{"l":"grapple/json/JsonWriter$.html","n":"apply","t":"def apply(output: OutputStream): JsonWriter","d":"grapple/json/JsonWriter$","k":"def"},
{"l":"grapple/json/JsonWriter$.html","n":"apply","t":"def apply(output: File, indent: String): JsonWriter","d":"grapple/json/JsonWriter$","k":"def"},
{"l":"grapple/json/JsonWriter$.html","n":"apply","t":"def apply(output: File): JsonWriter","d":"grapple/json/JsonWriter$","k":"def"},
{"l":"grapple/json/JsonWriter$.html","n":"apply","t":"def apply(output: Path, indent: String): JsonWriter","d":"grapple/json/JsonWriter$","k":"def"},
{"l":"grapple/json/JsonWriter$.html","n":"apply","t":"def apply(output: Path): JsonWriter","d":"grapple/json/JsonWriter$","k":"def"},
{"l":"grapple/json/arrayToJsonArray.html","n":"arrayToJsonArray","t":"given arrayToJsonArray[T](using val converter: JsonOutput[T]): JsonOutput[Array[T]]","d":"grapple/json/arrayToJsonArray","k":"given"},
{"l":"grapple/json/arrayToJsonArray.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json/arrayToJsonArray","k":"val"},
{"l":"grapple/json/arrayToJsonArray.html","n":"write","t":"def write(value: Array[T]): JsonArray","d":"grapple/json/arrayToJsonArray","k":"def"},
{"l":"grapple/json/bigDecimalToJsonNumber$.html","n":"bigDecimalToJsonNumber","t":"given bigDecimalToJsonNumber: JsonOutput[BigDecimal]","d":"grapple/json/bigDecimalToJsonNumber$","k":"given"},
{"l":"grapple/json/bigDecimalToJsonNumber$.html","n":"write","t":"def write(value: BigDecimal): JsonNumber","d":"grapple/json/bigDecimalToJsonNumber$","k":"def"},
{"l":"grapple/json/bigIntToJsonNumber$.html","n":"bigIntToJsonNumber","t":"given bigIntToJsonNumber: JsonOutput[BigInt]","d":"grapple/json/bigIntToJsonNumber$","k":"given"},
{"l":"grapple/json/bigIntToJsonNumber$.html","n":"write","t":"def write(value: BigInt): JsonNumber","d":"grapple/json/bigIntToJsonNumber$","k":"def"},
{"l":"grapple/json/booleanToJsonBoolean$.html","n":"booleanToJsonBoolean","t":"given booleanToJsonBoolean: JsonOutput[Boolean]","d":"grapple/json/booleanToJsonBoolean$","k":"given"},
{"l":"grapple/json/booleanToJsonBoolean$.html","n":"write","t":"def write(value: Boolean): JsonBoolean","d":"grapple/json/booleanToJsonBoolean$","k":"def"},
{"l":"grapple/json/byteToJsonNumber$.html","n":"byteToJsonNumber","t":"given byteToJsonNumber: JsonOutput[Byte]","d":"grapple/json/byteToJsonNumber$","k":"given"},
{"l":"grapple/json/byteToJsonNumber$.html","n":"write","t":"def write(value: Byte): JsonNumber","d":"grapple/json/byteToJsonNumber$","k":"def"},
{"l":"grapple/json/doubleToJsonNumber$.html","n":"doubleToJsonNumber","t":"given doubleToJsonNumber: JsonOutput[Double]","d":"grapple/json/doubleToJsonNumber$","k":"given"},
{"l":"grapple/json/doubleToJsonNumber$.html","n":"write","t":"def write(value: Double): JsonNumber","d":"grapple/json/doubleToJsonNumber$","k":"def"},
{"l":"grapple/json/eitherToJsonValue.html","n":"eitherToJsonValue","t":"given eitherToJsonValue[A, B, M <: (Either)](using val left: JsonOutput[A])(using val right: JsonOutput[B]): JsonOutput[M[A, B]]","d":"grapple/json/eitherToJsonValue","k":"given"},
{"l":"grapple/json/eitherToJsonValue.html","n":"left","t":"val left: JsonOutput[A]","d":"grapple/json/eitherToJsonValue","k":"val"},
{"l":"grapple/json/eitherToJsonValue.html","n":"right","t":"val right: JsonOutput[B]","d":"grapple/json/eitherToJsonValue","k":"val"},
{"l":"grapple/json/eitherToJsonValue.html","n":"write","t":"def write(value: M[A, B]): JsonValue","d":"grapple/json/eitherToJsonValue","k":"def"},
{"l":"grapple/json/failureToJsonNull$.html","n":"failureToJsonNull","t":"given failureToJsonNull: JsonOutput[Failure[_]]","d":"grapple/json/failureToJsonNull$","k":"given"},
{"l":"grapple/json/failureToJsonNull$.html","n":"write","t":"def write(value: Failure[_]): JsonNull","d":"grapple/json/failureToJsonNull$","k":"def"},
{"l":"grapple/json/floatToJsonNumber$.html","n":"floatToJsonNumber","t":"given floatToJsonNumber: JsonOutput[Float]","d":"grapple/json/floatToJsonNumber$","k":"given"},
{"l":"grapple/json/floatToJsonNumber$.html","n":"write","t":"def write(value: Float): JsonNumber","d":"grapple/json/floatToJsonNumber$","k":"def"},
{"l":"grapple/json/intToJsonNumber$.html","n":"intToJsonNumber","t":"given intToJsonNumber: JsonOutput[Int]","d":"grapple/json/intToJsonNumber$","k":"given"},
{"l":"grapple/json/intToJsonNumber$.html","n":"write","t":"def write(value: Int): JsonNumber","d":"grapple/json/intToJsonNumber$","k":"def"},
{"l":"grapple/json/iterableToJsonArray.html","n":"iterableToJsonArray","t":"given iterableToJsonArray[T, M <: (Iterable)](using val converter: JsonOutput[T]): JsonOutput[M[T]]","d":"grapple/json/iterableToJsonArray","k":"given"},
{"l":"grapple/json/iterableToJsonArray.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json/iterableToJsonArray","k":"val"},
{"l":"grapple/json/iterableToJsonArray.html","n":"write","t":"def write(value: M[T]): JsonArray","d":"grapple/json/iterableToJsonArray","k":"def"},
{"l":"grapple/json/jsonInputConversion.html","n":"jsonInputConversion","t":"given jsonInputConversion[T](using val converter: JsonInput[T]): Conversion[JsonValue, T]","d":"grapple/json/jsonInputConversion","k":"given"},
{"l":"grapple/json/jsonInputConversion.html","n":"apply","t":"def apply(value: JsonValue): T","d":"grapple/json/jsonInputConversion","k":"def"},
{"l":"grapple/json/jsonInputConversion.html","n":"converter","t":"val converter: JsonInput[T]","d":"grapple/json/jsonInputConversion","k":"val"},
{"l":"grapple/json/jsonOutputConversion.html","n":"jsonOutputConversion","t":"given jsonOutputConversion[T](using val converter: JsonOutput[T]): Conversion[T, JsonValue]","d":"grapple/json/jsonOutputConversion","k":"given"},
{"l":"grapple/json/jsonOutputConversion.html","n":"apply","t":"def apply(value: T): JsonValue","d":"grapple/json/jsonOutputConversion","k":"def"},
{"l":"grapple/json/jsonOutputConversion.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json/jsonOutputConversion","k":"val"},
{"l":"grapple/json/jsonValueToBigDecimal$.html","n":"jsonValueToBigDecimal","t":"given jsonValueToBigDecimal: JsonInput[BigDecimal]","d":"grapple/json/jsonValueToBigDecimal$","k":"given"},
{"l":"grapple/json/jsonValueToBigDecimal$.html","n":"read","t":"def read(value: JsonValue): BigDecimal","d":"grapple/json/jsonValueToBigDecimal$","k":"def"},
{"l":"grapple/json/jsonValueToBigInt$.html","n":"jsonValueToBigInt","t":"given jsonValueToBigInt: JsonInput[BigInt]","d":"grapple/json/jsonValueToBigInt$","k":"given"},
{"l":"grapple/json/jsonValueToBigInt$.html","n":"read","t":"def read(value: JsonValue): BigInt","d":"grapple/json/jsonValueToBigInt$","k":"def"},
{"l":"grapple/json/jsonValueToBoolean$.html","n":"jsonValueToBoolean","t":"given jsonValueToBoolean: JsonInput[Boolean]","d":"grapple/json/jsonValueToBoolean$","k":"given"},
{"l":"grapple/json/jsonValueToBoolean$.html","n":"read","t":"def read(value: JsonValue): Boolean","d":"grapple/json/jsonValueToBoolean$","k":"def"},
{"l":"grapple/json/jsonValueToByte$.html","n":"jsonValueToByte","t":"given jsonValueToByte: JsonInput[Byte]","d":"grapple/json/jsonValueToByte$","k":"given"},
{"l":"grapple/json/jsonValueToByte$.html","n":"read","t":"def read(value: JsonValue): Byte","d":"grapple/json/jsonValueToByte$","k":"def"},
{"l":"grapple/json/jsonValueToCollection.html","n":"jsonValueToCollection","t":"given jsonValueToCollection[T, M[T]](using val converter: JsonInput[T])(using val factory: Factory[T, M[T]]): JsonInput[M[T]]","d":"grapple/json/jsonValueToCollection","k":"given"},
{"l":"grapple/json/jsonValueToCollection.html","n":"converter","t":"val converter: JsonInput[T]","d":"grapple/json/jsonValueToCollection","k":"val"},
{"l":"grapple/json/jsonValueToCollection.html","n":"factory","t":"val factory: Factory[T, M[T]]","d":"grapple/json/jsonValueToCollection","k":"val"},
{"l":"grapple/json/jsonValueToCollection.html","n":"read","t":"def read(value: JsonValue): M[T]","d":"grapple/json/jsonValueToCollection","k":"def"},
{"l":"grapple/json/jsonValueToDouble$.html","n":"jsonValueToDouble","t":"given jsonValueToDouble: JsonInput[Double]","d":"grapple/json/jsonValueToDouble$","k":"given"},
{"l":"grapple/json/jsonValueToDouble$.html","n":"read","t":"def read(value: JsonValue): Double","d":"grapple/json/jsonValueToDouble$","k":"def"},
{"l":"grapple/json/jsonValueToEither.html","n":"jsonValueToEither","t":"given jsonValueToEither[A, B](using val left: JsonInput[A])(using val right: JsonInput[B]): JsonInput[Either[A, B]]","d":"grapple/json/jsonValueToEither","k":"given"},
{"l":"grapple/json/jsonValueToEither.html","n":"left","t":"val left: JsonInput[A]","d":"grapple/json/jsonValueToEither","k":"val"},
{"l":"grapple/json/jsonValueToEither.html","n":"read","t":"def read(value: JsonValue): Either[A, B]","d":"grapple/json/jsonValueToEither","k":"def"},
{"l":"grapple/json/jsonValueToEither.html","n":"right","t":"val right: JsonInput[B]","d":"grapple/json/jsonValueToEither","k":"val"},
{"l":"grapple/json/jsonValueToFloat$.html","n":"jsonValueToFloat","t":"given jsonValueToFloat: JsonInput[Float]","d":"grapple/json/jsonValueToFloat$","k":"given"},
{"l":"grapple/json/jsonValueToFloat$.html","n":"read","t":"def read(value: JsonValue): Float","d":"grapple/json/jsonValueToFloat$","k":"def"},
{"l":"grapple/json/jsonValueToInt$.html","n":"jsonValueToInt","t":"given jsonValueToInt: JsonInput[Int]","d":"grapple/json/jsonValueToInt$","k":"given"},
{"l":"grapple/json/jsonValueToInt$.html","n":"read","t":"def read(value: JsonValue): Int","d":"grapple/json/jsonValueToInt$","k":"def"},
{"l":"grapple/json/jsonValueToJsonArray$.html","n":"jsonValueToJsonArray","t":"given jsonValueToJsonArray: JsonInput[JsonArray]","d":"grapple/json/jsonValueToJsonArray$","k":"given"},
{"l":"grapple/json/jsonValueToJsonArray$.html","n":"read","t":"def read(value: JsonValue): JsonArray","d":"grapple/json/jsonValueToJsonArray$","k":"def"},
{"l":"grapple/json/jsonValueToJsonBoolean$.html","n":"jsonValueToJsonBoolean","t":"given jsonValueToJsonBoolean: JsonInput[JsonBoolean]","d":"grapple/json/jsonValueToJsonBoolean$","k":"given"},
{"l":"grapple/json/jsonValueToJsonBoolean$.html","n":"read","t":"def read(value: JsonValue): JsonBoolean","d":"grapple/json/jsonValueToJsonBoolean$","k":"def"},
{"l":"grapple/json/jsonValueToJsonNull$.html","n":"jsonValueToJsonNull","t":"given jsonValueToJsonNull: JsonInput[JsonNull]","d":"grapple/json/jsonValueToJsonNull$","k":"given"},
{"l":"grapple/json/jsonValueToJsonNull$.html","n":"read","t":"def read(value: JsonValue): JsonNull","d":"grapple/json/jsonValueToJsonNull$","k":"def"},
{"l":"grapple/json/jsonValueToJsonNumber$.html","n":"jsonValueToJsonNumber","t":"given jsonValueToJsonNumber: JsonInput[JsonNumber]","d":"grapple/json/jsonValueToJsonNumber$","k":"given"},
{"l":"grapple/json/jsonValueToJsonNumber$.html","n":"read","t":"def read(value: JsonValue): JsonNumber","d":"grapple/json/jsonValueToJsonNumber$","k":"def"},
{"l":"grapple/json/jsonValueToJsonObject$.html","n":"jsonValueToJsonObject","t":"given jsonValueToJsonObject: JsonInput[JsonObject]","d":"grapple/json/jsonValueToJsonObject$","k":"given"},
{"l":"grapple/json/jsonValueToJsonObject$.html","n":"read","t":"def read(value: JsonValue): JsonObject","d":"grapple/json/jsonValueToJsonObject$","k":"def"},
{"l":"grapple/json/jsonValueToJsonString$.html","n":"jsonValueToJsonString","t":"given jsonValueToJsonString: JsonInput[JsonString]","d":"grapple/json/jsonValueToJsonString$","k":"given"},
{"l":"grapple/json/jsonValueToJsonString$.html","n":"read","t":"def read(value: JsonValue): JsonString","d":"grapple/json/jsonValueToJsonString$","k":"def"},
{"l":"grapple/json/jsonValueToJsonValue$.html","n":"jsonValueToJsonValue","t":"given jsonValueToJsonValue: JsonInput[JsonValue]","d":"grapple/json/jsonValueToJsonValue$","k":"given"},
{"l":"grapple/json/jsonValueToJsonValue$.html","n":"read","t":"def read(value: JsonValue): JsonValue","d":"grapple/json/jsonValueToJsonValue$","k":"def"},
{"l":"grapple/json/jsonValueToLong$.html","n":"jsonValueToLong","t":"given jsonValueToLong: JsonInput[Long]","d":"grapple/json/jsonValueToLong$","k":"given"},
{"l":"grapple/json/jsonValueToLong$.html","n":"read","t":"def read(value: JsonValue): Long","d":"grapple/json/jsonValueToLong$","k":"def"},
{"l":"grapple/json/jsonValueToOption.html","n":"jsonValueToOption","t":"given jsonValueToOption[T](using val converter: JsonInput[T]): JsonInput[Option[T]]","d":"grapple/json/jsonValueToOption","k":"given"},
{"l":"grapple/json/jsonValueToOption.html","n":"converter","t":"val converter: JsonInput[T]","d":"grapple/json/jsonValueToOption","k":"val"},
{"l":"grapple/json/jsonValueToOption.html","n":"read","t":"def read(value: JsonValue): Option[T]","d":"grapple/json/jsonValueToOption","k":"def"},
{"l":"grapple/json/jsonValueToShort$.html","n":"jsonValueToShort","t":"given jsonValueToShort: JsonInput[Short]","d":"grapple/json/jsonValueToShort$","k":"given"},
{"l":"grapple/json/jsonValueToShort$.html","n":"read","t":"def read(value: JsonValue): Short","d":"grapple/json/jsonValueToShort$","k":"def"},
{"l":"grapple/json/jsonValueToString$.html","n":"jsonValueToString","t":"given jsonValueToString: JsonInput[String]","d":"grapple/json/jsonValueToString$","k":"given"},
{"l":"grapple/json/jsonValueToString$.html","n":"read","t":"def read(value: JsonValue): String","d":"grapple/json/jsonValueToString$","k":"def"},
{"l":"grapple/json/jsonValueToTry.html","n":"jsonValueToTry","t":"given jsonValueToTry[T](using val converter: JsonInput[T]): JsonInput[Try[T]]","d":"grapple/json/jsonValueToTry","k":"given"},
{"l":"grapple/json/jsonValueToTry.html","n":"converter","t":"val converter: JsonInput[T]","d":"grapple/json/jsonValueToTry","k":"val"},
{"l":"grapple/json/jsonValueToTry.html","n":"read","t":"def read(value: JsonValue): Try[T]","d":"grapple/json/jsonValueToTry","k":"def"},
{"l":"grapple/json/leftToJsonValue.html","n":"leftToJsonValue","t":"given leftToJsonValue[T](using val converter: JsonOutput[T]): JsonOutput[Left[T, _]]","d":"grapple/json/leftToJsonValue","k":"given"},
{"l":"grapple/json/leftToJsonValue.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json/leftToJsonValue","k":"val"},
{"l":"grapple/json/leftToJsonValue.html","n":"write","t":"def write(value: Left[T, _]): JsonValue","d":"grapple/json/leftToJsonValue","k":"def"},
{"l":"grapple/json/longToJsonNumber$.html","n":"longToJsonNumber","t":"given longToJsonNumber: JsonOutput[Long]","d":"grapple/json/longToJsonNumber$","k":"given"},
{"l":"grapple/json/longToJsonNumber$.html","n":"write","t":"def write(value: Long): JsonNumber","d":"grapple/json/longToJsonNumber$","k":"def"},
{"l":"grapple/json/mapToJsonObject.html","n":"mapToJsonObject","t":"given mapToJsonObject[T, M <: ([T] =>> Map[String, T])](using val converter: JsonOutput[T]): JsonOutput[M[T]]","d":"grapple/json/mapToJsonObject","k":"given"},
{"l":"grapple/json/mapToJsonObject.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json/mapToJsonObject","k":"val"},
{"l":"grapple/json/mapToJsonObject.html","n":"write","t":"def write(value: M[T]): JsonObject","d":"grapple/json/mapToJsonObject","k":"def"},
{"l":"grapple/json/noneToJsonNull$.html","n":"noneToJsonNull","t":"given noneToJsonNull: JsonOutput[None]","d":"grapple/json/noneToJsonNull$","k":"given"},
{"l":"grapple/json/noneToJsonNull$.html","n":"write","t":"def write(value: None): JsonNull","d":"grapple/json/noneToJsonNull$","k":"def"},
{"l":"grapple/json/optionToJsonValue.html","n":"optionToJsonValue","t":"given optionToJsonValue[T, M <: (Option)](using val converter: JsonOutput[T]): JsonOutput[M[T]]","d":"grapple/json/optionToJsonValue","k":"given"},
{"l":"grapple/json/optionToJsonValue.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json/optionToJsonValue","k":"val"},
{"l":"grapple/json/optionToJsonValue.html","n":"write","t":"def write(value: M[T]): JsonValue","d":"grapple/json/optionToJsonValue","k":"def"},
{"l":"grapple/json/rightToJsonValue.html","n":"rightToJsonValue","t":"given rightToJsonValue[T](using val converter: JsonOutput[T]): JsonOutput[Right[_, T]]","d":"grapple/json/rightToJsonValue","k":"given"},
{"l":"grapple/json/rightToJsonValue.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json/rightToJsonValue","k":"val"},
{"l":"grapple/json/rightToJsonValue.html","n":"write","t":"def write(value: Right[_, T]): JsonValue","d":"grapple/json/rightToJsonValue","k":"def"},
{"l":"grapple/json/shortToJsonNumber$.html","n":"shortToJsonNumber","t":"given shortToJsonNumber: JsonOutput[Short]","d":"grapple/json/shortToJsonNumber$","k":"given"},
{"l":"grapple/json/shortToJsonNumber$.html","n":"write","t":"def write(value: Short): JsonNumber","d":"grapple/json/shortToJsonNumber$","k":"def"},
{"l":"grapple/json/stringToJsonString$.html","n":"stringToJsonString","t":"given stringToJsonString: JsonOutput[String]","d":"grapple/json/stringToJsonString$","k":"given"},
{"l":"grapple/json/stringToJsonString$.html","n":"write","t":"def write(value: String): JsonString","d":"grapple/json/stringToJsonString$","k":"def"},
{"l":"grapple/json/toJsonArrayConversion.html","n":"toJsonArrayConversion","t":"given toJsonArrayConversion(using val converter: JsonInput[JsonArray]): Conversion[JsonValue, JsonArray]","d":"grapple/json/toJsonArrayConversion","k":"given"},
{"l":"grapple/json/toJsonArrayConversion.html","n":"apply","t":"def apply(value: JsonValue): JsonArray","d":"grapple/json/toJsonArrayConversion","k":"def"},
{"l":"grapple/json/toJsonArrayConversion.html","n":"converter","t":"val converter: JsonInput[JsonArray]","d":"grapple/json/toJsonArrayConversion","k":"val"},
{"l":"grapple/json/toJsonObjectConversion.html","n":"toJsonObjectConversion","t":"given toJsonObjectConversion(using val converter: JsonInput[JsonObject]): Conversion[JsonValue, JsonObject]","d":"grapple/json/toJsonObjectConversion","k":"given"},
{"l":"grapple/json/toJsonObjectConversion.html","n":"apply","t":"def apply(value: JsonValue): JsonObject","d":"grapple/json/toJsonObjectConversion","k":"def"},
{"l":"grapple/json/toJsonObjectConversion.html","n":"converter","t":"val converter: JsonInput[JsonObject]","d":"grapple/json/toJsonObjectConversion","k":"val"},
{"l":"grapple/json/tryToJsonValue.html","n":"tryToJsonValue","t":"given tryToJsonValue[T, M <: (Try)](using val converter: JsonOutput[T]): JsonOutput[M[T]]","d":"grapple/json/tryToJsonValue","k":"given"},
{"l":"grapple/json/tryToJsonValue.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json/tryToJsonValue","k":"val"},
{"l":"grapple/json/tryToJsonValue.html","n":"write","t":"def write(value: M[T]): JsonValue","d":"grapple/json/tryToJsonValue","k":"def"},
{"l":"grapple/json/tupleToJsonField.html","n":"tupleToJsonField","t":"given tupleToJsonField[T](using val converter: JsonOutput[T]): Conversion[(String, T), (String, JsonValue)]","d":"grapple/json/tupleToJsonField","k":"given"},
{"l":"grapple/json/tupleToJsonField.html","n":"apply","t":"def apply(value: (String, T)): (String, JsonValue)","d":"grapple/json/tupleToJsonField","k":"def"},
{"l":"grapple/json/tupleToJsonField.html","n":"converter","t":"val converter: JsonOutput[T]","d":"grapple/json/tupleToJsonField","k":"val"},
{"l":"grapple/json/rpc.html","n":"grapple.json.rpc","t":"package grapple.json.rpc","d":"grapple/json/rpc","k":"package"},
{"l":"grapple/json/rpc.html","n":"defaultOnFailure","t":"val defaultOnFailure: PartialFunction[Throwable, JsonRpcError]","d":"grapple/json/rpc","k":"val"},
{"l":"grapple/json/rpc/jsonRpcErrorToJsonValue$.html","n":"jsonRpcErrorToJsonValue","t":"given jsonRpcErrorToJsonValue: JsonOutput[JsonRpcError]","d":"grapple/json/rpc","k":"given"},
{"l":"grapple/json/rpc/jsonRpcErrorToJsonValue$.html","n":"write","t":"def write(error: JsonRpcError): JsonValue","d":"grapple/json/rpc","k":"def"},
{"l":"grapple/json/rpc/jsonRpcIdentifierToJsonValue$.html","n":"jsonRpcIdentifierToJsonValue","t":"given jsonRpcIdentifierToJsonValue: JsonOutput[JsonRpcIdentifier]","d":"grapple/json/rpc","k":"given"},
{"l":"grapple/json/rpc/jsonRpcIdentifierToJsonValue$.html","n":"write","t":"def write(id: JsonRpcIdentifier): JsonValue","d":"grapple/json/rpc","k":"def"},
{"l":"grapple/json/rpc/jsonRpcRequestToJsonValue$.html","n":"jsonRpcRequestToJsonValue","t":"given jsonRpcRequestToJsonValue: JsonOutput[JsonRpcRequest]","d":"grapple/json/rpc","k":"given"},
{"l":"grapple/json/rpc/jsonRpcRequestToJsonValue$.html","n":"write","t":"def write(request: JsonRpcRequest): JsonValue","d":"grapple/json/rpc","k":"def"},
{"l":"grapple/json/rpc/jsonRpcResponseToJsonValue$.html","n":"jsonRpcResponseToJsonValue","t":"given jsonRpcResponseToJsonValue: JsonOutput[JsonRpcResponse]","d":"grapple/json/rpc","k":"given"},
{"l":"grapple/json/rpc/jsonRpcResponseToJsonValue$.html","n":"write","t":"def write(response: JsonRpcResponse): JsonValue","d":"grapple/json/rpc","k":"def"},
{"l":"grapple/json/rpc/jsonValueToJsonRpcError$.html","n":"jsonValueToJsonRpcError","t":"given jsonValueToJsonRpcError: JsonInput[JsonRpcError]","d":"grapple/json/rpc","k":"given"},
{"l":"grapple/json/rpc/jsonValueToJsonRpcError$.html","n":"read","t":"def read(json: JsonValue): JsonRpcError","d":"grapple/json/rpc","k":"def"},
{"l":"grapple/json/rpc/jsonValueToJsonRpcIdentifier$.html","n":"jsonValueToJsonRpcIdentifier","t":"given jsonValueToJsonRpcIdentifier: JsonInput[JsonRpcIdentifier]","d":"grapple/json/rpc","k":"given"},
{"l":"grapple/json/rpc/jsonValueToJsonRpcIdentifier$.html","n":"read","t":"def read(json: JsonValue): JsonRpcIdentifier","d":"grapple/json/rpc","k":"def"},
{"l":"grapple/json/rpc/jsonValueToJsonRpcRequest$.html","n":"jsonValueToJsonRpcRequest","t":"given jsonValueToJsonRpcRequest: JsonInput[JsonRpcRequest]","d":"grapple/json/rpc","k":"given"},
{"l":"grapple/json/rpc/jsonValueToJsonRpcRequest$.html","n":"read","t":"def read(json: JsonValue): JsonRpcRequest","d":"grapple/json/rpc","k":"def"},
{"l":"grapple/json/rpc/jsonValueToJsonRpcResponse$.html","n":"jsonValueToJsonRpcResponse","t":"given jsonValueToJsonRpcResponse: JsonInput[JsonRpcResponse]","d":"grapple/json/rpc","k":"given"},
{"l":"grapple/json/rpc/jsonValueToJsonRpcResponse$.html","n":"read","t":"def read(json: JsonValue): JsonRpcResponse","d":"grapple/json/rpc","k":"def"},
{"l":"grapple/json/rpc/InternalError.html","n":"InternalError","t":"class InternalError extends JsonRpcError","d":"grapple/json/rpc/InternalError","k":"class"},
{"l":"grapple/json/rpc/InternalError$.html","n":"InternalError","t":"object InternalError","d":"grapple/json/rpc/InternalError$","k":"object"},
{"l":"grapple/json/rpc/InternalError$.html","n":"apply","t":"def apply(): InternalError","d":"grapple/json/rpc/InternalError$","k":"def"},
{"l":"grapple/json/rpc/InternalError$.html","n":"apply","t":"def apply(data: String): InternalError","d":"grapple/json/rpc/InternalError$","k":"def"},
{"l":"grapple/json/rpc/InternalError$.html","n":"apply","t":"def apply(data: JsonValue): InternalError","d":"grapple/json/rpc/InternalError$","k":"def"},
{"l":"grapple/json/rpc/InternalError$.html","n":"apply","t":"def apply(data: Option[JsonValue]): InternalError","d":"grapple/json/rpc/InternalError$","k":"def"},
{"l":"grapple/json/rpc/InternalError$.html","n":"unapply","t":"def unapply(error: InternalError): Option[(Int, String, Option[JsonValue])]","d":"grapple/json/rpc/InternalError$","k":"def"},
{"l":"grapple/json/rpc/InvalidParams.html","n":"InvalidParams","t":"class InvalidParams extends JsonRpcError","d":"grapple/json/rpc/InvalidParams","k":"class"},
{"l":"grapple/json/rpc/InvalidParams$.html","n":"InvalidParams","t":"object InvalidParams","d":"grapple/json/rpc/InvalidParams$","k":"object"},
{"l":"grapple/json/rpc/InvalidParams$.html","n":"apply","t":"def apply(): InvalidParams","d":"grapple/json/rpc/InvalidParams$","k":"def"},
{"l":"grapple/json/rpc/InvalidParams$.html","n":"apply","t":"def apply(data: String): InvalidParams","d":"grapple/json/rpc/InvalidParams$","k":"def"},
{"l":"grapple/json/rpc/InvalidParams$.html","n":"apply","t":"def apply(data: JsonValue): InvalidParams","d":"grapple/json/rpc/InvalidParams$","k":"def"},
{"l":"grapple/json/rpc/InvalidParams$.html","n":"apply","t":"def apply(data: Option[JsonValue]): InvalidParams","d":"grapple/json/rpc/InvalidParams$","k":"def"},
{"l":"grapple/json/rpc/InvalidParams$.html","n":"unapply","t":"def unapply(error: InvalidParams): Option[(Int, String, Option[JsonValue])]","d":"grapple/json/rpc/InvalidParams$","k":"def"},
{"l":"grapple/json/rpc/InvalidRequest.html","n":"InvalidRequest","t":"class InvalidRequest extends JsonRpcError","d":"grapple/json/rpc/InvalidRequest","k":"class"},
{"l":"grapple/json/rpc/InvalidRequest$.html","n":"InvalidRequest","t":"object InvalidRequest","d":"grapple/json/rpc/InvalidRequest$","k":"object"},
{"l":"grapple/json/rpc/InvalidRequest$.html","n":"apply","t":"def apply(): InvalidRequest","d":"grapple/json/rpc/InvalidRequest$","k":"def"},
{"l":"grapple/json/rpc/InvalidRequest$.html","n":"apply","t":"def apply(data: String): InvalidRequest","d":"grapple/json/rpc/InvalidRequest$","k":"def"},
{"l":"grapple/json/rpc/InvalidRequest$.html","n":"apply","t":"def apply(data: JsonValue): InvalidRequest","d":"grapple/json/rpc/InvalidRequest$","k":"def"},
{"l":"grapple/json/rpc/InvalidRequest$.html","n":"apply","t":"def apply(data: Option[JsonValue]): InvalidRequest","d":"grapple/json/rpc/InvalidRequest$","k":"def"},
{"l":"grapple/json/rpc/InvalidRequest$.html","n":"unapply","t":"def unapply(error: InvalidRequest): Option[(Int, String, Option[JsonValue])]","d":"grapple/json/rpc/InvalidRequest$","k":"def"},
{"l":"grapple/json/rpc/JsonRpcError.html","n":"JsonRpcError","t":"class JsonRpcError extends JsonException","d":"grapple/json/rpc/JsonRpcError","k":"class"},
{"l":"grapple/json/rpc/JsonRpcError.html","n":"code","t":"def code: Int","d":"grapple/json/rpc/JsonRpcError","k":"def"},
{"l":"grapple/json/rpc/JsonRpcError.html","n":"data","t":"def data: Option[JsonValue]","d":"grapple/json/rpc/JsonRpcError","k":"def"},
{"l":"grapple/json/rpc/JsonRpcError.html","n":"isInternalError","t":"def isInternalError: Boolean","d":"grapple/json/rpc/JsonRpcError","k":"def"},
{"l":"grapple/json/rpc/JsonRpcError.html","n":"isInvalidParams","t":"def isInvalidParams: Boolean","d":"grapple/json/rpc/JsonRpcError","k":"def"},
{"l":"grapple/json/rpc/JsonRpcError.html","n":"isInvalidRequest","t":"def isInvalidRequest: Boolean","d":"grapple/json/rpc/JsonRpcError","k":"def"},
{"l":"grapple/json/rpc/JsonRpcError.html","n":"isMethodNotFound","t":"def isMethodNotFound: Boolean","d":"grapple/json/rpc/JsonRpcError","k":"def"},
{"l":"grapple/json/rpc/JsonRpcError.html","n":"isParseError","t":"def isParseError: Boolean","d":"grapple/json/rpc/JsonRpcError","k":"def"},
{"l":"grapple/json/rpc/JsonRpcError.html","n":"isServerError","t":"def isServerError: Boolean","d":"grapple/json/rpc/JsonRpcError","k":"def"},
{"l":"grapple/json/rpc/JsonRpcError.html","n":"message","t":"def message: String","d":"grapple/json/rpc/JsonRpcError","k":"def"},
{"l":"grapple/json/rpc/JsonRpcError$.html","n":"JsonRpcError","t":"object JsonRpcError","d":"grapple/json/rpc/JsonRpcError$","k":"object"},
{"l":"grapple/json/rpc/JsonRpcError$.html","n":"apply","t":"def apply(code: Int, message: String): JsonRpcError","d":"grapple/json/rpc/JsonRpcError$","k":"def"},
{"l":"grapple/json/rpc/JsonRpcError$.html","n":"apply","t":"def apply(code: Int, message: String, data: JsonValue): JsonRpcError","d":"grapple/json/rpc/JsonRpcError$","k":"def"},
{"l":"grapple/json/rpc/JsonRpcError$.html","n":"apply","t":"def apply(code: Int, message: String, data: Option[JsonValue]): JsonRpcError","d":"grapple/json/rpc/JsonRpcError$","k":"def"},
{"l":"grapple/json/rpc/JsonRpcError$.html","n":"unapply","t":"def unapply(error: JsonRpcError): Option[(Int, String, Option[JsonValue])]","d":"grapple/json/rpc/JsonRpcError$","k":"def"},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html","n":"JsonRpcIdentifier","t":"trait JsonRpcIdentifier","d":"grapple/json/rpc/JsonRpcIdentifier","k":"trait"},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html","n":"isNull","t":"def isNull: Boolean","d":"grapple/json/rpc/JsonRpcIdentifier","k":"def"},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html","n":"isNumber","t":"def isNumber: Boolean","d":"grapple/json/rpc/JsonRpcIdentifier","k":"def"},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html","n":"isString","t":"def isString: Boolean","d":"grapple/json/rpc/JsonRpcIdentifier","k":"def"},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html","n":"numberValue","t":"def numberValue: Long","d":"grapple/json/rpc/JsonRpcIdentifier","k":"def"},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html","n":"stringValue","t":"def stringValue: String","d":"grapple/json/rpc/JsonRpcIdentifier","k":"def"},
{"l":"grapple/json/rpc/JsonRpcIdentifier$.html","n":"JsonRpcIdentifier","t":"object JsonRpcIdentifier","d":"grapple/json/rpc/JsonRpcIdentifier$","k":"object"},
{"l":"grapple/json/rpc/JsonRpcIdentifier$.html","n":"apply","t":"def apply(id: String): JsonRpcIdentifier","d":"grapple/json/rpc/JsonRpcIdentifier$","k":"def"},
{"l":"grapple/json/rpc/JsonRpcIdentifier$.html","n":"apply","t":"def apply(id: Long): JsonRpcIdentifier","d":"grapple/json/rpc/JsonRpcIdentifier$","k":"def"},
{"l":"grapple/json/rpc/JsonRpcIdentifier$.html","n":"nullified","t":"def nullified: JsonRpcIdentifier","d":"grapple/json/rpc/JsonRpcIdentifier$","k":"def"},
{"l":"grapple/json/rpc/JsonRpcMessage.html","n":"JsonRpcMessage","t":"trait JsonRpcMessage","d":"grapple/json/rpc/JsonRpcMessage","k":"trait"},
{"l":"grapple/json/rpc/JsonRpcMessage.html","n":"attribute","t":"def attribute[T](name: String): T","d":"grapple/json/rpc/JsonRpcMessage","k":"def"},
{"l":"grapple/json/rpc/JsonRpcMessage.html","n":"attributes","t":"def attributes: Map[String, Any]","d":"grapple/json/rpc/JsonRpcMessage","k":"def"},
{"l":"grapple/json/rpc/JsonRpcMessage.html","n":"getAttribute","t":"def getAttribute[T](name: String): Option[T]","d":"grapple/json/rpc/JsonRpcMessage","k":"def"},
{"l":"grapple/json/rpc/JsonRpcMessage.html","n":"getAttributeOrElse","t":"def getAttributeOrElse[T](name: String, default: => T): T","d":"grapple/json/rpc/JsonRpcMessage","k":"def"},
{"l":"grapple/json/rpc/JsonRpcMessage.html","n":"id","t":"def id: JsonRpcIdentifier","d":"grapple/json/rpc/JsonRpcMessage","k":"def"},
{"l":"grapple/json/rpc/JsonRpcMessage.html","n":"version","t":"def version: String","d":"grapple/json/rpc/JsonRpcMessage","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest.html","n":"JsonRpcRequest","t":"trait JsonRpcRequest extends JsonRpcMessage","d":"grapple/json/rpc/JsonRpcRequest","k":"trait"},
{"l":"grapple/json/rpc/JsonRpcRequest.html","n":"isNotification","t":"def isNotification: Boolean","d":"grapple/json/rpc/JsonRpcRequest","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest.html","n":"method","t":"def method: String","d":"grapple/json/rpc/JsonRpcRequest","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest.html","n":"params","t":"def params: Option[JsonValue]","d":"grapple/json/rpc/JsonRpcRequest","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest.html","n":"putAttribute","t":"def putAttribute(name: String, value: Any): JsonRpcRequest","d":"grapple/json/rpc/JsonRpcRequest","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest.html","n":"removeAttribute","t":"def removeAttribute(name: String): JsonRpcRequest","d":"grapple/json/rpc/JsonRpcRequest","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest.html","n":"setAttributes","t":"def setAttributes(attributes: Map[String, Any]): JsonRpcRequest","d":"grapple/json/rpc/JsonRpcRequest","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest$.html","n":"JsonRpcRequest","t":"object JsonRpcRequest","d":"grapple/json/rpc/JsonRpcRequest$","k":"object"},
{"l":"grapple/json/rpc/JsonRpcRequest$.html","n":"apply","t":"def apply(version: String, method: String, params: Option[JsonValue]): JsonRpcRequest","d":"grapple/json/rpc/JsonRpcRequest$","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest$.html","n":"apply","t":"def apply(version: String, id: JsonRpcIdentifier, method: String, params: Option[JsonValue]): JsonRpcRequest","d":"grapple/json/rpc/JsonRpcRequest$","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest$.html","n":"builder","t":"def builder(): Builder","d":"grapple/json/rpc/JsonRpcRequest$","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest$$Builder.html","n":"Builder","t":"class Builder","d":"grapple/json/rpc/JsonRpcRequest$$Builder","k":"class"},
{"l":"grapple/json/rpc/JsonRpcRequest$$Builder.html","n":"attributes","t":"def attributes(value: Map[String, Any]): Builder","d":"grapple/json/rpc/JsonRpcRequest$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest$$Builder.html","n":"attributes","t":"def attributes(one: (String, Any), more: (String, Any)*): Builder","d":"grapple/json/rpc/JsonRpcRequest$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest$$Builder.html","n":"build","t":"def build(): JsonRpcRequest","d":"grapple/json/rpc/JsonRpcRequest$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest$$Builder.html","n":"id","t":"def id(value: JsonRpcIdentifier): Builder","d":"grapple/json/rpc/JsonRpcRequest$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest$$Builder.html","n":"id","t":"def id(value: String): Builder","d":"grapple/json/rpc/JsonRpcRequest$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest$$Builder.html","n":"id","t":"def id(value: Long): Builder","d":"grapple/json/rpc/JsonRpcRequest$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest$$Builder.html","n":"idNull","t":"def idNull(): Builder","d":"grapple/json/rpc/JsonRpcRequest$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest$$Builder.html","n":"idUndefined","t":"def idUndefined(): Builder","d":"grapple/json/rpc/JsonRpcRequest$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest$$Builder.html","n":"method","t":"def method(value: String): Builder","d":"grapple/json/rpc/JsonRpcRequest$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest$$Builder.html","n":"params","t":"def params(value: Option[JsonValue]): Builder","d":"grapple/json/rpc/JsonRpcRequest$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest$$Builder.html","n":"params","t":"def params(value: JsonValue): Builder","d":"grapple/json/rpc/JsonRpcRequest$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcRequest$$Builder.html","n":"version","t":"def version(value: String): Builder","d":"grapple/json/rpc/JsonRpcRequest$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse.html","n":"JsonRpcResponse","t":"trait JsonRpcResponse extends JsonRpcMessage","d":"grapple/json/rpc/JsonRpcResponse","k":"trait"},
{"l":"grapple/json/rpc/JsonRpcResponse.html","n":"error","t":"def error: JsonRpcError","d":"grapple/json/rpc/JsonRpcResponse","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse.html","n":"isError","t":"def isError: Boolean","d":"grapple/json/rpc/JsonRpcResponse","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse.html","n":"isResult","t":"def isResult: Boolean","d":"grapple/json/rpc/JsonRpcResponse","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse.html","n":"putAttribute","t":"def putAttribute(name: String, value: Any): JsonRpcResponse","d":"grapple/json/rpc/JsonRpcResponse","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse.html","n":"removeAttribute","t":"def removeAttribute(name: String): JsonRpcResponse","d":"grapple/json/rpc/JsonRpcResponse","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse.html","n":"result","t":"def result: JsonValue","d":"grapple/json/rpc/JsonRpcResponse","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse.html","n":"setAttributes","t":"def setAttributes(attributes: Map[String, Any]): JsonRpcResponse","d":"grapple/json/rpc/JsonRpcResponse","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$.html","n":"JsonRpcResponse","t":"object JsonRpcResponse","d":"grapple/json/rpc/JsonRpcResponse$","k":"object"},
{"l":"grapple/json/rpc/JsonRpcResponse$.html","n":"apply","t":"def apply(version: String, id: JsonRpcIdentifier, result: JsonValue): JsonRpcResponse","d":"grapple/json/rpc/JsonRpcResponse$","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$.html","n":"apply","t":"def apply(version: String, id: JsonRpcIdentifier, error: JsonRpcError): JsonRpcResponse","d":"grapple/json/rpc/JsonRpcResponse$","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$.html","n":"builder","t":"def builder(): Builder","d":"grapple/json/rpc/JsonRpcResponse$","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$$Builder.html","n":"Builder","t":"class Builder","d":"grapple/json/rpc/JsonRpcResponse$$Builder","k":"class"},
{"l":"grapple/json/rpc/JsonRpcResponse$$Builder.html","n":"attributes","t":"def attributes(value: Map[String, Any]): Builder","d":"grapple/json/rpc/JsonRpcResponse$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$$Builder.html","n":"attributes","t":"def attributes(one: (String, Any), more: (String, Any)*): Builder","d":"grapple/json/rpc/JsonRpcResponse$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$$Builder.html","n":"build","t":"def build(): JsonRpcResponse","d":"grapple/json/rpc/JsonRpcResponse$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$$Builder.html","n":"error","t":"def error(value: JsonRpcError): Builder","d":"grapple/json/rpc/JsonRpcResponse$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$$Builder.html","n":"error","t":"def error(code: Int, message: String, data: Option[JsonValue]): Builder","d":"grapple/json/rpc/JsonRpcResponse$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$$Builder.html","n":"error","t":"def error(code: Int, message: String, data: JsonValue): Builder","d":"grapple/json/rpc/JsonRpcResponse$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$$Builder.html","n":"id","t":"def id(value: JsonRpcIdentifier): Builder","d":"grapple/json/rpc/JsonRpcResponse$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$$Builder.html","n":"id","t":"def id(value: String): Builder","d":"grapple/json/rpc/JsonRpcResponse$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$$Builder.html","n":"id","t":"def id(value: Long): Builder","d":"grapple/json/rpc/JsonRpcResponse$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$$Builder.html","n":"idNull","t":"def idNull(): Builder","d":"grapple/json/rpc/JsonRpcResponse$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$$Builder.html","n":"result","t":"def result(value: JsonValue): Builder","d":"grapple/json/rpc/JsonRpcResponse$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$$Builder.html","n":"resultOrError","t":"def resultOrError(value: JsonValue | JsonRpcError): Builder","d":"grapple/json/rpc/JsonRpcResponse$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$$Builder.html","n":"tryResult","t":"def tryResult(value: => JsonValue)(using onFailure: PartialFunction[Throwable, JsonRpcError]): Builder","d":"grapple/json/rpc/JsonRpcResponse$$Builder","k":"def"},
{"l":"grapple/json/rpc/JsonRpcResponse$$Builder.html","n":"version","t":"def version(value: String): Builder","d":"grapple/json/rpc/JsonRpcResponse$$Builder","k":"def"},
{"l":"grapple/json/rpc/MethodNotFound.html","n":"MethodNotFound","t":"class MethodNotFound extends JsonRpcError","d":"grapple/json/rpc/MethodNotFound","k":"class"},
{"l":"grapple/json/rpc/MethodNotFound$.html","n":"MethodNotFound","t":"object MethodNotFound","d":"grapple/json/rpc/MethodNotFound$","k":"object"},
{"l":"grapple/json/rpc/MethodNotFound$.html","n":"apply","t":"def apply(): MethodNotFound","d":"grapple/json/rpc/MethodNotFound$","k":"def"},
{"l":"grapple/json/rpc/MethodNotFound$.html","n":"apply","t":"def apply(data: String): MethodNotFound","d":"grapple/json/rpc/MethodNotFound$","k":"def"},
{"l":"grapple/json/rpc/MethodNotFound$.html","n":"apply","t":"def apply(data: JsonValue): MethodNotFound","d":"grapple/json/rpc/MethodNotFound$","k":"def"},
{"l":"grapple/json/rpc/MethodNotFound$.html","n":"apply","t":"def apply(data: Option[JsonValue]): MethodNotFound","d":"grapple/json/rpc/MethodNotFound$","k":"def"},
{"l":"grapple/json/rpc/MethodNotFound$.html","n":"unapply","t":"def unapply(error: MethodNotFound): Option[(Int, String, Option[JsonValue])]","d":"grapple/json/rpc/MethodNotFound$","k":"def"},
{"l":"grapple/json/rpc/ParseError.html","n":"ParseError","t":"class ParseError extends JsonRpcError","d":"grapple/json/rpc/ParseError","k":"class"},
{"l":"grapple/json/rpc/ParseError$.html","n":"ParseError","t":"object ParseError","d":"grapple/json/rpc/ParseError$","k":"object"},
{"l":"grapple/json/rpc/ParseError$.html","n":"apply","t":"def apply(): ParseError","d":"grapple/json/rpc/ParseError$","k":"def"},
{"l":"grapple/json/rpc/ParseError$.html","n":"apply","t":"def apply(data: String): ParseError","d":"grapple/json/rpc/ParseError$","k":"def"},
{"l":"grapple/json/rpc/ParseError$.html","n":"apply","t":"def apply(data: JsonValue): ParseError","d":"grapple/json/rpc/ParseError$","k":"def"},
{"l":"grapple/json/rpc/ParseError$.html","n":"apply","t":"def apply(data: Option[JsonValue]): ParseError","d":"grapple/json/rpc/ParseError$","k":"def"},
{"l":"grapple/json/rpc/ParseError$.html","n":"unapply","t":"def unapply(error: ParseError): Option[(Int, String, Option[JsonValue])]","d":"grapple/json/rpc/ParseError$","k":"def"},
{"l":"grapple/json/rpc/jsonRpcErrorToJsonValue$.html","n":"jsonRpcErrorToJsonValue","t":"given jsonRpcErrorToJsonValue: JsonOutput[JsonRpcError]","d":"grapple/json/rpc/jsonRpcErrorToJsonValue$","k":"given"},
{"l":"grapple/json/rpc/jsonRpcErrorToJsonValue$.html","n":"write","t":"def write(error: JsonRpcError): JsonValue","d":"grapple/json/rpc/jsonRpcErrorToJsonValue$","k":"def"},
{"l":"grapple/json/rpc/jsonRpcIdentifierToJsonValue$.html","n":"jsonRpcIdentifierToJsonValue","t":"given jsonRpcIdentifierToJsonValue: JsonOutput[JsonRpcIdentifier]","d":"grapple/json/rpc/jsonRpcIdentifierToJsonValue$","k":"given"},
{"l":"grapple/json/rpc/jsonRpcIdentifierToJsonValue$.html","n":"write","t":"def write(id: JsonRpcIdentifier): JsonValue","d":"grapple/json/rpc/jsonRpcIdentifierToJsonValue$","k":"def"},
{"l":"grapple/json/rpc/jsonRpcRequestToJsonValue$.html","n":"jsonRpcRequestToJsonValue","t":"given jsonRpcRequestToJsonValue: JsonOutput[JsonRpcRequest]","d":"grapple/json/rpc/jsonRpcRequestToJsonValue$","k":"given"},
{"l":"grapple/json/rpc/jsonRpcRequestToJsonValue$.html","n":"write","t":"def write(request: JsonRpcRequest): JsonValue","d":"grapple/json/rpc/jsonRpcRequestToJsonValue$","k":"def"},
{"l":"grapple/json/rpc/jsonRpcResponseToJsonValue$.html","n":"jsonRpcResponseToJsonValue","t":"given jsonRpcResponseToJsonValue: JsonOutput[JsonRpcResponse]","d":"grapple/json/rpc/jsonRpcResponseToJsonValue$","k":"given"},
{"l":"grapple/json/rpc/jsonRpcResponseToJsonValue$.html","n":"write","t":"def write(response: JsonRpcResponse): JsonValue","d":"grapple/json/rpc/jsonRpcResponseToJsonValue$","k":"def"},
{"l":"grapple/json/rpc/jsonValueToJsonRpcError$.html","n":"jsonValueToJsonRpcError","t":"given jsonValueToJsonRpcError: JsonInput[JsonRpcError]","d":"grapple/json/rpc/jsonValueToJsonRpcError$","k":"given"},
{"l":"grapple/json/rpc/jsonValueToJsonRpcError$.html","n":"read","t":"def read(json: JsonValue): JsonRpcError","d":"grapple/json/rpc/jsonValueToJsonRpcError$","k":"def"},
{"l":"grapple/json/rpc/jsonValueToJsonRpcIdentifier$.html","n":"jsonValueToJsonRpcIdentifier","t":"given jsonValueToJsonRpcIdentifier: JsonInput[JsonRpcIdentifier]","d":"grapple/json/rpc/jsonValueToJsonRpcIdentifier$","k":"given"},
{"l":"grapple/json/rpc/jsonValueToJsonRpcIdentifier$.html","n":"read","t":"def read(json: JsonValue): JsonRpcIdentifier","d":"grapple/json/rpc/jsonValueToJsonRpcIdentifier$","k":"def"},
{"l":"grapple/json/rpc/jsonValueToJsonRpcRequest$.html","n":"jsonValueToJsonRpcRequest","t":"given jsonValueToJsonRpcRequest: JsonInput[JsonRpcRequest]","d":"grapple/json/rpc/jsonValueToJsonRpcRequest$","k":"given"},
{"l":"grapple/json/rpc/jsonValueToJsonRpcRequest$.html","n":"read","t":"def read(json: JsonValue): JsonRpcRequest","d":"grapple/json/rpc/jsonValueToJsonRpcRequest$","k":"def"},
{"l":"grapple/json/rpc/jsonValueToJsonRpcResponse$.html","n":"jsonValueToJsonRpcResponse","t":"given jsonValueToJsonRpcResponse: JsonInput[JsonRpcResponse]","d":"grapple/json/rpc/jsonValueToJsonRpcResponse$","k":"given"},
{"l":"grapple/json/rpc/jsonValueToJsonRpcResponse$.html","n":"read","t":"def read(json: JsonValue): JsonRpcResponse","d":"grapple/json/rpc/jsonValueToJsonRpcResponse$","k":"def"},
{"l":"docs/index.html","n":"Grapple","t":"Grapple","d":"","k":"static"}];