pages = [{"l":"index.html#","e":false,"i":"","n":"Grapple","t":"Grapple","d":"","k":"static","x":""},
{"l":"grapple/json.html#","e":false,"i":"","n":"grapple.json","t":"grapple.json","d":"","k":"package","x":""},
{"l":"grapple/json.html#\\-ffffffa9","e":false,"i":"extension (json: JsonValue)","n":"\\","t":"\\(name: String): JsonValue","d":"grapple.json","k":"def","x":""},
{"l":"grapple/json.html#\\-fa7","e":false,"i":"extension (json: JsonValue)","n":"\\","t":"\\(index: Int): JsonValue","d":"grapple.json","k":"def","x":""},
{"l":"grapple/json.html#\\\\-92","e":false,"i":"extension (json: JsonValue)","n":"\\\\","t":"\\\\(name: String): Seq[JsonValue]","d":"grapple.json","k":"def","x":""},
{"l":"grapple/json.html#arrayToJsonArray-fffff871","e":false,"i":"","n":"arrayToJsonArray","t":"arrayToJsonArray[T](using converter: JsonOutput[T]): JsonOutput[Array[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#bigDecimalToJsonNumber-0","e":false,"i":"","n":"bigDecimalToJsonNumber","t":"bigDecimalToJsonNumber: JsonOutput[BigDecimal]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#bigIntToJsonNumber-0","e":false,"i":"","n":"bigIntToJsonNumber","t":"bigIntToJsonNumber: JsonOutput[BigInt]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#booleanToJsonBoolean-0","e":false,"i":"","n":"booleanToJsonBoolean","t":"booleanToJsonBoolean: JsonOutput[Boolean]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#byteToJsonNumber-0","e":false,"i":"","n":"byteToJsonNumber","t":"byteToJsonNumber: JsonOutput[Byte]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#doubleToJsonNumber-0","e":false,"i":"","n":"doubleToJsonNumber","t":"doubleToJsonNumber: JsonOutput[Double]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#eitherToJsonValue-fffffbfd","e":false,"i":"","n":"eitherToJsonValue","t":"eitherToJsonValue[A, B, M <: (Either)](using left: JsonOutput[A])(using right: JsonOutput[B]): JsonOutput[M[A, B]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#failureToJsonNull-0","e":false,"i":"","n":"failureToJsonNull","t":"failureToJsonNull: JsonOutput[Failure[_]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#floatToJsonNumber-0","e":false,"i":"","n":"floatToJsonNumber","t":"floatToJsonNumber: JsonOutput[Float]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#intToJsonNumber-0","e":false,"i":"","n":"intToJsonNumber","t":"intToJsonNumber: JsonOutput[Int]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#iterableToJsonArray-eb2","e":false,"i":"","n":"iterableToJsonArray","t":"iterableToJsonArray[T, M <: (Iterable)](using converter: JsonOutput[T]): JsonOutput[M[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonInputConversion-fffff4ea","e":false,"i":"","n":"jsonInputConversion","t":"jsonInputConversion[T](using converter: JsonInput[T]): Conversion[JsonValue, T]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonOutputConversion-bdd","e":false,"i":"","n":"jsonOutputConversion","t":"jsonOutputConversion[T](using converter: JsonOutput[T]): Conversion[T, JsonValue]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToBigDecimal-0","e":false,"i":"","n":"jsonValueToBigDecimal","t":"jsonValueToBigDecimal: JsonInput[BigDecimal]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToBigInt-0","e":false,"i":"","n":"jsonValueToBigInt","t":"jsonValueToBigInt: JsonInput[BigInt]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToBoolean-0","e":false,"i":"","n":"jsonValueToBoolean","t":"jsonValueToBoolean: JsonInput[Boolean]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToByte-0","e":false,"i":"","n":"jsonValueToByte","t":"jsonValueToByte: JsonInput[Byte]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToCollection-fffff2ea","e":false,"i":"","n":"jsonValueToCollection","t":"jsonValueToCollection[T, M[T]](using converter: JsonInput[T])(using factory: Factory[T, M[T]]): JsonInput[M[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToDouble-0","e":false,"i":"","n":"jsonValueToDouble","t":"jsonValueToDouble: JsonInput[Double]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToEither-fffff2c3","e":false,"i":"","n":"jsonValueToEither","t":"jsonValueToEither[A, B](using left: JsonInput[A])(using right: JsonInput[B]): JsonInput[Either[A, B]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToFloat-0","e":false,"i":"","n":"jsonValueToFloat","t":"jsonValueToFloat: JsonInput[Float]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToInt-0","e":false,"i":"","n":"jsonValueToInt","t":"jsonValueToInt: JsonInput[Int]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToJsonArray-0","e":false,"i":"","n":"jsonValueToJsonArray","t":"jsonValueToJsonArray: JsonInput[JsonArray]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToJsonBoolean-0","e":false,"i":"","n":"jsonValueToJsonBoolean","t":"jsonValueToJsonBoolean: JsonInput[JsonBoolean]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToJsonNull-0","e":false,"i":"","n":"jsonValueToJsonNull","t":"jsonValueToJsonNull: JsonInput[JsonNull.type]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToJsonNumber-0","e":false,"i":"","n":"jsonValueToJsonNumber","t":"jsonValueToJsonNumber: JsonInput[JsonNumber]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToJsonObject-0","e":false,"i":"","n":"jsonValueToJsonObject","t":"jsonValueToJsonObject: JsonInput[JsonObject]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToJsonString-0","e":false,"i":"","n":"jsonValueToJsonString","t":"jsonValueToJsonString: JsonInput[JsonString]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToJsonValue-0","e":false,"i":"","n":"jsonValueToJsonValue","t":"jsonValueToJsonValue: JsonInput[JsonValue]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToLong-0","e":false,"i":"","n":"jsonValueToLong","t":"jsonValueToLong: JsonInput[Long]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToOption-fffff5a7","e":false,"i":"","n":"jsonValueToOption","t":"jsonValueToOption[T](using converter: JsonInput[T]): JsonInput[Option[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToShort-0","e":false,"i":"","n":"jsonValueToShort","t":"jsonValueToShort: JsonInput[Short]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToString-0","e":false,"i":"","n":"jsonValueToString","t":"jsonValueToString: JsonInput[String]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#jsonValueToTry-fffff5a7","e":false,"i":"","n":"jsonValueToTry","t":"jsonValueToTry[T](using converter: JsonInput[T]): JsonInput[Try[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#leftToJsonValue-fffff871","e":false,"i":"","n":"leftToJsonValue","t":"leftToJsonValue[T](using converter: JsonOutput[T]): JsonOutput[Left[T, _]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#longToJsonNumber-0","e":false,"i":"","n":"longToJsonNumber","t":"longToJsonNumber: JsonOutput[Long]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#mapToJsonObject-eb2","e":false,"i":"","n":"mapToJsonObject","t":"mapToJsonObject[T, M <: ([T] =>> Map[String, T])](using converter: JsonOutput[T]): JsonOutput[M[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#noneToJsonNull-0","e":false,"i":"","n":"noneToJsonNull","t":"noneToJsonNull: JsonOutput[None.type]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#optionToJsonValue-eb2","e":false,"i":"","n":"optionToJsonValue","t":"optionToJsonValue[T, M <: (Option)](using converter: JsonOutput[T]): JsonOutput[M[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#rightToJsonValue-fffff871","e":false,"i":"","n":"rightToJsonValue","t":"rightToJsonValue[T](using converter: JsonOutput[T]): JsonOutput[Right[_, T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#shortToJsonNumber-0","e":false,"i":"","n":"shortToJsonNumber","t":"shortToJsonNumber: JsonOutput[Short]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#stringToJsonString-0","e":false,"i":"","n":"stringToJsonString","t":"stringToJsonString: JsonOutput[String]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#toJsonArrayConversion-179","e":false,"i":"","n":"toJsonArrayConversion","t":"toJsonArrayConversion(using converter: JsonInput[JsonArray]): Conversion[JsonValue, JsonArray]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#toJsonObjectConversion-179","e":false,"i":"","n":"toJsonObjectConversion","t":"toJsonObjectConversion(using converter: JsonInput[JsonObject]): Conversion[JsonValue, JsonObject]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#tryToJsonValue-eb2","e":false,"i":"","n":"tryToJsonValue","t":"tryToJsonValue[T, M <: (Try)](using converter: JsonOutput[T]): JsonOutput[M[T]]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json.html#tupleToJsonField-bdd","e":false,"i":"","n":"tupleToJsonField","t":"tupleToJsonField[T](using converter: JsonOutput[T]): Conversion[(String, T), (String, JsonValue)]","d":"grapple.json","k":"given","x":""},
{"l":"grapple/json/rpc.html#","e":false,"i":"","n":"grapple.json.rpc","t":"grapple.json.rpc","d":"","k":"package","x":""},
{"l":"grapple/json/rpc.html#defaultOnFailure-0","e":false,"i":"","n":"defaultOnFailure","t":"defaultOnFailure: PartialFunction[Throwable, JsonRpcError]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc.html#jsonRpcErrorToJsonValue-0","e":false,"i":"","n":"jsonRpcErrorToJsonValue","t":"jsonRpcErrorToJsonValue: JsonOutput[JsonRpcError]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc.html#jsonRpcIdentifierToJsonValue-0","e":false,"i":"","n":"jsonRpcIdentifierToJsonValue","t":"jsonRpcIdentifierToJsonValue: JsonOutput[JsonRpcIdentifier]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc.html#jsonRpcRequestToJsonValue-0","e":false,"i":"","n":"jsonRpcRequestToJsonValue","t":"jsonRpcRequestToJsonValue: JsonOutput[JsonRpcRequest]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc.html#jsonRpcResponseToJsonValue-0","e":false,"i":"","n":"jsonRpcResponseToJsonValue","t":"jsonRpcResponseToJsonValue: JsonOutput[JsonRpcResponse]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc.html#jsonValueToJsonRpcError-0","e":false,"i":"","n":"jsonValueToJsonRpcError","t":"jsonValueToJsonRpcError: JsonInput[JsonRpcError]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc.html#jsonValueToJsonRpcIdentifier-0","e":false,"i":"","n":"jsonValueToJsonRpcIdentifier","t":"jsonValueToJsonRpcIdentifier: JsonInput[JsonRpcIdentifier]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc.html#jsonValueToJsonRpcRequest-0","e":false,"i":"","n":"jsonValueToJsonRpcRequest","t":"jsonValueToJsonRpcRequest: JsonInput[JsonRpcRequest]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc.html#jsonValueToJsonRpcResponse-0","e":false,"i":"","n":"jsonValueToJsonRpcResponse","t":"jsonValueToJsonRpcResponse: JsonInput[JsonRpcResponse]","d":"grapple.json.rpc","k":"given","x":""},
{"l":"grapple/json/rpc/InternalError.html#","e":false,"i":"","n":"InternalError","t":"InternalError extends JsonRpcError","d":"grapple.json.rpc","k":"class","x":""},
{"l":"grapple/json/rpc/InternalError$.html#","e":false,"i":"","n":"InternalError","t":"InternalError","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/InternalError$.html#apply-cdb","e":false,"i":"","n":"apply","t":"apply(): InternalError","d":"grapple.json.rpc.InternalError","k":"def","x":""},
{"l":"grapple/json/rpc/InternalError$.html#apply-480","e":false,"i":"","n":"apply","t":"apply(data: String): InternalError","d":"grapple.json.rpc.InternalError","k":"def","x":""},
{"l":"grapple/json/rpc/InternalError$.html#apply-ffffff9d","e":false,"i":"","n":"apply","t":"apply(data: JsonValue): InternalError","d":"grapple.json.rpc.InternalError","k":"def","x":""},
{"l":"grapple/json/rpc/InternalError$.html#apply-a58","e":false,"i":"","n":"apply","t":"apply(data: Option[JsonValue]): InternalError","d":"grapple.json.rpc.InternalError","k":"def","x":""},
{"l":"grapple/json/rpc/InternalError$.html#unapply-fffff298","e":false,"i":"","n":"unapply","t":"unapply(error: InternalError): Option[(Int, String, Option[JsonValue])]","d":"grapple.json.rpc.InternalError","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidParams.html#","e":false,"i":"","n":"InvalidParams","t":"InvalidParams extends JsonRpcError","d":"grapple.json.rpc","k":"class","x":""},
{"l":"grapple/json/rpc/InvalidParams$.html#","e":false,"i":"","n":"InvalidParams","t":"InvalidParams","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/InvalidParams$.html#apply-fffff5ed","e":false,"i":"","n":"apply","t":"apply(): InvalidParams","d":"grapple.json.rpc.InvalidParams","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidParams$.html#apply-fffffd92","e":false,"i":"","n":"apply","t":"apply(data: String): InvalidParams","d":"grapple.json.rpc.InvalidParams","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidParams$.html#apply-fffff8af","e":false,"i":"","n":"apply","t":"apply(data: JsonValue): InvalidParams","d":"grapple.json.rpc.InvalidParams","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidParams$.html#apply-fffff36a","e":false,"i":"","n":"apply","t":"apply(data: Option[JsonValue]): InvalidParams","d":"grapple.json.rpc.InvalidParams","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidParams$.html#unapply-aa","e":false,"i":"","n":"unapply","t":"unapply(error: InvalidParams): Option[(Int, String, Option[JsonValue])]","d":"grapple.json.rpc.InvalidParams","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidRequest.html#","e":false,"i":"","n":"InvalidRequest","t":"InvalidRequest extends JsonRpcError","d":"grapple.json.rpc","k":"class","x":""},
{"l":"grapple/json/rpc/InvalidRequest$.html#","e":false,"i":"","n":"InvalidRequest","t":"InvalidRequest","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/InvalidRequest$.html#apply-308","e":false,"i":"","n":"apply","t":"apply(): InvalidRequest","d":"grapple.json.rpc.InvalidRequest","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidRequest$.html#apply-3","e":false,"i":"","n":"apply","t":"apply(data: String): InvalidRequest","d":"grapple.json.rpc.InvalidRequest","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidRequest$.html#apply-886","e":false,"i":"","n":"apply","t":"apply(data: JsonValue): InvalidRequest","d":"grapple.json.rpc.InvalidRequest","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidRequest$.html#apply-52b","e":false,"i":"","n":"apply","t":"apply(data: Option[JsonValue]): InvalidRequest","d":"grapple.json.rpc.InvalidRequest","k":"def","x":""},
{"l":"grapple/json/rpc/InvalidRequest$.html#unapply-fffffd45","e":false,"i":"","n":"unapply","t":"unapply(error: InvalidRequest): Option[(Int, String, Option[JsonValue])]","d":"grapple.json.rpc.InvalidRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#","e":false,"i":"","n":"JsonRpcError","t":"JsonRpcError extends JsonException","d":"grapple.json.rpc","k":"class","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#code-0","e":false,"i":"","n":"code","t":"code: Int","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#data-0","e":false,"i":"","n":"data","t":"data: Option[JsonValue]","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#isInternalError-0","e":false,"i":"","n":"isInternalError","t":"isInternalError: Boolean","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#isInvalidParams-0","e":false,"i":"","n":"isInvalidParams","t":"isInvalidParams: Boolean","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#isInvalidRequest-0","e":false,"i":"","n":"isInvalidRequest","t":"isInvalidRequest: Boolean","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#isMethodNotFound-0","e":false,"i":"","n":"isMethodNotFound","t":"isMethodNotFound: Boolean","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#isParseError-0","e":false,"i":"","n":"isParseError","t":"isParseError: Boolean","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#isServerError-0","e":false,"i":"","n":"isServerError","t":"isServerError: Boolean","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError.html#message-0","e":false,"i":"","n":"message","t":"message: String","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError$.html#","e":false,"i":"","n":"JsonRpcError","t":"JsonRpcError","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/JsonRpcError$.html#apply-68f","e":false,"i":"","n":"apply","t":"apply(code: Int, message: String): JsonRpcError","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError$.html#apply-fffff48d","e":false,"i":"","n":"apply","t":"apply(code: Int, message: String, data: JsonValue): JsonRpcError","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError$.html#apply-fffff772","e":false,"i":"","n":"apply","t":"apply(code: Int, message: String, data: Option[JsonValue]): JsonRpcError","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcError$.html#unapply-858","e":false,"i":"","n":"unapply","t":"unapply(error: JsonRpcError): Option[(Int, String, Option[JsonValue])]","d":"grapple.json.rpc.JsonRpcError","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html#","e":false,"i":"","n":"JsonRpcIdentifier","t":"JsonRpcIdentifier","d":"grapple.json.rpc","k":"trait","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html#isNull-0","e":false,"i":"","n":"isNull","t":"isNull: Boolean","d":"grapple.json.rpc.JsonRpcIdentifier","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html#isNumber-0","e":false,"i":"","n":"isNumber","t":"isNumber: Boolean","d":"grapple.json.rpc.JsonRpcIdentifier","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html#isString-0","e":false,"i":"","n":"isString","t":"isString: Boolean","d":"grapple.json.rpc.JsonRpcIdentifier","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html#numberValue-0","e":false,"i":"","n":"numberValue","t":"numberValue: Long","d":"grapple.json.rpc.JsonRpcIdentifier","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier.html#stringValue-0","e":false,"i":"","n":"stringValue","t":"stringValue: String","d":"grapple.json.rpc.JsonRpcIdentifier","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier$.html#","e":false,"i":"","n":"JsonRpcIdentifier","t":"JsonRpcIdentifier","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier$.html#apply-d1b","e":false,"i":"","n":"apply","t":"apply(id: String): JsonRpcIdentifier","d":"grapple.json.rpc.JsonRpcIdentifier","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier$.html#apply-53a","e":false,"i":"","n":"apply","t":"apply(id: Long): JsonRpcIdentifier","d":"grapple.json.rpc.JsonRpcIdentifier","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcIdentifier$.html#nullified-0","e":false,"i":"","n":"nullified","t":"nullified: JsonRpcIdentifier","d":"grapple.json.rpc.JsonRpcIdentifier","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcMessage.html#","e":false,"i":"","n":"JsonRpcMessage","t":"JsonRpcMessage","d":"grapple.json.rpc","k":"trait","x":""},
{"l":"grapple/json/rpc/JsonRpcMessage.html#attribute-229","e":false,"i":"","n":"attribute","t":"attribute[T](name: String): T","d":"grapple.json.rpc.JsonRpcMessage","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcMessage.html#attributes-0","e":false,"i":"","n":"attributes","t":"attributes: Map[String, Any]","d":"grapple.json.rpc.JsonRpcMessage","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcMessage.html#getAttribute-fffff9d3","e":false,"i":"","n":"getAttribute","t":"getAttribute[T](name: String): Option[T]","d":"grapple.json.rpc.JsonRpcMessage","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcMessage.html#getAttributeOrElse-6cd","e":false,"i":"","n":"getAttributeOrElse","t":"getAttributeOrElse[T](name: String, default: => T): T","d":"grapple.json.rpc.JsonRpcMessage","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcMessage.html#id-0","e":false,"i":"","n":"id","t":"id: JsonRpcIdentifier","d":"grapple.json.rpc.JsonRpcMessage","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcMessage.html#version-0","e":false,"i":"","n":"version","t":"version: String","d":"grapple.json.rpc.JsonRpcMessage","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest.html#","e":false,"i":"","n":"JsonRpcRequest","t":"JsonRpcRequest extends JsonRpcMessage","d":"grapple.json.rpc","k":"trait","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest.html#isNotification-0","e":false,"i":"","n":"isNotification","t":"isNotification: Boolean","d":"grapple.json.rpc.JsonRpcRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest.html#method-0","e":false,"i":"","n":"method","t":"method: String","d":"grapple.json.rpc.JsonRpcRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest.html#params-0","e":false,"i":"","n":"params","t":"params: Option[JsonValue]","d":"grapple.json.rpc.JsonRpcRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest.html#putAttribute-fffff56a","e":false,"i":"","n":"putAttribute","t":"putAttribute(name: String, value: Any): JsonRpcRequest","d":"grapple.json.rpc.JsonRpcRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest.html#removeAttribute-75d","e":false,"i":"","n":"removeAttribute","t":"removeAttribute(name: String): JsonRpcRequest","d":"grapple.json.rpc.JsonRpcRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest.html#setAttributes-fffff23a","e":false,"i":"","n":"setAttributes","t":"setAttributes(attributes: Map[String, Any]): JsonRpcRequest","d":"grapple.json.rpc.JsonRpcRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest$.html#","e":false,"i":"","n":"JsonRpcRequest","t":"JsonRpcRequest","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest$.html#apply-ffffff7b","e":false,"i":"","n":"apply","t":"apply(version: String, method: String, params: Option[JsonValue]): JsonRpcRequest","d":"grapple.json.rpc.JsonRpcRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequest$.html#apply-f05","e":false,"i":"","n":"apply","t":"apply(version: String, id: JsonRpcIdentifier, method: String, params: Option[JsonValue]): JsonRpcRequest","d":"grapple.json.rpc.JsonRpcRequest","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#","e":false,"i":"","n":"JsonRpcRequestBuilder","t":"JsonRpcRequestBuilder","d":"grapple.json.rpc","k":"class","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#attributes-fffff001","e":false,"i":"","n":"attributes","t":"attributes(value: Map[String, Any]): JsonRpcRequestBuilder.this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#attributes-fffff2f6","e":false,"i":"","n":"attributes","t":"attributes(one: (String, Any), more: (String, Any)*): JsonRpcRequestBuilder.this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#id-fffff24f","e":false,"i":"","n":"id","t":"id(value: JsonRpcIdentifier): JsonRpcRequestBuilder.this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#id-fffffd7e","e":false,"i":"","n":"id","t":"id(value: String): JsonRpcRequestBuilder.this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#id-fffffe1d","e":false,"i":"","n":"id","t":"id(value: Long): JsonRpcRequestBuilder.this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#idNull-ad9","e":false,"i":"","n":"idNull","t":"idNull(): JsonRpcRequestBuilder.this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#idUndefined-ad9","e":false,"i":"","n":"idUndefined","t":"idUndefined(): JsonRpcRequestBuilder.this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#method-fffffd7e","e":false,"i":"","n":"method","t":"method(value: String): JsonRpcRequestBuilder.this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#params-fffffb56","e":false,"i":"","n":"params","t":"params(value: Option[JsonValue]): JsonRpcRequestBuilder.this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#params-b9b","e":false,"i":"","n":"params","t":"params(value: JsonValue): JsonRpcRequestBuilder.this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#toJsonRpcRequest-fffffa62","e":false,"i":"","n":"toJsonRpcRequest","t":"toJsonRpcRequest(): JsonRpcRequest","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcRequestBuilder.html#version-fffffd7e","e":false,"i":"","n":"version","t":"version(value: String): JsonRpcRequestBuilder.this.type","d":"grapple.json.rpc.JsonRpcRequestBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse.html#","e":false,"i":"","n":"JsonRpcResponse","t":"JsonRpcResponse extends JsonRpcMessage","d":"grapple.json.rpc","k":"trait","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse.html#error-0","e":false,"i":"","n":"error","t":"error: JsonRpcError","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse.html#isError-0","e":false,"i":"","n":"isError","t":"isError: Boolean","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse.html#isResult-0","e":false,"i":"","n":"isResult","t":"isResult: Boolean","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse.html#putAttribute-fffffcc6","e":false,"i":"","n":"putAttribute","t":"putAttribute(name: String, value: Any): JsonRpcResponse","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse.html#removeAttribute-fffff933","e":false,"i":"","n":"removeAttribute","t":"removeAttribute(name: String): JsonRpcResponse","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse.html#result-0","e":false,"i":"","n":"result","t":"result: JsonValue","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse.html#setAttributes-9f6","e":false,"i":"","n":"setAttributes","t":"setAttributes(attributes: Map[String, Any]): JsonRpcResponse","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse$.html#","e":false,"i":"","n":"JsonRpcResponse","t":"JsonRpcResponse","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse$.html#apply-fffffbeb","e":false,"i":"","n":"apply","t":"apply(version: String, id: JsonRpcIdentifier, result: JsonValue): JsonRpcResponse","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponse$.html#apply-62e","e":false,"i":"","n":"apply","t":"apply(version: String, id: JsonRpcIdentifier, error: JsonRpcError): JsonRpcResponse","d":"grapple.json.rpc.JsonRpcResponse","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#","e":false,"i":"","n":"JsonRpcResponseBuilder","t":"JsonRpcResponseBuilder","d":"grapple.json.rpc","k":"class","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#attributes-cc5","e":false,"i":"","n":"attributes","t":"attributes(value: Map[String, Any]): JsonRpcResponseBuilder.this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#attributes-fffff870","e":false,"i":"","n":"attributes","t":"attributes(one: (String, Any), more: (String, Any)*): JsonRpcResponseBuilder.this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#error-fffff1f2","e":false,"i":"","n":"error","t":"error(value: JsonRpcError): JsonRpcResponseBuilder.this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#error-fffff104","e":false,"i":"","n":"error","t":"error(code: Int, message: String, data: Option[JsonValue]): JsonRpcResponseBuilder.this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#error-85f","e":false,"i":"","n":"error","t":"error(code: Int, message: String, data: JsonValue): JsonRpcResponseBuilder.this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#id-fffff437","e":false,"i":"","n":"id","t":"id(value: JsonRpcIdentifier): JsonRpcResponseBuilder.this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#id-ee8","e":false,"i":"","n":"id","t":"id(value: String): JsonRpcResponseBuilder.this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#id-fffff229","e":false,"i":"","n":"id","t":"id(value: Long): JsonRpcResponseBuilder.this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#idNull-ced","e":false,"i":"","n":"idNull","t":"idNull(): JsonRpcResponseBuilder.this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#result-fffff46b","e":false,"i":"","n":"result","t":"result(value: JsonValue): JsonRpcResponseBuilder.this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#resultOrError-3fa","e":false,"i":"","n":"resultOrError","t":"resultOrError(value: JsonValue | JsonRpcError): JsonRpcResponseBuilder.this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#toJsonRpcResponse-fffff6ce","e":false,"i":"","n":"toJsonRpcResponse","t":"toJsonRpcResponse(): JsonRpcResponse","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#tryResult-ac","e":false,"i":"","n":"tryResult","t":"tryResult(value: => JsonValue)(using onFailure: PartialFunction[Throwable, JsonRpcError]): JsonRpcResponseBuilder.this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/JsonRpcResponseBuilder.html#version-ee8","e":false,"i":"","n":"version","t":"version(value: String): JsonRpcResponseBuilder.this.type","d":"grapple.json.rpc.JsonRpcResponseBuilder","k":"def","x":""},
{"l":"grapple/json/rpc/MethodNotFound.html#","e":false,"i":"","n":"MethodNotFound","t":"MethodNotFound extends JsonRpcError","d":"grapple.json.rpc","k":"class","x":""},
{"l":"grapple/json/rpc/MethodNotFound$.html#","e":false,"i":"","n":"MethodNotFound","t":"MethodNotFound","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/MethodNotFound$.html#apply-fffffae0","e":false,"i":"","n":"apply","t":"apply(): MethodNotFound","d":"grapple.json.rpc.MethodNotFound","k":"def","x":""},
{"l":"grapple/json/rpc/MethodNotFound$.html#apply-fffff7db","e":false,"i":"","n":"apply","t":"apply(data: String): MethodNotFound","d":"grapple.json.rpc.MethodNotFound","k":"def","x":""},
{"l":"grapple/json/rpc/MethodNotFound$.html#apply-fffff05e","e":false,"i":"","n":"apply","t":"apply(data: JsonValue): MethodNotFound","d":"grapple.json.rpc.MethodNotFound","k":"def","x":""},
{"l":"grapple/json/rpc/MethodNotFound$.html#apply-fffffd03","e":false,"i":"","n":"apply","t":"apply(data: Option[JsonValue]): MethodNotFound","d":"grapple.json.rpc.MethodNotFound","k":"def","x":""},
{"l":"grapple/json/rpc/MethodNotFound$.html#unapply-11d","e":false,"i":"","n":"unapply","t":"unapply(error: MethodNotFound): Option[(Int, String, Option[JsonValue])]","d":"grapple.json.rpc.MethodNotFound","k":"def","x":""},
{"l":"grapple/json/rpc/ParseError.html#","e":false,"i":"","n":"ParseError","t":"ParseError extends JsonRpcError","d":"grapple.json.rpc","k":"class","x":""},
{"l":"grapple/json/rpc/ParseError$.html#","e":false,"i":"","n":"ParseError","t":"ParseError","d":"grapple.json.rpc","k":"object","x":""},
{"l":"grapple/json/rpc/ParseError$.html#apply-585","e":false,"i":"","n":"apply","t":"apply(): ParseError","d":"grapple.json.rpc.ParseError","k":"def","x":""},
{"l":"grapple/json/rpc/ParseError$.html#apply-fffff800","e":false,"i":"","n":"apply","t":"apply(data: String): ParseError","d":"grapple.json.rpc.ParseError","k":"def","x":""},
{"l":"grapple/json/rpc/ParseError$.html#apply-a03","e":false,"i":"","n":"apply","t":"apply(data: JsonValue): ParseError","d":"grapple.json.rpc.ParseError","k":"def","x":""},
{"l":"grapple/json/rpc/ParseError$.html#apply-128","e":false,"i":"","n":"apply","t":"apply(data: Option[JsonValue]): ParseError","d":"grapple.json.rpc.ParseError","k":"def","x":""},
{"l":"grapple/json/rpc/ParseError$.html#unapply-c42","e":false,"i":"","n":"unapply","t":"unapply(error: ParseError): Option[(Int, String, Option[JsonValue])]","d":"grapple.json.rpc.ParseError","k":"def","x":""},
{"l":"grapple/json/Json$.html#","e":false,"i":"","n":"Json","t":"Json","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/Json$.html#arr-b15","e":false,"i":"","n":"arr","t":"arr(values: JsonValue*): JsonArray","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#obj-fffff203","e":false,"i":"","n":"obj","t":"obj(fields: (String, JsonValue)*): JsonObject","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#parse-fe9","e":false,"i":"","n":"parse","t":"parse(text: String): JsonStructure","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#parse-fffffb76","e":false,"i":"","n":"parse","t":"parse(bytes: Array[Byte]): JsonStructure","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#parse-fffff6d6","e":false,"i":"","n":"parse","t":"parse(bytes: Array[Byte], offset: Int, length: Int): JsonStructure","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#parse-fffff6e3","e":false,"i":"","n":"parse","t":"parse(input: Reader): JsonStructure","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#parse-fffff492","e":false,"i":"","n":"parse","t":"parse(input: InputStream): JsonStructure","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#parse-55c","e":false,"i":"","n":"parse","t":"parse(input: File): JsonStructure","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#parse-fffff9d5","e":false,"i":"","n":"parse","t":"parse(input: Path): JsonStructure","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#toBytes-fffff774","e":false,"i":"","n":"toBytes","t":"toBytes(value: JsonValue): Array[Byte]","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#toJson-f4e","e":false,"i":"","n":"toJson","t":"toJson[T](value: T)(using converter: JsonOutput[T]): JsonValue","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#toPrettyPrint-fffff4a7","e":false,"i":"","n":"toPrettyPrint","t":"toPrettyPrint(value: JsonValue): String","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/Json$.html#toPrettyPrint-fffffd0c","e":false,"i":"","n":"toPrettyPrint","t":"toPrettyPrint(value: JsonValue, indent: String): String","d":"grapple.json.Json","k":"def","x":""},
{"l":"grapple/json/JsonAdapter.html#","e":false,"i":"","n":"JsonAdapter","t":"JsonAdapter[T] extends JsonInput[T], JsonOutput[T]","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonArray.html#","e":false,"i":"","n":"JsonArray","t":"JsonArray extends JsonStructure","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonArray.html#++-ad4","e":false,"i":"","n":"++","t":"++(suffix: JsonArray): JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#+:-fffff7ec","e":false,"i":"","n":"+:","t":"+:(value: JsonValue): JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#:+-fffff7ec","e":false,"i":"","n":":+","t":":+(value: JsonValue): JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#apply-a29","e":false,"i":"","n":"apply","t":"apply(index: Int): JsonValue","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getBigDecimal-788","e":false,"i":"","n":"getBigDecimal","t":"getBigDecimal(index: Int): BigDecimal","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getBigInt-fa6","e":false,"i":"","n":"getBigInt","t":"getBigInt(index: Int): BigInt","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getBoolean-ffffff99","e":false,"i":"","n":"getBoolean","t":"getBoolean(index: Int): Boolean","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getByte-fffffb37","e":false,"i":"","n":"getByte","t":"getByte(index: Int): Byte","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getDouble-640","e":false,"i":"","n":"getDouble","t":"getDouble(index: Int): Double","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getFloat-fffffe0d","e":false,"i":"","n":"getFloat","t":"getFloat(index: Int): Float","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getInt-fffffbe0","e":false,"i":"","n":"getInt","t":"getInt(index: Int): Int","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getJsonArray-b11","e":false,"i":"","n":"getJsonArray","t":"getJsonArray(index: Int): JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getJsonBoolean-6e0","e":false,"i":"","n":"getJsonBoolean","t":"getJsonBoolean(index: Int): JsonBoolean","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getJsonNull-435","e":false,"i":"","n":"getJsonNull","t":"getJsonNull(index: Int): JsonNull.type","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getJsonNumber-fffff991","e":false,"i":"","n":"getJsonNumber","t":"getJsonNumber(index: Int): JsonNumber","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getJsonObject-fffff187","e":false,"i":"","n":"getJsonObject","t":"getJsonObject(index: Int): JsonObject","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getJsonString-fffffe59","e":false,"i":"","n":"getJsonString","t":"getJsonString(index: Int): JsonString","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getLong-fffff0ab","e":false,"i":"","n":"getLong","t":"getLong(index: Int): Long","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getShort-fffff02d","e":false,"i":"","n":"getShort","t":"getShort(index: Int): Short","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#getString-78c","e":false,"i":"","n":"getString","t":"getString(index: Int): String","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#head-0","e":false,"i":"","n":"head","t":"head: JsonValue","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#headOption-0","e":false,"i":"","n":"headOption","t":"headOption: Option[JsonValue]","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#init-0","e":false,"i":"","n":"init","t":"init: JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#isNull-ffffff99","e":false,"i":"","n":"isNull","t":"isNull(index: Int): Boolean","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#last-0","e":false,"i":"","n":"last","t":"last: JsonValue","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#lastOption-0","e":false,"i":"","n":"lastOption","t":"lastOption: Option[JsonValue]","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#slice-70a","e":false,"i":"","n":"slice","t":"slice(from: Int, until: Int): JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#tail-0","e":false,"i":"","n":"tail","t":"tail: JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#updated-fffff893","e":false,"i":"","n":"updated","t":"updated(index: Int, value: JsonValue): JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray.html#values-0","e":false,"i":"","n":"values","t":"values: Seq[JsonValue]","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray$.html#","e":false,"i":"","n":"JsonArray","t":"JsonArray","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonArray$.html#apply-fffff32a","e":false,"i":"","n":"apply","t":"apply(): JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray$.html#apply-b15","e":false,"i":"","n":"apply","t":"apply(values: Seq[JsonValue]): JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: JsonArray","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArray$.html#unapply-a67","e":false,"i":"","n":"unapply","t":"unapply(json: JsonArray): Option[Seq[JsonValue]]","d":"grapple.json.JsonArray","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#","e":false,"i":"","n":"JsonArrayBuilder","t":"JsonArrayBuilder","d":"grapple.json","k":"class","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-fffffe0f","e":false,"i":"","n":"add","t":"add(value: JsonValue): JsonArrayBuilder.this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-cc","e":false,"i":"","n":"add","t":"add(value: String): JsonArrayBuilder.this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-241","e":false,"i":"","n":"add","t":"add(value: Byte): JsonArrayBuilder.this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-fdd","e":false,"i":"","n":"add","t":"add(value: Short): JsonArrayBuilder.this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-fffff74a","e":false,"i":"","n":"add","t":"add(value: Int): JsonArrayBuilder.this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-14d","e":false,"i":"","n":"add","t":"add(value: Long): JsonArrayBuilder.this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-fffffdfd","e":false,"i":"","n":"add","t":"add(value: Float): JsonArrayBuilder.this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-a18","e":false,"i":"","n":"add","t":"add(value: Double): JsonArrayBuilder.this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-844","e":false,"i":"","n":"add","t":"add(value: BigInt): JsonArrayBuilder.this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-ffffff22","e":false,"i":"","n":"add","t":"add(value: BigDecimal): JsonArrayBuilder.this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#add-5b1","e":false,"i":"","n":"add","t":"add(value: Boolean): JsonArrayBuilder.this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#addNull-111","e":false,"i":"","n":"addNull","t":"addNull(): JsonArrayBuilder.this.type","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonArrayBuilder.html#toJsonArray-fffff32a","e":false,"i":"","n":"toJsonArray","t":"toJsonArray(): JsonArray","d":"grapple.json.JsonArrayBuilder","k":"def","x":""},
{"l":"grapple/json/JsonBoolean.html#","e":false,"i":"","n":"JsonBoolean","t":"JsonBoolean extends JsonValue","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonBoolean.html#value-0","e":false,"i":"","n":"value","t":"value: Boolean","d":"grapple.json.JsonBoolean","k":"def","x":""},
{"l":"grapple/json/JsonBoolean$.html#","e":false,"i":"","n":"JsonBoolean","t":"JsonBoolean","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonBoolean$.html#apply-fffff419","e":false,"i":"","n":"apply","t":"apply(value: Boolean): JsonBoolean","d":"grapple.json.JsonBoolean","k":"def","x":""},
{"l":"grapple/json/JsonBoolean$.html#unapply-fffff576","e":false,"i":"","n":"unapply","t":"unapply(json: JsonBoolean): Option[Boolean]","d":"grapple.json.JsonBoolean","k":"def","x":""},
{"l":"grapple/json/JsonBoolean$$False$.html#","e":false,"i":"","n":"False","t":"False extends JsonBoolean","d":"grapple.json.JsonBoolean","k":"object","x":""},
{"l":"grapple/json/JsonBoolean$$False$.html#toString-0","e":false,"i":"","n":"toString","t":"toString: String","d":"grapple.json.JsonBoolean.False","k":"val","x":""},
{"l":"grapple/json/JsonBoolean$$False$.html#value-0","e":false,"i":"","n":"value","t":"value: Boolean","d":"grapple.json.JsonBoolean.False","k":"val","x":""},
{"l":"grapple/json/JsonBoolean$$True$.html#","e":false,"i":"","n":"True","t":"True extends JsonBoolean","d":"grapple.json.JsonBoolean","k":"object","x":""},
{"l":"grapple/json/JsonBoolean$$True$.html#toString-0","e":false,"i":"","n":"toString","t":"toString: String","d":"grapple.json.JsonBoolean.True","k":"val","x":""},
{"l":"grapple/json/JsonBoolean$$True$.html#value-0","e":false,"i":"","n":"value","t":"value: Boolean","d":"grapple.json.JsonBoolean.True","k":"val","x":""},
{"l":"grapple/json/JsonException.html#","e":false,"i":"","n":"JsonException","t":"JsonException(message: String, cause: Throwable) extends RuntimeException","d":"grapple.json","k":"class","x":""},
{"l":"grapple/json/JsonException.html#<init>-a0","e":false,"i":"","n":"this","t":"this()","d":"grapple.json.JsonException","k":"def","x":""},
{"l":"grapple/json/JsonException.html#<init>-fffff2c5","e":false,"i":"","n":"this","t":"this(message: String)","d":"grapple.json.JsonException","k":"def","x":""},
{"l":"grapple/json/JsonException.html#<init>-40c","e":false,"i":"","n":"this","t":"this(cause: Throwable)","d":"grapple.json.JsonException","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#","e":false,"i":"","n":"JsonGenerator","t":"JsonGenerator extends AutoCloseable","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonGenerator.html#close-94c","e":false,"i":"","n":"close","t":"close(): Unit","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#flush-94c","e":false,"i":"","n":"flush","t":"flush(): Unit","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffff74b","e":false,"i":"","n":"write","t":"write(name: String, value: JsonValue): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-56e","e":false,"i":"","n":"write","t":"write(name: String, value: String): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fd9","e":false,"i":"","n":"write","t":"write(name: String, value: Byte): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffff493","e":false,"i":"","n":"write","t":"write(name: String, value: Short): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-ffffff06","e":false,"i":"","n":"write","t":"write(name: String, value: Int): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffffc4d","e":false,"i":"","n":"write","t":"write(name: String, value: Long): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffffa73","e":false,"i":"","n":"write","t":"write(name: String, value: Float): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffffa22","e":false,"i":"","n":"write","t":"write(name: String, value: Double): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffff54c","e":false,"i":"","n":"write","t":"write(name: String, value: BigInt): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffff5ae","e":false,"i":"","n":"write","t":"write(name: String, value: BigDecimal): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-c7f","e":false,"i":"","n":"write","t":"write(name: String, value: Boolean): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-ee6","e":false,"i":"","n":"write","t":"write(value: JsonValue): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-d49","e":false,"i":"","n":"write","t":"write(value: String): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-7f4","e":false,"i":"","n":"write","t":"write(value: Byte): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fd8","e":false,"i":"","n":"write","t":"write(value: Short): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-78b","e":false,"i":"","n":"write","t":"write(value: Int): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-468","e":false,"i":"","n":"write","t":"write(value: Long): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffff5b8","e":false,"i":"","n":"write","t":"write(value: Float): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-77d","e":false,"i":"","n":"write","t":"write(value: Double): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-8d1","e":false,"i":"","n":"write","t":"write(value: BigInt): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffffeb3","e":false,"i":"","n":"write","t":"write(value: BigDecimal): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#write-fffffa84","e":false,"i":"","n":"write","t":"write(value: Boolean): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#writeEnd-b24","e":false,"i":"","n":"writeEnd","t":"writeEnd(): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#writeNull-d49","e":false,"i":"","n":"writeNull","t":"writeNull(name: String): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#writeNull-b24","e":false,"i":"","n":"writeNull","t":"writeNull(): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#writeStartArray-d49","e":false,"i":"","n":"writeStartArray","t":"writeStartArray(name: String): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#writeStartArray-b24","e":false,"i":"","n":"writeStartArray","t":"writeStartArray(): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#writeStartObject-d49","e":false,"i":"","n":"writeStartObject","t":"writeStartObject(name: String): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator.html#writeStartObject-b24","e":false,"i":"","n":"writeStartObject","t":"writeStartObject(): JsonGenerator.this.type","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator$.html#","e":false,"i":"","n":"JsonGenerator","t":"JsonGenerator","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonGenerator$.html#apply-fffff818","e":false,"i":"","n":"apply","t":"apply(output: Writer, indent: String): JsonGenerator","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator$.html#apply-3f3","e":false,"i":"","n":"apply","t":"apply(output: Writer): JsonGenerator","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator$.html#apply-506","e":false,"i":"","n":"apply","t":"apply(output: OutputStream, indent: String): JsonGenerator","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator$.html#apply-fffffce1","e":false,"i":"","n":"apply","t":"apply(output: OutputStream): JsonGenerator","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator$.html#apply-fffff4e1","e":false,"i":"","n":"apply","t":"apply(output: File, indent: String): JsonGenerator","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator$.html#apply-2bc","e":false,"i":"","n":"apply","t":"apply(output: File): JsonGenerator","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator$.html#apply-75a","e":false,"i":"","n":"apply","t":"apply(output: Path, indent: String): JsonGenerator","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGenerator$.html#apply-fffff735","e":false,"i":"","n":"apply","t":"apply(output: Path): JsonGenerator","d":"grapple.json.JsonGenerator","k":"def","x":""},
{"l":"grapple/json/JsonGeneratorError.html#","e":false,"i":"","n":"JsonGeneratorError","t":"JsonGeneratorError(message: String) extends JsonException","d":"grapple.json","k":"class","x":""},
{"l":"grapple/json/JsonInput.html#","e":false,"i":"","n":"JsonInput","t":"JsonInput[T]","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonInput.html#read-fffff7d5","e":false,"i":"","n":"read","t":"read(value: JsonValue): T","d":"grapple.json.JsonInput","k":"def","x":""},
{"l":"grapple/json/JsonNull$.html#","e":false,"i":"","n":"JsonNull","t":"JsonNull extends JsonValue","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonNull$.html#toString-0","e":false,"i":"","n":"toString","t":"toString: String","d":"grapple.json.JsonNull","k":"val","x":""},
{"l":"grapple/json/JsonNumber.html#","e":false,"i":"","n":"JsonNumber","t":"JsonNumber extends JsonValue","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonNumber.html#bigDecimalValue-0","e":false,"i":"","n":"bigDecimalValue","t":"bigDecimalValue: BigDecimal","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber.html#bigIntValue-0","e":false,"i":"","n":"bigIntValue","t":"bigIntValue: BigInt","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber.html#byteValue-0","e":false,"i":"","n":"byteValue","t":"byteValue: Byte","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber.html#doubleValue-0","e":false,"i":"","n":"doubleValue","t":"doubleValue: Double","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber.html#floatValue-0","e":false,"i":"","n":"floatValue","t":"floatValue: Float","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber.html#intValue-0","e":false,"i":"","n":"intValue","t":"intValue: Int","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber.html#longValue-0","e":false,"i":"","n":"longValue","t":"longValue: Long","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber.html#shortValue-0","e":false,"i":"","n":"shortValue","t":"shortValue: Short","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber$.html#","e":false,"i":"","n":"JsonNumber","t":"JsonNumber","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonNumber$.html#apply-c93","e":false,"i":"","n":"apply","t":"apply(value: String): JsonNumber","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber$.html#apply-fffff991","e":false,"i":"","n":"apply","t":"apply(value: Int): JsonNumber","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber$.html#apply-1d4","e":false,"i":"","n":"apply","t":"apply(value: Long): JsonNumber","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber$.html#apply-edf","e":false,"i":"","n":"apply","t":"apply(value: Double): JsonNumber","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber$.html#apply-e0b","e":false,"i":"","n":"apply","t":"apply(value: BigInt): JsonNumber","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber$.html#apply-fffff369","e":false,"i":"","n":"apply","t":"apply(value: BigDecimal): JsonNumber","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonNumber$.html#unapply-fffff6d5","e":false,"i":"","n":"unapply","t":"unapply(json: JsonNumber): Option[BigDecimal]","d":"grapple.json.JsonNumber","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#","e":false,"i":"","n":"JsonObject","t":"JsonObject extends JsonStructure","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonObject.html#+-fffff51c","e":false,"i":"","n":"+","t":"+(field: (String, JsonValue)): JsonObject","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#++-fffff040","e":false,"i":"","n":"++","t":"++(other: JsonObject): JsonObject","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#--489","e":false,"i":"","n":"-","t":"-(name: String): JsonObject","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#apply-fffffee7","e":false,"i":"","n":"apply","t":"apply(name: String): JsonValue","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#fields-0","e":false,"i":"","n":"fields","t":"fields: Map[String, JsonValue]","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#get-fffffd22","e":false,"i":"","n":"get","t":"get(name: String): Option[JsonValue]","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getBigDecimal-fffff30a","e":false,"i":"","n":"getBigDecimal","t":"getBigDecimal(name: String): BigDecimal","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getBigInt-fffffc28","e":false,"i":"","n":"getBigInt","t":"getBigInt(name: String): BigInt","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getBoolean-fffffd1b","e":false,"i":"","n":"getBoolean","t":"getBoolean(name: String): Boolean","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getByte-cf5","e":false,"i":"","n":"getByte","t":"getByte(name: String): Byte","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getDouble-fffff07e","e":false,"i":"","n":"getDouble","t":"getDouble(name: String): Double","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getFloat-fffff40f","e":false,"i":"","n":"getFloat","t":"getFloat(name: String): Float","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getInt-a62","e":false,"i":"","n":"getInt","t":"getInt(name: String): Int","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getJsonArray-ffffffcf","e":false,"i":"","n":"getJsonArray","t":"getJsonArray(name: String): JsonArray","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getJsonBoolean-41e","e":false,"i":"","n":"getJsonBoolean","t":"getJsonBoolean(name: String): JsonBoolean","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getJsonNull-fffff8f3","e":false,"i":"","n":"getJsonNull","t":"getJsonNull(name: String): JsonNull.type","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getJsonNumber-c93","e":false,"i":"","n":"getJsonNumber","t":"getJsonNumber(name: String): JsonNumber","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getJsonObject-489","e":false,"i":"","n":"getJsonObject","t":"getJsonObject(name: String): JsonObject","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getJsonString-15b","e":false,"i":"","n":"getJsonString","t":"getJsonString(name: String): JsonString","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getLong-269","e":false,"i":"","n":"getLong","t":"getLong(name: String): Long","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getOrElse-1e8","e":false,"i":"","n":"getOrElse","t":"getOrElse[T](name: String, default: => T)(using JsonInput[T]): T","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getShort-fffff62f","e":false,"i":"","n":"getShort","t":"getShort(name: String): Short","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#getString-fffff2ca","e":false,"i":"","n":"getString","t":"getString(name: String): String","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#isNull-fffffd1b","e":false,"i":"","n":"isNull","t":"isNull(name: String): Boolean","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#map-fffffd6e","e":false,"i":"","n":"map","t":"map[T](name: String)(using JsonInput[T]): Option[T]","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject.html#names-0","e":false,"i":"","n":"names","t":"names: Seq[String]","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject$.html#","e":false,"i":"","n":"JsonObject","t":"JsonObject","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonObject$.html#apply-fffffc8e","e":false,"i":"","n":"apply","t":"apply(): JsonObject","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject$.html#apply-fffffc66","e":false,"i":"","n":"apply","t":"apply(fields: Map[String, JsonValue]): JsonObject","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject$.html#apply-fffff203","e":false,"i":"","n":"apply","t":"apply(fields: Seq[(String, JsonValue)]): JsonObject","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: JsonObject","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObject$.html#unapply-dcb","e":false,"i":"","n":"unapply","t":"unapply(json: JsonObject): Option[Map[String, JsonValue]]","d":"grapple.json.JsonObject","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#","e":false,"i":"","n":"JsonObjectBuilder","t":"JsonObjectBuilder","d":"grapple.json","k":"class","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-fd4","e":false,"i":"","n":"add","t":"add(name: String, value: JsonValue): JsonObjectBuilder.this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-477","e":false,"i":"","n":"add","t":"add(name: String, value: String): JsonObjectBuilder.this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-fffff162","e":false,"i":"","n":"add","t":"add(name: String, value: Byte): JsonObjectBuilder.this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-fffff91c","e":false,"i":"","n":"add","t":"add(name: String, value: Short): JsonObjectBuilder.this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-20f","e":false,"i":"","n":"add","t":"add(name: String, value: Int): JsonObjectBuilder.this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-3d6","e":false,"i":"","n":"add","t":"add(name: String, value: Long): JsonObjectBuilder.this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-fffffefc","e":false,"i":"","n":"add","t":"add(name: String, value: Float): JsonObjectBuilder.this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-ffffff2b","e":false,"i":"","n":"add","t":"add(name: String, value: Double): JsonObjectBuilder.this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-fffff555","e":false,"i":"","n":"add","t":"add(name: String, value: BigInt): JsonObjectBuilder.this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-4b7","e":false,"i":"","n":"add","t":"add(name: String, value: BigDecimal): JsonObjectBuilder.this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#add-b08","e":false,"i":"","n":"add","t":"add(name: String, value: Boolean): JsonObjectBuilder.this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#addNull-fffff6d2","e":false,"i":"","n":"addNull","t":"addNull(name: String): JsonObjectBuilder.this.type","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonObjectBuilder.html#toJsonObject-fffffc8e","e":false,"i":"","n":"toJsonObject","t":"toJsonObject(): JsonObject","d":"grapple.json.JsonObjectBuilder","k":"def","x":""},
{"l":"grapple/json/JsonOutput.html#","e":false,"i":"","n":"JsonOutput","t":"JsonOutput[T]","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonOutput.html#write-fffffb95","e":false,"i":"","n":"write","t":"write(value: T): JsonValue","d":"grapple.json.JsonOutput","k":"def","x":""},
{"l":"grapple/json/JsonParser.html#","e":false,"i":"","n":"JsonParser","t":"JsonParser extends Iterator[Event], AutoCloseable","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonParser.html#close-94c","e":false,"i":"","n":"close","t":"close(): Unit","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser.html#getArray-fffff32a","e":false,"i":"","n":"getArray","t":"getArray(): JsonArray","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser.html#getObject-fffffc8e","e":false,"i":"","n":"getObject","t":"getObject(): JsonObject","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser.html#hasNext-0","e":false,"i":"","n":"hasNext","t":"hasNext: Boolean","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser.html#next-702","e":false,"i":"","n":"next","t":"next(): Event","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser$.html#","e":false,"i":"","n":"JsonParser","t":"JsonParser","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonParser$.html#apply-8af","e":false,"i":"","n":"apply","t":"apply(input: Reader): JsonParser","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser$.html#apply-d69","e":false,"i":"","n":"apply","t":"apply(text: String): JsonParser","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser$.html#apply-fffff4fc","e":false,"i":"","n":"apply","t":"apply(bytes: Array[Byte]): JsonParser","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser$.html#apply-fffff59c","e":false,"i":"","n":"apply","t":"apply(bytes: Array[Byte], offset: Int, length: Int): JsonParser","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser$.html#apply-160","e":false,"i":"","n":"apply","t":"apply(input: InputStream): JsonParser","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser$.html#apply-4d6","e":false,"i":"","n":"apply","t":"apply(input: File): JsonParser","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser$.html#apply-fffffafd","e":false,"i":"","n":"apply","t":"apply(input: Path): JsonParser","d":"grapple.json.JsonParser","k":"def","x":""},
{"l":"grapple/json/JsonParser$$Event.html#","e":false,"i":"","n":"Event","t":"Event","d":"grapple.json.JsonParser","k":"enum","x":""},
{"l":"grapple/json/JsonParser$$Event$$FieldName.html#","e":false,"i":"","n":"FieldName","t":"FieldName(get: String) extends Event","d":"grapple.json.JsonParser.Event","k":"case","x":""},
{"l":"grapple/json/JsonParser$$Event$$Value.html#","e":false,"i":"","n":"Value","t":"Value(get: JsonValue) extends Event","d":"grapple.json.JsonParser.Event","k":"case","x":""},
{"l":"grapple/json/JsonParser$$Event.html#StartObject-0","e":false,"i":"","n":"StartObject","t":"StartObject extends Event","d":"grapple.json.JsonParser.Event","k":"case","x":""},
{"l":"grapple/json/JsonParser$$Event.html#StartArray-0","e":false,"i":"","n":"StartArray","t":"StartArray extends Event","d":"grapple.json.JsonParser.Event","k":"case","x":""},
{"l":"grapple/json/JsonParser$$Event.html#EndObject-0","e":false,"i":"","n":"EndObject","t":"EndObject extends Event","d":"grapple.json.JsonParser.Event","k":"case","x":""},
{"l":"grapple/json/JsonParser$$Event.html#EndArray-0","e":false,"i":"","n":"EndArray","t":"EndArray extends Event","d":"grapple.json.JsonParser.Event","k":"case","x":""},
{"l":"grapple/json/JsonParser$$Event$$FieldName.html#","e":false,"i":"","n":"FieldName","t":"FieldName(get: String) extends Event","d":"grapple.json.JsonParser.Event","k":"case","x":""},
{"l":"grapple/json/JsonParser$$Event$$Value.html#","e":false,"i":"","n":"Value","t":"Value(get: JsonValue) extends Event","d":"grapple.json.JsonParser.Event","k":"case","x":""},
{"l":"grapple/json/JsonParserError.html#","e":false,"i":"","n":"JsonParserError","t":"JsonParserError(message: String, offset: Long) extends JsonException","d":"grapple.json","k":"class","x":""},
{"l":"grapple/json/JsonReader.html#","e":false,"i":"","n":"JsonReader","t":"JsonReader extends AutoCloseable","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonReader.html#close-94c","e":false,"i":"","n":"close","t":"close(): Unit","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonReader.html#read-dc4","e":false,"i":"","n":"read","t":"read(): JsonStructure","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonReader$.html#","e":false,"i":"","n":"JsonReader","t":"JsonReader","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonReader$.html#apply-a0d","e":false,"i":"","n":"apply","t":"apply(text: String): JsonReader","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonReader$.html#apply-fffff1a0","e":false,"i":"","n":"apply","t":"apply(bytes: Array[Byte]): JsonReader","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonReader$.html#apply-fffff240","e":false,"i":"","n":"apply","t":"apply(bytes: Array[Byte], offset: Int, length: Int): JsonReader","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonReader$.html#apply-553","e":false,"i":"","n":"apply","t":"apply(input: Reader): JsonReader","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonReader$.html#apply-e04","e":false,"i":"","n":"apply","t":"apply(input: InputStream): JsonReader","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonReader$.html#apply-17a","e":false,"i":"","n":"apply","t":"apply(input: File): JsonReader","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonReader$.html#apply-fffff7a1","e":false,"i":"","n":"apply","t":"apply(input: Path): JsonReader","d":"grapple.json.JsonReader","k":"def","x":""},
{"l":"grapple/json/JsonString.html#","e":false,"i":"","n":"JsonString","t":"JsonString extends JsonValue","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonString.html#value-0","e":false,"i":"","n":"value","t":"value: String","d":"grapple.json.JsonString","k":"def","x":""},
{"l":"grapple/json/JsonString$.html#","e":false,"i":"","n":"JsonString","t":"JsonString","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonString$.html#apply-15b","e":false,"i":"","n":"apply","t":"apply(value: String): JsonString","d":"grapple.json.JsonString","k":"def","x":""},
{"l":"grapple/json/JsonString$.html#unapply-ffffff9d","e":false,"i":"","n":"unapply","t":"unapply(json: JsonString): Option[String]","d":"grapple.json.JsonString","k":"def","x":""},
{"l":"grapple/json/JsonStructure.html#","e":false,"i":"","n":"JsonStructure","t":"JsonStructure extends JsonValue","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonStructure.html#isEmpty-0","e":false,"i":"","n":"isEmpty","t":"isEmpty: Boolean","d":"grapple.json.JsonStructure","k":"def","x":""},
{"l":"grapple/json/JsonStructure.html#size-0","e":false,"i":"","n":"size","t":"size: Int","d":"grapple.json.JsonStructure","k":"def","x":""},
{"l":"grapple/json/JsonValue.html#","e":false,"i":"","n":"JsonValue","t":"JsonValue","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonValue.html#as-f9f","e":false,"i":"","n":"as","t":"as[T](using converter: JsonInput[T]): T","d":"grapple.json.JsonValue","k":"def","x":""},
{"l":"grapple/json/JsonWriter.html#","e":false,"i":"","n":"JsonWriter","t":"JsonWriter extends AutoCloseable","d":"grapple.json","k":"trait","x":""},
{"l":"grapple/json/JsonWriter.html#close-94c","e":false,"i":"","n":"close","t":"close(): Unit","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter.html#write-37e","e":false,"i":"","n":"write","t":"write(value: JsonStructure): JsonWriter.this.type","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter$.html#","e":false,"i":"","n":"JsonWriter","t":"JsonWriter","d":"grapple.json","k":"object","x":""},
{"l":"grapple/json/JsonWriter$.html#apply-fffff54e","e":false,"i":"","n":"apply","t":"apply(output: Writer, indent: String): JsonWriter","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter$.html#apply-f53","e":false,"i":"","n":"apply","t":"apply(output: Writer): JsonWriter","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter$.html#apply-ffffff20","e":false,"i":"","n":"apply","t":"apply(output: OutputStream, indent: String): JsonWriter","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter$.html#apply-d25","e":false,"i":"","n":"apply","t":"apply(output: OutputStream): JsonWriter","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter$.html#apply-fffff525","e":false,"i":"","n":"apply","t":"apply(output: File, indent: String): JsonWriter","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter$.html#apply-d2a","e":false,"i":"","n":"apply","t":"apply(output: File): JsonWriter","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter$.html#apply-fffffd4c","e":false,"i":"","n":"apply","t":"apply(output: Path, indent: String): JsonWriter","d":"grapple.json.JsonWriter","k":"def","x":""},
{"l":"grapple/json/JsonWriter$.html#apply-fffff351","e":false,"i":"","n":"apply","t":"apply(output: Path): JsonWriter","d":"grapple.json.JsonWriter","k":"def","x":""}];